add update file tests
0chain/system_test pull request #100
Opened 2021-11-06 18:55 UTC by littlestar642

2021-11-08 17:55 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_create_allocation_test.go
> -	t.Logf("Creating new allocation...")
Why remove this?

2021-11-08 17:55 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_update_test.go
> +		// require.NotEqual(t, originalFileChecksum, downloadedFileChecksum)
Remove commented code

2021-11-08 17:55 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_update_test.go
> +		require.Equal(t, originalFileChecksum, downloadedFileChecksum)
Why are we downloading a file here? For updateFile with commit, we should just be asserting on the CLI output received from `./zbox update` command. Here's an example output from that command:

```
 20 / 20 [==========================================================================================================================================================] 100.00% 1s
Status completed callback. Type = application/octet-stream. Name = test.txt
Commit Metadata successful, Response : {"TxnID":"50d6e785edbc947d651b615e91323a8b1b8c7003bf514f6d15e51ab3c29a808c","MetaData":{"Name":"test.txt","Type":"f","Path":"/test.txt","LookupHash":"00fbea45136bb5febe585b5e5f4e84111e188ef3d00e6caa986db6be8bed1af4","Hash":"9ca0a454937b5ab9bc98161e413ba1202987c017233851c00957f77d5473c706","MimeType":"application/octet-stream","Size":20,"ActualFileSize":10,"ActualNumBlocks":1,"EncryptedKey":"","CommitMetaTxns":[{"ref_id":666,"txn_id":"ae698fe90ebb279ce2e745fada5d4116ef6a5810c52361856a89b3d594f8ae46","created_at":"2021-11-08T17:48:47.128947Z"}],"Collaborators":[],"Attributes":{}}}
```

2021-11-08 17:55 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_update_test.go
> +	require.Nil(t, err, strings.Join(output, "\n"))
assertions on output required

2021-11-08 17:55 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_update_test.go
> +	require.Nil(t, err, strings.Join(output, "\n"))
Assertions on output required

2021-11-08 17:55 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_upload_test.go
> -	t.Logf("Uploading file...")
Why remove this?

2021-11-08 19:31 UTC, stewartie4 commented on tests/cli_tests/zboxcli_upload_test.go
> -	t.Logf("Uploading file...")
uploadFileForWallet already logs this I think

2021-11-09 14:28 UTC, littlestar642 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> -	t.Logf("Creating new allocation...")
redundant log.

2021-11-09 14:30 UTC, littlestar642 commented on tests/cli_tests/zboxcli_file_update_test.go
> +		require.Equal(t, originalFileChecksum, downloadedFileChecksum)
I considered downloading the file and then check for the metadata as a more fool proof way to assert. It ensures that the metadata did got committed to the file.

2021-11-09 14:32 UTC, littlestar642 commented on tests/cli_tests/zboxcli_upload_test.go
> -	t.Logf("Uploading file...")
yeah, its redundant

2021-11-09 14:34 UTC, littlestar642 commented on tests/cli_tests/zboxcli_file_update_test.go
> +		// require.NotEqual(t, originalFileChecksum, downloadedFileChecksum)
This code bit is not working. I have mentioned it to be because of buggy thumbnail download.  
I will remove the commented part as of now and would be taken care by the person who will work on this later.

2021-11-14 05:49 UTC, avanaur commented on tests/cli_tests/zboxcli_download_test.go
> +		wait(t, 15*time.Second)
There is already a 15s wait inside downloadFile. Should just adjust that if necessary.

2021-11-14 05:49 UTC, avanaur commented on tests/cli_tests/zboxcli_upload_token_test.go
> +func uploadCostWithUnit(t *testing.T, cliConfigFilename, allocationID, localpath string) (cost float64, unit string) {
This can call getUploadCostInUnit() internally

2021-11-14 05:49 UTC, avanaur commented on tests/cli_tests/zboxcli_upload_token_test.go
> +	require.Len(t, output, 1, strings.Join(output, "\n"))
The team agreed that all assertions are best within the test function. Reason why functions to call cli command are always returning the raw output and error. 

This would result to duplicate codes and very long test functions.

2021-11-14 05:49 UTC, avanaur commented on tests/cli_tests/zboxcli_file_update_test.go
> +	require.Len(t, output, 2)
should assert the contents of output. only exemption if too random
what's the example output?

2021-11-14 20:20 UTC, Kishan-Dhakan commented on tests/cli_tests/broken_scenarios_test.go
> +		require.Len(t, output, 2)
Instead of calling `updateFileWithThumbnailURL` twice, we could initially upload the file with a thumbnail parameter (like [here](https://github.com/0chain/system_test/blob/7c45c874547f18aaedc7eebb9ff3d252cf116e6b/tests/cli_tests/zboxcli_download_test.go#L552)) and then update it by calling `updateFileWithThumbnailURL` once to test it. This reduces number of uploads from 3 to 2.

2021-11-14 20:20 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_test.go
> +		require.NotNil(t, err, strings.Join(output, "\n"))
Why? Is this a FIXME? Can you add a comment here if so

2021-11-14 20:20 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_update_test.go
> +	t.Run("update existing file in another allocation", func(t *testing.T) {
I could not understand this case. What's `another` allocation here?

2021-11-15 04:06 UTC, mohsenno1 requested changes

2021-11-15 04:06 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_file_update_test.go
> +	t.Run("update with another file of size larger than allocation", func(t *testing.T) {
As above, test expectation in test name is missing

2021-11-15 04:06 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_file_update_test.go
> +	t.Run("update encrypted file with encrypted file", func(t *testing.T) {
As above, test expectation in test name is missing

2021-11-15 04:06 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_file_update_test.go
> +	t.Run("update encrypted file with non-encrypted file", func(t *testing.T) {
As above, test expectation in test name is missing

2021-11-17 00:22 UTC, stewartie4 approved these changes

2021-11-17 00:22 UTC, merged