rectify file update tests
0chain/system_test pull request #102
Opened 2021-11-09 14:52 UTC by littlestar642

2021-11-09 17:17 UTC, stewartie4 commented
@littlestar642 how does this relate to
https://github.com/0chain/system_test/pull/100

2021-11-09 18:48 UTC, Kishan-Dhakan commented
I renamed the PR to refer to `file stats` correction instead of `file update`

2021-11-09 18:57 UTC, Kishan-Dhakan requested changes

2021-11-09 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_stats_test.go
>  			}
Since file size is updated, assert on data.size too?

2021-11-12 14:00 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_stats_test.go
>  			// require.Equal(t, blobberID, data.BlobberID, "key name and blobberID in value should be same")
@littlestar642 should this still be commented out?

2021-11-12 14:04 UTC, merged