Test/mobile sdk split key
0chain/system_test pull request #1024
Opened 2024-03-01 17:05 UTC by Ash-KODES

2024-03-08 15:30 UTC, Jayashsatolia403 requested changes

2024-03-08 15:30 UTC, Jayashsatolia403 commented on go.mod
> +	github.com/herumi/bls-go-binary v1.33.0
Why do you need to update bls version?

2024-03-08 15:30 UTC, Jayashsatolia403 commented on tests/api_tests/split_key_wallet_mobile_test.go
> +			{
Remove comments.

2024-03-09 16:51 UTC, Ash-KODES commented on go.mod
> +	github.com/herumi/bls-go-binary v1.33.0
Actually don't need it,degraded that.

2024-03-09 17:19 UTC, Jayashsatolia403 approved these changes
lgtm, merge on green run

2024-03-09 19:16 UTC, merged