Transfer Allocation tests
0chain/system_test pull request #106
Opened 2021-11-11 23:24 UTC by avanaur

Cases covered:
- transfer allocation by owner should fail
- transfer allocation by curator
- transfer allocation by non-owner and non-curator should fail
- transfer allocation to self
- transfer an expired allocation
- transfer a canceled allocation (test is skipped - not doable)
- transfer a finalized allocation (test is skipped - not working)
- transfer allocation and download non-encrypted file
- transfer allocation and download encrypted file should fail
- transfer allocation and download with auth ticket should fail
- transfer allocation and upload file
- transfer allocation and update allocation
- transfer allocation with no allocation param should fail
- transfer allocation with no new_owner_key param should fail
- transfer allocation with no new_owner param should fail
- transfer allocation with invalid allocation param should fail
- transfer allocation with invalid new_owner param
- transfer allocation with invalid new_owner_key param should fail
- transfer allocation accounting test

2021-11-12 23:52 UTC, stewartie4 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		t.Skip("Finalizing allocation is not working")
instead of skipping this test here can you add it to broken scenarios file?
That way it will continue to run on master

2021-11-13 00:01 UTC, stewartie4 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		case <-timeout:
could you replace the switch statement with a simpler if statement?

2021-11-13 08:38 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		case <-timeout:
this is actually a select statement which checks if timeout channel is available, if not then it just continue

2021-11-13 09:16 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		t.Skip("Finalizing allocation is not working")
Decided to retain and assert the error.
Also, for some reason, cancel allocation is working so had that enable now.

2021-11-13 09:41 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		t.Skip("Finalizing allocation is not working")
Hmm this is kinda tricky. Cancel allocation works on dev but not on CI run. Might just make it work for CI.

2021-11-14 11:15 UTC, stewartie4 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		t.Skip("Finalizing allocation is not working")
yeah @Sriep and myself have been chatting about this
instant cancel should work I think

2021-11-14 11:16 UTC, stewartie4 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		case <-timeout:
yeah I was just wondering if it was possible to do it as an if statement instead but it's minor, nvm

2021-11-14 11:16 UTC, stewartie4 approved these changes

2021-11-14 12:27 UTC, littlestar642 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.NotNil(t, err, strings.Join(output, "\n"))
Since this is not working, should we move this to broken scenarios test file?

2021-11-14 20:39 UTC, Kishan-Dhakan approved these changes

2021-11-14 20:39 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.Equal(t, "Status completed callback. Type = application/octet-stream. Name = "+filepath.Base(file), output[1])
Is uploading a file necessary for this case?

2021-11-14 20:39 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.Equal(t, allocationID, finalWritePool[0].AllocationId, strings.Join(output, "\n"))
This might be what's happening right now but should it? I'd imagine if I'm no longer an owner of the allocation my tokens should be returned. New guy can pay for it, if new guys doesn't have enough wallet balance, transfer should fail.

thoughts @avanaur @stewartie4?

2021-11-14 20:39 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.Equal(t, "Status completed callback. Type = application/octet-stream. Name = "+filepath.Base(file), output[1])
Ah I think it's needed for polling transfer complete got it

2021-11-14 20:51 UTC, stewartie4 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.Equal(t, allocationID, finalWritePool[0].AllocationId, strings.Join(output, "\n"))
Agreed can you check up on this with the blockchain guys @avanaur ? if you don't get anywhere can you add a FIXME comment?

2021-11-14 20:52 UTC, stewartie4 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.NotNil(t, err, strings.Join(output, "\n"))
The assertion is asserting on it not working so i think this is fine as-is so long as there is a FIXME comment (which there is)

2021-11-15 01:30 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.Equal(t, "Status completed callback. Type = application/octet-stream. Name = "+filepath.Base(file), output[1])
Yeah, it is a hack. Can't think of another way to confirm transfer is complete. 
With a dummy file and list-all, I get a better confirmation that transfer is done given list-all requires a high consensus before it adds a file in the result.

2021-11-15 01:34 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.Equal(t, allocationID, finalWritePool[0].AllocationId, strings.Join(output, "\n"))
Yeah, I'll add a FIXME and ask on the blockchain channel.

2021-11-15 10:10 UTC, mohsenno1 requested changes

2021-11-15 10:10 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +	// FIXME is this expected to fail?
I'm agree with you, this should fail. Actually there is no check on curator or collaborator too. Literally you can add any string with any length as curator or collaborator. Here is the same. At least there should be a check to test if the parameter is valid node id. Or more advanced to check if the node exists or not.

2021-11-15 10:10 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		// write lock pool of old owner should remain locked
```suggestion
		// write pool lock of old owner should remain locked
```

2021-11-15 10:15 UTC, avanaur commented on tests/cli_tests/zboxcli_create_dir_test.go
>  	time.Sleep(5 * time.Second)
I am not really keen to remove it on this PR given its another test entirely. 
We can look intor removing those explicit wait on another ticket and see if no issue with existing tests.
Thoughts @stewartie4 , @Kishan-Dhakan ?

2021-11-15 10:24 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		transferred := pollForAllocationTransferToEffect(t, newOwner, allocationID)
Yes AFAIK that is correct, zbox waits for txn confirmation. However from testing the txn confirmation is not enough.

Upload, download, and update allocation fails most of the time when trying with the new owner right away. 

To have high confidence that those will work, need to wait until the new owner can list the files of the allocation.
Perhaps there is better approach but this is the only one that worked and make the test stable.

2021-11-15 10:51 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +	// FIXME is this expected to fail?
Yeah agreed. Should at least have check
- new_owner_key is a valid pubkey (length + char allower)
- new_ower is a valid client (length + char allowed)
- new_owner and new_owner_key are valid pairs

2021-11-15 11:33 UTC, avanaur commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		require.Len(t, output, 2)
updated all to add extra message on assertions

2021-11-15 16:21 UTC, stewartie4 commented on tests/cli_tests/zboxcli_create_dir_test.go
>  	time.Sleep(5 * time.Second)
I agree, I will add a point to https://github.com/0chain/system_test/issues/32

2021-11-15 16:32 UTC, stewartie4 commented
I'll raise bugs for all of these

2021-11-15 18:06 UTC, merged