updated: added test cases for storage version
0chain/system_test pull request #1114
Opened 2024-10-07 19:44 UTC by Akhilesh53

Added System Tests for new storage version changes

2024-10-07 19:47 UTC, Jayashsatolia403 requested changes

2024-10-07 19:47 UTC, Jayashsatolia403 commented on tests/api_tests/update_blobber_test.go
> +	// write a test case to update the blobber version
Remove it

2024-10-07 19:47 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +	// write a test case to create the allocation with storage version and managing wallet
Add negative tests as well.

2024-10-07 19:47 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber version should work", func(t *test.SystemTest) {
Add negative tests as well : for example blobber should not be able to downgrade from v2 to v1.

2024-10-08 15:35 UTC, Akhilesh53 commented on tests/api_tests/update_blobber_test.go
> +	// write a test case to update the blobber version
means remove this function?

2024-10-08 15:35 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +	// write a test case to create the allocation with storage version and managing wallet
Resolved

2024-10-08 15:35 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber version should work", func(t *test.SystemTest) {
Resolved

2024-10-10 18:44 UTC, Jayashsatolia403 requested changes

2024-10-10 18:44 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber managing wallet should fail", func(t *test.SystemTest) {
Remove this test case for now. We can add it in api tests. You shouldn't add invalid fields directly in the CLI.

2024-10-10 18:44 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +	// write a test case to create the allocation with storage version and managing wallet
I don't see it. Can you mention the name please?

2024-10-10 18:44 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber version should fail", func(t *test.SystemTest) {
Why should this fail?

2024-10-10 18:44 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber version should work", func(t *test.SystemTest) {
It's not correct. Please check the comment.

2024-10-10 18:46 UTC, Jayashsatolia403 requested changes

2024-10-10 18:46 UTC, Jayashsatolia403 commented on tests/api_tests/update_blobber_test.go
> +	// write a test case to update the blobber version
Test is not for update blobber settings so you can't add this subtest here. Remove it.

2024-10-10 18:58 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +	// write a test case to create the allocation with storage version and managing wallet
You mentioned in the chat to remove the negative tc—that wont work.

2024-10-10 18:59 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +	// write a test case to create the allocation with storage version and managing wallet
You mentioned on chat to remove the negative test. I told you, that

2024-10-10 19:00 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber version should work", func(t *test.SystemTest) {
Negative test is mentioned below.

2024-10-10 19:02 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber managing wallet should fail", func(t *test.SystemTest) {
removed

2024-10-11 04:48 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber version should fail", func(t *test.SystemTest) {
This will fail bcz managing wallet will work with version4 only. Blobber version update is not woring. Updated version us coming as 0 after .update. Tp update the wallet this is mandatory condition

2024-10-13 19:12 UTC, Jayashsatolia403 requested changes

2024-10-13 19:12 UTC, Jayashsatolia403 commented on tests/api_tests/register_blobber_test.go
> +		apiClient.KillBlobber(t, scWallet, killBlobberReq, 1)
Add it in defer func.

2024-10-13 19:12 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +			"storage_version": 2,
Keep it storage version 1.

2024-10-13 19:12 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber version should fail", func(t *test.SystemTest) {
What do you mean? Why should update version depend on managing wallet at all?

2024-10-13 19:12 UTC, Jayashsatolia403 commented on tests/api_tests/update_blobber_test.go
> +		blobber.StorageVersion = 2
Set to 1. We only have 0 and 1 for now.

2024-10-13 19:12 UTC, Jayashsatolia403 commented on tests/api_tests/update_blobber_test.go
> +		blobber.StorageVersion = 1
Set to 0. We only have 0 and 1 for now.

2024-10-13 19:12 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +		// todo: not able to upate the version of blobber. Only v4 will have managing wallet
Sort our TODOs.

2024-10-14 17:51 UTC, Jayashsatolia403 requested changes

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/api_tests/main_test.go
> +	walletIdx = int64(rand.Intn(len(initialisedWallets)))
Revert it.

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/api_tests/update_blobber_test.go
> +		apiClient.UpdateBlobber(t, wallet, blobber, client.TxUnsuccessfulStatus)
Add getBlobber to verify version is added properly.

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/api_tests/update_blobber_test.go
> +		apiClient.UpdateBlobber(t, wallet, blobber, client.TxUnsuccessfulStatus)
Same

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/cli_tests/config/config.yaml
> +ethereum_node_url: "https://virtual.mainnet.rpc.tenderly.co/1b2b3323-9a80-49c3-a2ff-50efb7afb359"
Revert

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/cli_tests/config/zbox_config.yaml
> +ethereum_node_url: "https://virtual.mainnet.rpc.tenderly.co/1b2b3323-9a80-49c3-a2ff-50efb7afb359"
Revert

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +			"storage_version": 4,
Remove storage version

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +	t.RunSequentially("update blobber managing wallet should be able to update delegate wallet", func(t *test.SystemTest) {
Add cleanup : revert back the original delegate wallet

2024-10-14 17:51 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +	t.Run("Create allocation with storage version", func(t *test.SystemTest) {
Add negative tests

2024-10-14 17:55 UTC, Akhilesh53 commented on tests/api_tests/register_blobber_test.go
> +		apiClient.KillBlobber(t, scWallet, killBlobberReq, 1)
Added

2024-10-14 18:01 UTC, Akhilesh53 commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +			"storage_version": 4,
Storage version removed

2024-10-14 18:05 UTC, Akhilesh53 commented on tests/cli_tests/config/zbox_config.yaml
> +ethereum_node_url: "https://virtual.mainnet.rpc.tenderly.co/1b2b3323-9a80-49c3-a2ff-50efb7afb359"
Reverted

2024-10-14 18:05 UTC, Akhilesh53 commented on tests/cli_tests/config/config.yaml
> +ethereum_node_url: "https://virtual.mainnet.rpc.tenderly.co/1b2b3323-9a80-49c3-a2ff-50efb7afb359"
Reverted

2024-10-14 18:09 UTC, Akhilesh53 commented on tests/api_tests/update_blobber_test.go
> +		apiClient.UpdateBlobber(t, wallet, blobber, client.TxUnsuccessfulStatus)
Added get blobber to verify the version

2024-10-14 18:10 UTC, Akhilesh53 commented on tests/api_tests/update_blobber_test.go
> +		apiClient.UpdateBlobber(t, wallet, blobber, client.TxUnsuccessfulStatus)
Added get blopbber to verify the version

2024-10-14 18:12 UTC, Akhilesh53 commented on tests/api_tests/main_test.go
> +	walletIdx = int64(rand.Intn(len(initialisedWallets)))
Reverted create wallet

2024-12-18 09:44 UTC, closed without merging