system test for new transaction endpoint
0chain/system_test pull request #1118
Opened 2024-10-15 19:13 UTC by smaulik13

2024-10-16 13:20 UTC, Jayashsatolia403 requested changes

2024-10-16 13:20 UTC, Jayashsatolia403 commented on tests/api_tests/0box_transactions._test.go
> +	t.RunSequentiallyWithTimeout("get paginated transactions list while creating pit id", 5*time.Minute, func(t *test.SystemTest) {
Why 5 minutes timeout?

2024-10-16 13:20 UTC, Jayashsatolia403 commented on tests/api_tests/0box_transactions._test.go
> +		if txnData != nil {
We will always have transactions so txnData should never be nil. Return error if it is nil.

2024-10-16 13:20 UTC, Jayashsatolia403 commented on tests/api_tests/0box_transactions._test.go
> +			_, resp, err := zboxClient.GetTransactionsList(t, pitId)
Verify the data returned as well. You can request the same transactions from 0chain by hash and compare the content.

2024-10-16 14:20 UTC, smaulik13 commented on tests/api_tests/0box_transactions._test.go
> +	t.RunSequentiallyWithTimeout("get paginated transactions list while creating pit id", 5*time.Minute, func(t *test.SystemTest) {
As once pit id is created it is valid for 5 mins

2024-10-16 17:30 UTC, Jayashsatolia403 commented on tests/api_tests/0box_transactions._test.go
> +	t.RunSequentiallyWithTimeout("get paginated transactions list while creating pit id", 5*time.Minute, func(t *test.SystemTest) {
It's timeout for the test run. You need to know how much should it take to run.

2024-10-20 08:26 UTC, merged

2024-10-20 08:26 UTC, Jayashsatolia403 reviewed
lgtm