add zboxcli's available-after params in share file test
0chain/system_test pull request #122
Opened 2021-12-01 15:47 UTC by Rizary

Adding system_test for available-after in zboxcli (fix 0chain/blobber#439)

2021-12-01 23:46 UTC, stewartie4 requested changes
Thanks for the contribution, it's great to see new features being tested as they are written!
Some minor comments

Staging is broken right now so I ran tests manually using staging-556fedc2 image
![image](https://user-images.githubusercontent.com/18306778/144331829-ab735ff1-8ffa-445e-866e-7f32b0fe9093.png)

2021-12-01 23:46 UTC, stewartie4 commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.Run("Download file before available-after params should fail ", func(t *testing.T) {
Additional scenarios I think we need
download file during window should succeed 
download file after window should fail

2021-12-01 23:46 UTC, stewartie4 commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.Run("Share to public with available-after params should fail ", func(t *testing.T) {
what does share to public mean here?
is share to public a feature that needs tested?

2021-12-02 01:47 UTC, Rizary commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.Run("Share to public with available-after params should fail ", func(t *testing.T) {
it's when you didn't pass clientID, you can't use `available-after` params

2021-12-02 01:53 UTC, Rizary commented
> Thanks for the contribution, it's great to see new features being tested as they are written! Some minor comments
> 
> Staging is broken right now so I ran your new teat branch manually against the last working staging-556fedc2 image and your CLI feature branch ![image](https://user-images.githubusercontent.com/18306778/144334212-efda9f20-0b75-49fc-a45c-bb2c2651135f.png)
> 
> It looks like your CLI if failing to build however https://github.com/0chain/system_test/runs/4389003394?check_suite_focus=true

hi thanks. Hmm, strange, I try to build locally and didn't get the error. How do we debug on this? I mean we use different version of gosdk (it's based on my PR on gosdk).

Another one is, the blobber should be changed, but I couldn't find it in the docker hub? what should I do? Can we just refer it to the branch like the one we did on zboxcli?

2021-12-02 09:42 UTC, stewartie4 commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.Run("Share to public with available-after params should fail ", func(t *testing.T) {
Understood
what i mean is i didn't realise that it's possible NOT to pass client id - i thought it was mandatory 
wondering if we need tests for that feature in general

2021-12-02 09:44 UTC, stewartie4 commented
@Rizary you need to publish the blobber docker image for your branch manually 
https://github.com/0chain/blobber/actions/workflows/build-&-publish-docker-image.yml
then pass that image into system tests as above

2021-12-04 03:43 UTC, Rizary commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.Run("Share to public with available-after params should fail ", func(t *testing.T) {
I think we can add that test "not to pass client id".

2021-12-04 03:44 UTC, Rizary commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.Run("Download file before available-after params should fail ", func(t *testing.T) {
what do you mean by `during/after` window ?

2021-12-04 03:45 UTC, Rizary commented
> @Rizary you need to publish the blobber docker image for your branch manually https://github.com/0chain/blobber/actions/workflows/build-&-publish-docker-image.yml then pass that image into system tests as above

Noted. I thought with GitHub action, we already publish every image whenever we create PR or push commit in that PR. I'll try to add the image manually into Docker Hub.

2021-12-06 00:49 UTC, cnlangzi commented
> > @Rizary you need to publish the blobber docker image for your branch manually https://github.com/0chain/blobber/actions/workflows/build-&-publish-docker-image.yml then pass that image into system tests as above
> 
> Noted. I thought with GitHub action, we already publish every image whenever we create PR or push commit in that PR. I'll try to add the image manually into Docker Hub.

Yes. In blobber, docker image will be built and published with `staging:merge-[8-sha]` and `staging:merge`.  they can be used in system_test directly.

2021-12-06 00:51 UTC, Rizary commented
> > > @Rizary you need to publish the blobber docker image for your branch manually https://github.com/0chain/blobber/actions/workflows/build-&-publish-docker-image.yml then pass that image into system tests as above
> > 
> > 
> > Noted. I thought with GitHub action, we already publish every image whenever we create PR or push commit in that PR. I'll try to add the image manually into Docker Hub.
> 
> Yes. In blobber, docker image will be built and published with `staging:merge-[8-sha]` and `staging:merge`. they can be used in system_test directly.

Thank you for confirming. Yes, I have used the `merge-sha` image in here: https://github.com/0chain/system_test/runs/4422822989?check_suite_focus=true

There are other failing tests which is not related with the feature I add. So I'm still investigate it.

2021-12-06 11:30 UTC, stewartie4 commented
yeah there are lots of panics being thrown from the CLI
![image](https://user-images.githubusercontent.com/18306778/144838658-6af028b7-2e91-43ea-8f7b-a273a659149f.png)

2021-12-09 12:39 UTC, stewartie4 commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.Run("Download file before available-after params should fail ", func(t *testing.T) {
i mean the time window starting at the time of available after and ending at the time of expiry

2022-01-06 03:22 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/available-after-param  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-08 07:14 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/available-after-param  |
| 0box  | feature/available-after-param  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-08 07:31 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | pr-442-24b649ee  |
| 0box  | feature/available-after-param  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-17 00:12 UTC, stewartie4 commented
@Rizary what's the status of this PR?

2022-01-17 00:20 UTC, Rizary commented
I am still put it on hold due to another deadline. Will get back to it soon after I finish all of my task.

2022-01-21 15:38 UTC, stewartie4 commented
@princeparmar is your code being deployed to CI correctly? CI runs staging images unless you specify otherwise

2022-01-21 20:17 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/zboxcli-available-after  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/zboxcli-available-after  |
| authorizer  | staging  |
| 0box  | feature/zboxcli-available-after  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-14 09:18 UTC, Rizary commented
hi @stewartie4 , I'm working on it right now.

2022-03-02 03:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | staging  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | pr-442-76b882e5  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-02 04:45 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/available-after-param  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-24 03:41 UTC, cnlangzi commented
feature branch has been merged.

2022-03-24 03:41 UTC, closed without merging