[WIP] Vesting tests
0chain/system_test pull request #140
Opened 2021-12-21 21:37 UTC by Kishan-Dhakan

- Cases:

- vp-add:
  - Vesting pool with single destination, valid duration and valid tokens should work
  - Vesting pool with single destination and description should work
  - Vesting pool with multiple destinations should work
  - Vesting pool with multiple destinations and description should work
  - Vesting pool with locking insufficient tokens should fail
  - Vesting pool with excess locked tokens should work and allow unlocking
  - Vesting pool with start time in future should work
  - Vesting pool with start time in future for multiple destination wallets should work
  - Vesting pool with start time in past should fail
  - Vesting pool with start time in past for multiple destinations should fail
  - Vesting pool with invalid destination should fail
  - Vesting pool with one valid destination and one invalid destination should fail
  - Vesting pool for duration less than min duration should fail
  - Vesting pool with duration greater than max duration should fail
  - Vesting pool with lock less than min lock should fail
  - Vesting pool with description greater than max description length should fail

2021-12-26 11:37 UTC, stewartie4 commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev-3.devnet-0chain.net/dns
revert

2021-12-28 00:48 UTC, stewartie4 commented
Hey Kishan this looks very extensive, is this out of WIP? just thinking it can be reviewed after the holidays if so

2021-12-29 18:45 UTC, Kishan-Dhakan commented
> Hey Kishan this looks very extensive, is this out of WIP? just thinking it can be reviewed after the holidays if so

Hey, Happy Holidays Ryan🎉, hope you have a great one! Yeah I was adding token accounting to all commands, it's out of WIP now👍

2021-12-30 23:24 UTC, stewartie4 commented
seeing this flaky - seems like a rounding issue?
![image](https://user-images.githubusercontent.com/18306778/147794117-9e45efb9-912a-4ef1-91f0-0e124cc20f2e.png)
other than that lgtm!

2021-12-31 05:50 UTC, mohsenno1 requested changes
Great Coverage. Thank you.

2021-12-31 05:50 UTC, mohsenno1 commented on tests/cli_tests/zwalletcli_vesting_pool_token_test.go
> +		require.GreaterOrEqualf(t, actualVestedAmount, expectedVestedAmount,
This failed once on my local with this error: 
"0.283333" is not greater than or equal to "0.2833333333333333". 
I think this may cause the test to be flaky.

2021-12-31 13:17 UTC, Kishan-Dhakan commented
@stewartie4 @mohsenno1 I changed the case to round the amounts to 6 decimal places👍

2021-12-31 13:26 UTC, stewartie4 approved these changes
Thanks @Kishan-Dhakan, could you please let the blockchain guys know of your list of FIXME's and enhancements and also record them in https://github.com/0chain/system_test/projects/2 ? thanks

2022-01-01 09:28 UTC, merged