[WIP] - delete file tests
0chain/system_test pull request #142
Opened 2021-12-23 10:09 UTC by littlestar642

2021-12-26 21:00 UTC, stewartie4 commented
I know this is WIP but there is a lot of missing coverage - see the [issue](https://github.com/0chain/system_test/issues/130)

2022-01-06 14:25 UTC, Kishan-Dhakan requested changes

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +	require.Nil(t, err)
Could use os.TempDir() to avoid this extra step

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +		}), false)
Since error isn't expected here, keep retries on. (here + below cases)

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +		}), false)
Keep retries true

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +			"size": 10000,
setupAllocation uses 10000 by default, was this supposed to use something else?

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +
require.Equal() on output missing

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +
require.Equal() on output missing

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +
require.Equal() on output missing

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +		require.Len(t, output, 1)
require.Equal() on output missing

2022-01-06 14:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_delete_test.go
> +		require.Len(t, output, 1)
require.Equal() on output missing (here+below)

2022-01-06 14:34 UTC, Kishan-Dhakan commented
Additional case:

- Delete file in someone else's allocation

2022-01-06 20:59 UTC, stewartie4 commented
@littlestar642 all delete tests seem to be failing

2022-01-07 00:29 UTC, stewartie4 commented
some additional scenarios:
- delete shared file by the consumer of the shared file, not the owner
- delete file shared by auth ticket (owner and shared wallet)
- Delete empty directory vs delete directory with files in it

"delete existing directory should fail" - should it? I would expect this to work

2022-01-07 11:47 UTC, Kishan-Dhakan commented
> @littlestar642 good coverage, some additional scenarios:
> 
>     * delete shared file by the consumer of the shared file, not the owner
> 
>     * delete file shared by auth ticket (owner and shared wallet)
> 
>     * Delete empty directory vs delete directory with files in it
> 
> 
> "delete existing directory should fail" - should it? I would expect this to work

Nice catch Ryan! @littlestar642 Directories are delete-able just not the root directory itself. Your case can be converted to "deleting root directory should fail" and add another case for deleting normal directory.

However, I found something weird: directories created by the `createdir` command show an error on deletion. Directories created by uploading a file instead (say `./zbox upload --remotepath "/newDir/abc.txt` where newDir did not exist previously) show no error on deletion. @littlestar642 please check this out as part of your ticket, sync with me on slack if you need anthing

2022-01-07 18:05 UTC, littlestar642 commented on tests/cli_tests/zboxcli_file_delete_test.go
> +			"size": 10000,
I guess i missed that. will remove this. I just wanted a big enough space.

2022-01-07 18:12 UTC, littlestar642 commented
Hey folks @stewartie4 @Kishan-Dhakan 
> delete shared file by the consumer of the shared file, not the owner
I added the above test, but kept it under broken scenarios because well, it was broken. I will add the other cases.

2022-01-13 17:43 UTC, stewartie4 requested changes

2022-01-13 17:43 UTC, stewartie4 commented on tests/cli_tests/flaky___flaky_test.go
> +	t.Run("delete existing root directory should fail", func(t *testing.T) {
This isn't a flaky test @littlestar642 see https://0chain.slack.com/archives/G014PQ61WNT/p1641943895005500 - deleting the root directory should work
so we can update the assertions here and move this to regular test suite

2022-01-14 18:05 UTC, littlestar642 commented on tests/cli_tests/flaky___flaky_test.go
> +	t.Run("delete existing root directory should fail", func(t *testing.T) {
Hey, I tried with writing the tests for working delete root directory but they fail.

2022-01-14 23:01 UTC, merged