Merge branch 'master' into feature/zcnsc3
0chain/system_test pull request #158
Opened 2022-01-08 18:15 UTC by Dmdv

2022-01-09 21:52 UTC, stewartie4 commented
Hey @Dmdv - does this relate to https://github.com/0chain/system_test/pull/87 ?

2022-01-09 23:12 UTC, Dmdv commented
> Hey @Dmdv - does this relate to #87 ?

Hi @stewartie4 
I started working on the mentioned #87 before the final decision to move to cli tests and are based on the GoSDK rather than cli.

I will close #87 

This PR is the final PR

2022-01-09 23:44 UTC, stewartie4 commented
thanks @Dmdv 
great to know

2022-01-16 12:42 UTC, stewartie4 requested changes
minor tidy up + add negative scenarios

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_wzcn_test.go
> +	var zwallet = func(cmd, amount string) ([]string, error) {
can we follow the standard used in the other utility functions eg.
make a function called burnEth and add retry logic?
see https://github.com/0chain/system_test/blob/master/tests/cli_tests/zboxcli_file_copy_test.go#L634 for an example but pretty much every utility function follows this strategy

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_zcn_test.go
> +	var zwallet = func(cmd, amount string) ([]string, error) {
this duplication can be removed once a utility function is created

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_client_init_test.go
> +	return cliutils.RunCommandWithoutRetry(cmd)
any reason we can't retry this if it fails?

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_ethereum-account-list_test.go
> +	return cliutils.RunCommandWithoutRetry(cmd)
add retries?

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_ethereum-account-register_test.go
> +	return cliutils.RunCommandWithoutRetry(cmd)
add retries?

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_get_wzcn_burn_ticket_test.go
> +		output, err := zwallet(
create utility function

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_list_authorizers_test.go
> +		output, err := zwallet("bridge-list-auth")
create utility function

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_mint_wzcn_test.go
> +			"bridge-mint-wzcn",
create utility function

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_owner_init_test.go
> +	return cliutils.RunCommandWithoutRetry(cmd)
retry?

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_wzcn_test.go
> +package cli_tests
general comment:
Coverage is great but 12 new files seems a bit excessive - could you move all of these tests to a single token bridge file?

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_wzcn_test.go
> +func TestBridgeBurnWZCN(t *testing.T) {
add error scenarios: 
examples i could think of:
- no amount param
- no file param
- unsuccessful burn
- try to burn someone else's tokens
- try to burn more tokens than you have
- try to bun negative amount
- file doesn't exist 
etc.

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_zcn_test.go
> +package cli_tests
add negative scenarios (same as TestBridgeBurnWZCN)?

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_client_init_test.go
> +package cli_tests
negative tests (i don't know what this does so there may not be any)

2022-01-16 12:42 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_ethereum-account-list_test.go
> +package cli_tests
I can't find this command for negative scenarios - is it on a branch somewhere?

2022-01-16 12:43 UTC, stewartie4 commented
general comment: one of your tests is causing a panic - see the CI run

2022-01-16 18:24 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_burn_wzcn_test.go
> +	var zwallet = func(cmd, amount string) ([]string, error) {
@stewartie4 Ryan, 

I will add retries but I to my understanding this is required for tests. Tests are heavy, 1 transaction may involve submitting transaction to ETHEREUM then talks to authorizers, confirming and minting to ZCN.
This is not going to be a one `transaction`.

Imagine the client application which successfully burned WZCN tokens, reported the transaction hash but currently not able to gather all burn tickets from authorizers.
It can always delay the check and all related further actions afterwards to another time.

I suggest the structure attached to the bottom (see picture)

It has benefits compared to the existing one

1. zwallet it a functor which takes `t *testing.T` as a closure, so no need to pass it in each time
2. No need to invent each time a new name for functions for each tests, it will always be zwallet.
3. This way is more declarative, we can always look in the header to get the meaning of the given test:
```	
const (
		Help = "Burn WZCN tokens that will be minted on ZCN chain"
	)
```


<img width="957" alt="image" src="https://user-images.githubusercontent.com/805238/149672360-00598d4f-3fa0-4bc3-9eb1-da0f28f9ce6a.png">

2022-01-16 18:25 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_client_init_test.go
> +	return cliutils.RunCommandWithoutRetry(cmd)
https://github.com/0chain/system_test/pull/158#discussion_r785478389 @stewartie4

2022-01-16 18:26 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_ethereum-account-list_test.go
> +	return cliutils.RunCommandWithoutRetry(cmd)
yes, makes sense

2022-01-16 18:42 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_burn_zcn_test.go
> +	var zwallet = func(cmd, amount string) ([]string, error) {
@stewartie4 I left comment there.

Also, this way is more declarative, I can know how zwallet cli is called

<img width="357" alt="image" src="https://user-images.githubusercontent.com/805238/149673378-301bcc84-6394-4747-9081-5d5a4c1d25f7.png">

2022-01-16 19:11 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_burn_wzcn_test.go
> +package cli_tests
All other tests are also split by files, instead of placing all tests in one file I suggest placing similar tests in one file, that would be 4 files instead of 12 @stewartie4

2022-01-16 19:15 UTC, Dmdv commented
@stewartie4 In general, retries makes sense only in case transient error such as network failures in major case, as for the other such as a creation of config file doesn't make sense if it cannot make file then it won't make it after 3 tries

2022-01-16 21:08 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-16 22:15 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_burn_wzcn_test.go
> +func TestBridgeBurnWZCN(t *testing.T) {
Ok

2022-01-17 00:01 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_ethereum-account-list_test.go
> +package cli_tests
https://github.com/0chain/gosdk/pull/353

2022-01-17 00:15 UTC, stewartie4 commented
@Dmdv makes sense assuming those operations only write a file and don't make any network calls - let's add it for any commands that require chain/network access

2022-01-19 00:24 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_wzcn_test.go
> +package cli_tests
that sounds good to me

2022-01-19 00:27 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_zcn_test.go
> +	var zwallet = func(cmd, amount string) ([]string, error) {
I understand what you're getting at but it also makes it more difficult for other tests to run the same function and causes code duplication
I'd keep it consistent with the rest of the suite and create a utility function called burnEth or similar but if you have a strong opinion on it that's fine because it's a small point

2022-01-29 10:48 UTC, stewartie4 requested changes

2022-01-29 10:48 UTC, stewartie4 commented on tests/cli_tests/config/config.yaml
> +block_worker: https://dev.0chain.net/dns
please use remove this and instead use zbox_config.yaml as per the rest of the test suite

2022-02-02 06:18 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_list_authorizers_test.go
> +		t.Skip("Temporarily skipping due to deployment issue")
Since we are now deploying authorizer with chain, can these be unskipped?

2022-02-02 06:23 UTC, Kishan-Dhakan commented
Looks good to merge pending unresolved comments 👍 Please check the skipped tests once again to see if any of them can be unskipped now

2022-02-03 21:32 UTC, Dmdv commented on tests/cli_tests/config/config.yaml
> +block_worker: https://dev.0chain.net/dns
done

2022-02-03 21:43 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_list_authorizers_test.go
> +		t.Skip("Temporarily skipping due to deployment issue")
```
https://beta.0chain.net/miner01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712e0/getAuthorizerNodes
```
still empty in beta

2022-02-04 04:34 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-04 13:15 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-04 23:23 UTC, stewartie4 commented on tests/cli_tests/config/config.yaml
> +block_worker: https://dev.0chain.net/dns
This doesn't seem to be done as of the latest commit - this file still exists and the changes in this have not been applied to zbox_config.yaml

2022-02-05 08:08 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-05 23:23 UTC, merged