WIP Stake pool changes.
0chain/system_test pull request #162
Opened 2022-01-11 17:09 UTC by Sriep

This makes changes necessary for https://github.com/0chain/0chain/pull/854.

2022-01-25 14:33 UTC, Sriep commented
Green test run https://github.com/0chain/system_test/actions/runs/1745374265

2022-01-25 18:48 UTC, Sriep commented
https://github.com/0chain/system_test/actions/runs/1746786632 second green tests after some refactoring

2022-01-26 05:53 UTC, Kishan-Dhakan requested changes

2022-01-26 05:53 UTC, Kishan-Dhakan commented on internal/cli/model/model.go
>  	// time it can't be unstaked.
Can we update these comments to reflect the changes?

2022-01-26 05:53 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_common_user_functions_test.go
> -		}
I get it that this changed, but what happens now? Do the blobbers don't lock anything? If so, these 2 cases should be removed completely (as in that case they are only testing creating and updating allocation, something that is covered separately). If not, the new token accounting must be added so it can be tested.

2022-01-26 11:37 UTC, Sriep commented on tests/cli_tests/zboxcli_common_user_functions_test.go
> -		}
The information this test relied upon is no longer available. The test worked because the amount locked for an allocation was available from two sources and so could be compared. However, this redundancy is not scalable and has been removed. 

https://github.com/0chain/0chain/pull/854 replaced a slice that could easily be tens of thousands of entries long with a single summary statistic. This is all 0chain needs for its internal processing. 

If it turns out that users require the offer information it can be got from the event database. https://github.com/0chain/0chain/issues/814 I am not aware of such a requirement but we can add a new Event database table to cover it if necessary.

Also https://github.com/0chain/system_test/issues/172. Might be best done after https://github.com/0chain/0chain/pull/684, as I think we need some control over which blobbers are used for allocations.

2022-01-27 15:49 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_common_user_functions_test.go
> -		}
I see. [0chain/0chain#814](https://github.com/0chain/0chain/pull/854) mentions `TotalOffers`, can that be somehow used to test against this? If not, these two cases can be removed completely (and covered later when offer information is available again), as they don't check anything.

2022-01-27 16:27 UTC, Sriep commented on tests/cli_tests/zboxcli_common_user_functions_test.go
> -		}
Total offers is the total for the blobber, not the allocation. So to control this value you would need to take account of the blobbers being used in parallel tests.

2022-01-28 05:12 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_common_user_functions_test.go
> -		}
Okay, I will add a commit to remove these completely then 👍. Can you please edit [0chain/0chain#814](https://github.com/0chain/0chain/issues/814) to mention adding the necessary system_tests once stakePool table is available, so it doesn't get missed out? cc: @stewartie4 hope this is okay?

2022-01-28 06:46 UTC, Kishan-Dhakan approved these changes

2022-01-28 09:52 UTC, merged

2022-01-28 15:59 UTC, stewartie4 commented on tests/cli_tests/zboxcli_common_user_functions_test.go
> -		}
yes this is important coverage to have, we'll need to re-add tests once the new method is available

2022-01-28 23:19 UTC, stewartie4 commented
@Sriep these tests never passed before the PR was merged and are now failing on master - can they be reverted or can the required code be merged to staging please as this will break everyone