Fix public share issue
0chain/system_test pull request #185
Opened 2022-02-08 05:24 UTC by lpoli

This PR contains following changes regarding clit tests:
1. Revoke public authticket should fail to download file
2. Collaborator should not be able to share file.

2022-02-08 08:10 UTC, Kishan-Dhakan requested changes

2022-02-08 08:10 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_collaborator_system_test.go
> +		require.NotNil(t, err, "expected error when collaborator shares a file")
This is still getting an error which is causing test to fail

2022-02-08 08:10 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> -	// FIXME is auth ticket with no target wallet and expiration meant to be eternal and cannot be revoked?
If you're removing the FIXME, I suppose the case is the expected behavior?

2022-02-08 17:39 UTC, lpoli commented on tests/cli_tests/zboxcli_share_file_test.go
> -	// FIXME is auth ticket with no target wallet and expiration meant to be eternal and cannot be revoked?
Revoke on public share is possible now

2022-02-08 18:32 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/public-share-issue  |
| gosdk  | fix/public-share-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-22 06:35 UTC, Kishan-Dhakan commented
Closing this, as the changes in this PR have already been merged to master via #192 and #189.

cc @stewartie4 @lpoli

2022-02-22 06:35 UTC, closed without merging