Update global config
0chain/system_test pull request #188
Opened 2022-02-09 08:33 UTC by mohsenno1

2022-02-09 19:54 UTC, stewartie4 commented
seeing some flaky tests already:
![image](https://user-images.githubusercontent.com/18306778/153279597-5f79d1db-5900-4019-b522-17fee450b7fd.png)
![image](https://user-images.githubusercontent.com/18306778/153279640-d270fca1-c394-4979-9166-57b3668a79f3.png)
![image](https://user-images.githubusercontent.com/18306778/153279682-b7357a7b-da87-4b3a-bcab-fb5b2a71ed42.png)

2022-02-10 13:47 UTC, cnlangzi requested changes

2022-02-10 13:47 UTC, cnlangzi commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev.0chain.net//dns
it should be `block_worker: https://dev.0chain.net/dns`

2022-02-10 13:47 UTC, cnlangzi commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev.0chain.net//dns
```suggestion
block_worker: https://dev.0chain.net/dns
```

2022-02-10 13:52 UTC, cnlangzi approved these changes

2022-02-11 00:00 UTC, stewartie4 approved these changes

2022-02-11 00:02 UTC, merged