Modify/download test
0chain/system_test pull request #189
Opened 2022-02-09 15:43 UTC by lpoli

Modify cli tests for file sharing as per changes in https://github.com/0chain/blobber/pull/526

2022-02-09 16:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/public-share-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | optimize/download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-09 19:18 UTC, stewartie4 commented on tests/cli_tests/zboxcli_collaborator_system_test.go
> -	t.Run("Remove Collaborator _ collaborator must no longer be able to share the file", func(t *testing.T) {
Instead of removing this test case completely i'd update it to be 
Remove Collaborator _ collaborator must no longer be able to **read** the file

2022-02-10 01:19 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | fix/public-share-issue  |
| zboxcli  | fix/public-share-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-10 07:55 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/public-share-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | optimize/download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-10 08:48 UTC, lpoli commented on tests/cli_tests/zboxcli_collaborator_system_test.go
> -	t.Run("Remove Collaborator _ collaborator must no longer be able to share the file", func(t *testing.T) {
I removed it because collaborator is not permitted to share file anyway. Be him removed or not.

2022-02-10 10:17 UTC, Kishan-Dhakan requested changes
Linter is failing, LGTM otherwise since this is blocking other PRs.

2022-02-10 10:22 UTC, Kishan-Dhakan requested changes
Linter is failing, please do the needful

2022-02-10 10:22 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +		_, err = downloadFileForWallet(t, receiverWallet, configPath, downloadParams, false)
Why is there no assertion on output?

2022-02-10 10:22 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +		/* Authticket is redundant for owner and collaborator
Why is this simply commented out instead of removed?

2022-02-10 11:20 UTC, Kishan-Dhakan commented
Merging to unblock other PRs

2022-02-10 11:20 UTC, merged