Authorizer settings tests
0chain/system_test pull request #205
Opened 2022-02-27 23:35 UTC by Dmdv

https://github.com/0chain/system_test/issues/202

2022-03-01 20:52 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +		require.Greater(t, len(output), 0, strings.Join(output, "\n"))
i'd add an output contents assertion to all of these, right now we're just checking that something is returned but not what

2022-03-01 20:52 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +		if _, err := os.Stat("./config/" + zcnscOwner + "_wallet.json"); err != nil {
this could be placed at the start of the man function to avoid the duplication

2022-03-02 17:27 UTC, Kishan-Dhakan requested changes

2022-03-02 17:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_settings_authorizer_tests.go
> +package cli_tests
This file does not seem necessary right now

2022-03-02 17:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +		}()
This needs to be inside `TestZCNBridgeGlobalSettings` if it is to be run at the end of test. Otherwise you need to revert configs inside each case. I suggest the former

2022-03-02 17:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +		}()
Also it seems you are reverting `Faucet SC configs`, shouldn't this be reverting `ZCN Bridge Global SC config`?

2022-03-02 17:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +		t.Parallel()
Please remove t.Parallel() from tests using a common wallet (in this case zcnscowner wallet), it causes flakiness due to race conditions

2022-03-02 17:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +	t.Logf("Retrieving zcnc bridge global config...")
Minor: Use t.Log instead of t.Logf

2022-03-06 22:23 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +		}()
Fixed this. Faucet was an error. Removed already

2022-03-06 22:23 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +		t.Parallel()
done

2022-03-06 22:24 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +	t.Logf("Retrieving zcnc bridge global config...")
done

2022-03-06 22:25 UTC, Dmdv commented on tests/cli_tests/zwalletcli_zcnbridge_settings_global_test.go
> +	t.Logf("Updating zcnsc bridge global config...")
done

2022-03-06 22:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | authorizer_settings  |
| gosdk  | authorizer_settings  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | feature/authorizer_settings_881  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-07 00:42 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | authorizer_settings  |
| gosdk  | authorizer_settings  |
| zboxcli  | staging  |
| zwalletcli  | authorizer_settings  |
| 0chain  | feature/authorizer_settings_881  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-12 10:35 UTC, stewartie4 approved these changes

2022-03-12 11:55 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | authorizer_settings  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | authorizer_settings  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-13 00:34 UTC, merged