Change miner stake pool fields
0chain/system_test pull request #211
Opened 2022-03-14 11:23 UTC by Sriep

0chain: https://github.com/0chain/0chain/pull/1025
GoSDK: https://github.com/0chain/gosdk/pull/414/files
zwalletCLI: https://github.com/0chain/zwalletcli/pull/102

2022-03-14 13:27 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | mn-sps  |
| gosdk  | miner-rewards  |
| zboxcli  | collect_sc  |
| zwalletcli  | collect_rewards  |
| 0chain  | miner-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-21 12:16 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | mn-sps  |
| gosdk  | miner-rewards  |
| zboxcli  | collect_rewards  |
| zwalletcli  | collect_sc  |
| 0chain  | miner-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-01 19:44 UTC, Kishan-Dhakan requested changes

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_blobber_config_update_test.go
> +		require.InDelta(t, newReadPrice, intToZCN(finalBlobberInfo.Terms.Read_price), delta)
These tests have worked well so far without precision errors, and your changes seem unrelated to this. Any reason for adding these?

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_token_test.go
> +		t.Skip("made redundant by https://github.com/0chain/0chain/issues/1062")
In that case we should remove it entirely, else it will keep showing up in `Skipped tests` in the logs

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_token_test.go
> +		t.Skip("made redundant by https://github.com/0chain/0chain/issues/1062")
On second thoughts I see 1062 is not merged yet. So I'm a bit skeptic about skipping. If you're confident this doesn't break anything, we can skip it

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_rp_lock_unlock_test.go
> +		t.Skip("made redundant by https://github.com/0chain/0chain/issues/1062")
Same as above

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_miner_stake_test.go
> +		t.Skip("rewards not transferred to wallet until a collect reward transaction")
Can you just add a //TODO here to cover this case by adding a collect reward txn at the end? Don't wanna take up more of your time on this, I will have this done later in a ticket that will test `collect-reward`

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_miner_stake_test.go
> +		return 0
Is this semantically correct?

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_send_and_balance_test.go
> +	strBody = strBody
Redundant?

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_sharder_stake_test.go
> +		t.Skip("needs attention, works intermittently")
Please add a FIXME or move to flaky__flakyscenarios. Will need to be reworked later.

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_sharder_stake_test.go
> +		t.Skip("rewards not transferred to wallet until a collect reward transaction")
Needs a //TODO

2022-05-01 19:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_rename_test.go
> -	t.Parallel()
This is weird. If move, upload, download and copy work in parallel, this should too. I think if your run is passing then it means parallel can be added back here.

2022-05-02 05:15 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_rename_test.go
> -	t.Parallel()
Resolved

2022-05-13 02:51 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | mn-sps  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | collect_sc  |
| zwalletcli  | collect_rewards  |
| 0chain  | miner-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-13 05:58 UTC, Kishan-Dhakan approved these changes

2022-05-16 22:48 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | mn-sps  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | collect_sc  |
| zwalletcli  | collect_rewards  |
| 0chain  | miner-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-17 12:40 UTC, merged