fix(upload):break upload if any error is thrown from blobber
0chain/system_test pull request #213
Opened 2022-03-17 08:34 UTC by cnlangzi

## Fixes
- fixed: https://github.com/0chain/gosdk/issues/266
- fixed: https://github.com/0chain/zboxcli/issues/130

## Associated PRs (Link as appropriate):
- zboxcli: https://github.com/0chain/zboxcli/pull/193
- gosdk: https://github.com/0chain/gosdk/pull/417

2022-03-17 09:21 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/break_upload_on_error  |
| gosdk  | staging  |
| zboxcli  | fix/break_upload_on_error  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-18 03:19 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/break_upload_on_error  |
| gosdk  | fix/break_upload_on_error  |
| zboxcli  | fix/break_upload_on_error  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-18 12:46 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/break_upload_on_error  |
| gosdk  | fix/break_upload_on_error  |
| zboxcli  | fix/break_upload_on_error  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-19 11:11 UTC, Kishan-Dhakan requested changes
LGTM pending minor changes

2022-03-19 11:11 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_sync_test.go
> +	// })
These need to be uncommented before merge

2022-03-19 11:11 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_sync_test.go
> +		fmt.Println(strings.Join(output, ""))
Debug line needs to be removed

2022-03-19 12:25 UTC, Kishan-Dhakan approved these changes

2022-03-19 12:26 UTC, merged