fix(collaborator):fixed tests
0chain/system_test pull request #225
Opened 2022-03-30 06:52 UTC by cnlangzi

## Fixes
- fixed https://github.com/0chain/blobber/issues/573

## PRs
- blobber: https://github.com/0chain/blobber/pull/613

2022-03-30 07:39 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/collaborator_update  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/collaborator_update  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-30 10:02 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/collaborator_update  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/collaborator_update  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-30 10:27 UTC, Kishan-Dhakan requested changes

2022-03-30 10:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_collaborator_system_test.go
>  		}, false)
Please turn this to true as now it is not expected to fail

2022-03-30 22:59 UTC, cnlangzi commented on tests/cli_tests/zboxcli_collaborator_system_test.go
>  		}, false)
fixed

2022-03-31 00:25 UTC, peterlimg approved these changes
lgtm

2022-03-31 01:59 UTC, merged