fix(list):added test to list file on a new allocation
0chain/system_test pull request #226
Opened 2022-03-30 08:05 UTC by cnlangzi

## Changes
- added test to list file on a new allocation

## PRs
- https://github.com/0chain/blobber/pulls

2022-03-30 08:59 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/getobjecttree  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/getobjecttree  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-30 10:13 UTC, Kishan-Dhakan requested changes

2022-03-30 10:13 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_list_file_system_test.go
> +		err = json.NewDecoder(strings.NewReader(output[0])).Decode(&listResults)
Can this be replaced with Json.Unmarshal for consistency?

2022-03-30 10:52 UTC, peterlimg requested changes

2022-03-30 10:52 UTC, peterlimg commented on tests/cli_tests/zboxcli_list_file_system_test.go
> +		expectedTotalEntries := totalFolders + totalFiles
The totalFolders and totalFiles are all 0, basically we only need to assert the returned `listResults` is 0.

2022-03-30 16:13 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_list_file_system_test.go
> +		expectedTotalEntries := totalFolders + totalFiles
Agreed, @cnlangzi you can use `require.Empty()`

2022-03-30 23:04 UTC, cnlangzi commented on tests/cli_tests/zboxcli_list_file_system_test.go
> +		err = json.NewDecoder(strings.NewReader(output[0])).Decode(&listResults)
fixed

2022-03-30 23:04 UTC, cnlangzi commented on tests/cli_tests/zboxcli_list_file_system_test.go
> +		expectedTotalEntries := totalFolders + totalFiles
fixed

2022-03-31 00:23 UTC, peterlimg approved these changes
lgtm

2022-03-31 00:43 UTC, merged