fix(upload): removed chunksize
0chain/system_test pull request #235
Opened 2022-04-08 09:32 UTC by cnlangzi

### Changes
- removed chunksize : https://github.com/0chain/gosdk/issues/425

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- system_test:
- zboxcli:
- gosdk:

2022-04-08 09:49 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/hide_chunksize  |
| gosdk  | fix/hide_chunksize  |
| zboxcli  | fix/hide_chunksize  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-08 10:27 UTC, Kishan-Dhakan requested changes
LGTM 👍 
Minor query added.

2022-04-08 10:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_upload_test.go
> -	})
Is there a similar case possible for `chunkNumber`? Say `too small a chunkNumber` should fail?

2022-04-08 10:28 UTC, Kishan-Dhakan commented
Out of curiosity, what does chunkNumber do, is it documented somewhere? I don't think we've tested it before

2022-04-08 10:30 UTC, cnlangzi commented on tests/cli_tests/zboxcli_upload_test.go
> -	})
https://github.com/0chain/gosdk/issues/360

2022-04-08 10:36 UTC, cnlangzi commented on tests/cli_tests/zboxcli_upload_test.go
> -	})
https://github.com/0chain/zboxcli#upload

2022-04-08 18:36 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_upload_test.go
> -	})
We should add a `chunkNumber 0 or negative should fail` then?

2022-04-09 02:58 UTC, cnlangzi commented on tests/cli_tests/zboxcli_upload_test.go
> -	})
it is impossible to set it with 0 or negative . it will be ignore on WithChunkNumber
```
// WithLiveChunkNumber set the number of chunks should be upload in a request. ignore if size <=0
func WithLiveChunkNumber(num int) LiveUploadOption {
	return func(lu *LiveUpload) {
		if num > 0 {
			lu.chunkNumber = num
		}
	}
}
```

2022-04-09 04:59 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/hide_chunksize  |
| gosdk  | fix/hide_chunksize  |
| zboxcli  | fix/hide_chunksize  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-09 16:43 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_upload_test.go
> -	})
That's great, I just meant it should be covered too. Leave it with me.

2022-04-09 16:44 UTC, Kishan-Dhakan approved these changes
LGTM

2022-04-12 10:36 UTC, merged