- open challenge fixed
0chain/system_test pull request #260
Opened 2022-05-10 14:12 UTC by sum-it08

2022-05-10 16:00 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/chall_table  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | feat/chall_table  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-11 13:45 UTC, Kishan-Dhakan approved these changes
LGTM pending unskipping the challenge tests

2022-05-11 13:45 UTC, Kishan-Dhakan requested changes
https://github.com/0chain/system_test/blob/91b1454594623ac0aa1d105ed8e9868684eac825/tests/cli_tests/0_blobber_challenge_test.go#L23 This needs to be undone @sum-it08

2022-05-11 15:15 UTC, Kishan-Dhakan approved these changes

2022-05-11 16:53 UTC, Kishan-Dhakan approved these changes

2022-05-12 22:00 UTC, merged