Owner config
0chain/system_test pull request #264
Opened 2022-05-14 07:27 UTC by Kishan-Dhakan

- Owner config tests
Related PR: https://github.com/0chain/0chain/pull/1240

2022-05-14 09:01 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | ownerConfig  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | ownerConfig  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-14 10:20 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | ownerConfig  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | ownerConfig  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-20 00:42 UTC, cnlangzi approved these changes
LGTM

2022-05-20 09:41 UTC, dabasov requested changes

2022-05-20 09:41 UTC, dabasov commented on tests/cli_tests/0_owner_update_config_test.go
> +	t.Run("should allow update of owner: VestingSC", func(t *testing.T) {
most likely VestingSC will be removed

2022-05-20 09:41 UTC, dabasov commented on tests/cli_tests/0_owner_update_config_test.go
> +	t.Run("Should allow update owner: InterestSC", func(t *testing.T) {
interestSC will be removed soon

2022-05-20 09:41 UTC, dabasov commented on tests/cli_tests/0_owner_update_config_test.go
> +	t.Run("should allow update of owner: StorageSC", func(t *testing.T) {
we should request nonce once before the test started and then getANdIncrement it for every test

```go
//before the test
		ret, err := getNonceForWallet(t, configPath, scOwnerWallet, true)
		require.Nil(t, err, "error fetching minerNodeDelegate nonce")
		nonceStr := strings.Split(ret[0], ":")[1]
		nonce, err := strconv.ParseInt(strings.Trim(nonceStr, " "), 10, 64)
		require.Nil(t, err, "error converting nonce to in")
```
```go
// in each test
		n := atomic.AddInt64(&nonce, 1)
```

2022-05-20 09:41 UTC, dabasov commented on tests/cli_tests/0_owner_update_config_test.go
> +		ret, err := getNonceForWallet(t, configPath, scOwnerWallet, true)
no need to get nonce since it is not shared between parallel tests.

2022-05-20 09:41 UTC, dabasov commented on tests/cli_tests/0_owner_update_config_test.go
> +		n := atomic.AddInt64(&nonce, 1)
should increment by 2 since nonce is used twice in this test, so you need to get next and one more

2022-05-20 09:41 UTC, dabasov commented on tests/cli_tests/0_owner_update_config_test.go
> +		}, n+1, false)
nonce should be n here, since it is next

2022-05-20 09:41 UTC, dabasov commented on tests/cli_tests/0_owner_update_config_test.go
> +			}, n, true)
in clean up it should be n+1

2022-05-20 18:37 UTC, Kishan-Dhakan commented on tests/cli_tests/0_owner_update_config_test.go
> +	t.Run("Should allow update owner: InterestSC", func(t *testing.T) {
Skipped this 👍

2022-05-20 18:39 UTC, Kishan-Dhakan commented on tests/cli_tests/0_owner_update_config_test.go
> +	t.Run("should allow update of owner: StorageSC", func(t *testing.T) {
These are not run in parallel so is it still necessary to get nonce?

2022-05-20 18:39 UTC, Kishan-Dhakan commented on tests/cli_tests/0_owner_update_config_test.go
> +	t.Run("should allow update of owner: VestingSC", func(t *testing.T) {
We can skip/remove this test once it is final

2022-05-20 18:41 UTC, Kishan-Dhakan commented on tests/cli_tests/0_owner_update_config_test.go
> +		ret, err := getNonceForWallet(t, configPath, scOwnerWallet, true)
True but the function `updateVestingPoolSCConfig` used elsewhere has a nonce param. I could define a new function but felt unnecessary. Should I do that?

2022-05-20 18:47 UTC, Kishan-Dhakan commented on tests/cli_tests/0_owner_update_config_test.go
> +		n := atomic.AddInt64(&nonce, 1)
Got it, updated n := nonce + 2, and used n-2, n-1 and n in order of execution

2022-05-20 18:47 UTC, Kishan-Dhakan commented on tests/cli_tests/0_owner_update_config_test.go
> +		}, n+1, false)
Resolved

2022-05-20 18:47 UTC, Kishan-Dhakan commented on tests/cli_tests/0_owner_update_config_test.go
> +			}, n, true)
Resolved

2022-05-21 09:52 UTC, merged