System test fixes for new simplified read-pool
0chain/system_test pull request #277
Opened 2022-05-25 20:48 UTC by iamrz1

2022-05-25 21:16 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | user-read-pools  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | user-read-pools  |
| zwalletcli  | user-read-pools  |
| 0chain  | user-read-pools  |
| blobber  | user-read-pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-27 04:20 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | user-read-pools  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | user-read-pools  |
| zwalletcli  | staging  |
| 0chain  | user-read-pools  |
| blobber  | user-read-pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-27 23:44 UTC, stewartie4 requested changes
some minor comments/queries

2022-05-27 23:44 UTC, stewartie4 commented on tests/cli_tests/flaky___broken_scenarios_test.go
> +		output, err = readPoolLock(t, configPath, "--tokens 0.4", true)
The createParams logic above is consistent with the rest of the test codebase, why has it been removed in favour of literal strings?

2022-05-27 23:44 UTC, stewartie4 commented on tests/cli_tests/miner_fees_payment_test.go
> +		//allocationId := setupAllocation(t, configPath)
uncomment

2022-05-27 23:44 UTC, stewartie4 commented on tests/cli_tests/zboxcli_download_token_test.go
> -	balance := 0.4 // 400.000 mZCN
are these scenarios no longer valid?

2022-05-27 23:44 UTC, stewartie4 commented on tests/cli_tests/zboxcli_download_token_test.go
>  		// Read pool before download
these assertions seem useful to keep?

2022-06-01 01:21 UTC, iamrz1 commented on tests/cli_tests/flaky___broken_scenarios_test.go
> +		output, err = readPoolLock(t, configPath, "--tokens 0.4", true)
according to my testing, boolean flag doesn't work with parameter map, and read pool lock command has boolean flag. hence all the call to lock read-pool has been changed to look similar in case we need to use the parameter more in the future.

2022-06-01 01:23 UTC, iamrz1 commented on tests/cli_tests/miner_fees_payment_test.go
> +		//allocationId := setupAllocation(t, configPath)
we don't need allocation id for read pool lock/unlock anymore, will remove this line.

2022-06-01 01:30 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | user-read-pools  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | user-read-pools  |
| zwalletcli  | staging  |
| 0chain  | user-read-pools  |
| blobber  | user-read-pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-06-01 01:31 UTC, iamrz1 commented on tests/cli_tests/zboxcli_download_token_test.go
> -	balance := 0.4 // 400.000 mZCN
read pool lock has been decoupled from allocation-pool, so the first test is no longer valid.
The second test might be salvageable, but I recall a similar calculation in another test (cost from blobbers = spent from read pool)

2022-06-01 01:32 UTC, iamrz1 commented on tests/cli_tests/zboxcli_download_token_test.go
>  		// Read pool before download
Not relevant anymore

2022-06-01 11:27 UTC, stewartie4 commented on tests/cli_tests/flaky___broken_scenarios_test.go
> +		output, err = readPoolLock(t, configPath, "--tokens 0.4", true)
you can pass through a boolean with 
output, err = readPoolLock(t, configPath, createParams(map[string]interface{}{
			"booleanName": "",
		}), true)
or
output, err = readPoolLock(t, configPath, createParams(map[string]interface{}{
			"booleanName": "true",
		}), true)

2022-06-01 11:28 UTC, stewartie4 commented on tests/cli_tests/flaky___broken_scenarios_test.go
> +		output, err = readPoolLock(t, configPath, "--tokens 0.4", true)
see how we do it for the commit flag for example 
https://github.com/0chain/system_test/pull/282/files#diff-b64b1f0b1e26c3819b06b4df6e3961b113082b9e744f7b4ea499371cf8459c89R60

2022-06-02 06:50 UTC, iamrz1 commented on tests/cli_tests/flaky___broken_scenarios_test.go
> +		output, err = readPoolLock(t, configPath, "--tokens 0.4", true)
this would work with bool values that assume the default value to be false. I have added a fix in createParam that would work with boolean values directly, so we don't have to use blank string for false values. PTAL.

2022-06-03 00:27 UTC, stewartie4 commented on tests/cli_tests/flaky___broken_scenarios_test.go
> +		output, err = readPoolLock(t, configPath, "--tokens 0.4", true)
Thanks, much tidier

2022-06-03 00:28 UTC, stewartie4 approved these changes

2022-06-06 18:40 UTC, merged