Token rounding
0chain/system_test pull request #292
Opened 2022-06-08 17:59 UTC by Kishan-Dhakan

2022-06-11 12:50 UTC, sum-it08 requested changes

2022-06-11 12:50 UTC, sum-it08 commented on tests/cli_tests/block_rewards_test.go
> +		require.Equalf(t, minTotalRewardsAndFees, rewardEarned, "total share difference %d is not within range %d", rewardEarned, delta)
remove delta

2022-06-11 12:50 UTC, sum-it08 commented on tests/cli_tests/block_rewards_test.go
> +		require.Equalf(t, minTotalRewardsAndFees, rewardEarned, "total share difference %d is not within range %d", rewardEarned, delta)
I guess just require.Equal should be good. its self explanatory.. we can remove message

2022-06-11 12:50 UTC, sum-it08 commented on tests/cli_tests/block_rewards_test.go
> +		require.Equalf(t, minTotalRewardsAndFees, rewardEarned, "total share difference %d is not within range %d", rewardEarned, delta)
remove delta and having just require.Equal() should be good

2022-06-11 12:50 UTC, sum-it08 commented on tests/cli_tests/flaky___flaky_test.go
> +		require.Equal(t, 0.5-actualExpectedUploadCostInZCN, intToZCN(initialWritePool[0].Balance), "Write pool Balance after upload expected to be [%v] but was [%v]", 0.5, intToZCN(initialWritePool[0].Bala
the equal statement and message are not aligning
in equal you're checking 0.5-actualExpectedUploadCostInZCN and in message its just 0.5

2022-06-13 23:16 UTC, stewartie4 approved these changes

2022-06-17 22:58 UTC, merged