WIP add test for open challenges api decode response
0chain/system_test pull request #304
Opened 2022-06-17 08:48 UTC by Shrhawk

Issue https://github.com/0chain/system_test/issues/247

2022-06-17 14:08 UTC, Kishan-Dhakan requested changes

2022-06-17 14:08 UTC, Kishan-Dhakan commented on internal/api/util/zerochain.go
> -	"github.com/go-resty/resty/v2" //nolint
Removing this is causing errors:
![image](https://user-images.githubusercontent.com/42718091/174314691-347bb082-0753-4e74-9b18-62552a738998.png)

2022-06-20 08:42 UTC, Kishan-Dhakan approved these changes

2022-06-23 23:19 UTC, stewartie4 requested changes

2022-06-24 10:41 UTC, Shrhawk commented on internal/api/util/zerochain.go
> +func (z *Zerochain) GetOpenChallenges(t *testing.T, storageSmartContractAddress string, blobberId string) (*resty.Response, error) { //nolint
@stewartie4 review the changes again please

2022-06-27 11:17 UTC, Kishan-Dhakan approved these changes

2022-06-27 12:24 UTC, merged