Challenge logic to check ids
0chain/system_test pull request #319
Opened 2022-06-30 19:48 UTC by Kishan-Dhakan

2022-06-30 19:55 UTC, sum-it08 requested changes

2022-06-30 19:55 UTC, sum-it08 commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev-5.devnet-0chain.net/dns
do we need to revert it?

2022-07-01 16:19 UTC, dabasov approved these changes
lgtm

2022-07-02 13:11 UTC, sum-it08 approved these changes
lgtm

2022-07-02 13:28 UTC, merged