Modify/datetime
0chain/system_test pull request #330
Opened 2022-07-14 17:37 UTC by lpoli

Modify system tests w.r.t. changes in PR https://github.com/0chain/blobber/pull/748.

2022-07-15 09:22 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/datetime  |
| gosdk  | modify/datetime  |
| zboxcli  | modify/datetime  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/datetime  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-15 12:40 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/datetime  |
| gosdk  | modify/datetime  |
| zboxcli  | modify/datetime  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/datetime  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-15 15:19 UTC, lpoli commented on tests/cli_tests/zboxcli_create_dir_test.go
> +		require.Contains(t, aggregatedOutput, "consensus failed")
Actually I thought about it. But you know, when blobbers are rejecting commit request, it means consensus is not met.
If an allocation would have 128 blobbers, then there will be 128 messages. Gosdk can't figure out which error to consider for.

Maybe we could collect common messages among blobbers and return to the user with large count.
Previous directory creation process was incomplete.

2022-07-17 14:02 UTC, stewartie4 commented on tests/cli_tests/zboxcli_create_dir_test.go
> +		require.Contains(t, aggregatedOutput, "consensus failed")
"when blobbers are rejecting commit request, it means consensus is not met."
based on this, let's translate the error message to "directory creation failed" - something a bit more meaningful to the end user

2022-07-17 22:39 UTC, stewartie4 requested changes
agree with Kishan - a better error message is needed, even if it is just create failed

2022-07-21 15:03 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_create_dir_test.go
> +		require.Contains(t, aggregatedOutput, `consensus not met`)
Same as above

2022-07-28 05:02 UTC, merged