Free allocation tests
0chain/system_test pull request #334
Opened 2022-07-18 19:49 UTC by Kishan-Dhakan

2022-07-19 22:08 UTC, stewartie4 commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev-2.devnet-0chain.net/dns
minor: revert

2022-07-31 22:50 UTC, stewartie4 reviewed
what's the status of this PR @Kishan-Dhakan ?

2022-08-16 22:50 UTC, stewartie4 commented on tests/cli_tests/zboxcli_create_allocation_free_storage_test.go
> +		// register recipient wallet
can these tests run in parallel? if not we should probably prepend a zero to the test file to ensure they run at the beginning with the other sequential tests

2022-08-16 22:50 UTC, stewartie4 requested changes
LGTM other than comment re: parallel tests

2022-08-18 17:20 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_create_allocation_free_storage_test.go
> +		// register recipient wallet
@stewartie4 the internal tests can't be run in parallel as they show flakiness, but the entire can be run along with other files. There's a top level t.Parallel() for that.

2022-08-18 17:58 UTC, stewartie4 approved these changes

2022-08-22 20:35 UTC, merged