Feature/recent refs
0chain/system_test pull request #369
Opened 2022-08-09 13:28 UTC by lpoli

This PR contains test for feature that lists recently added refs.

2022-08-09 23:09 UTC, stewartie4 requested changes
minor comments, thanks for the PR

2022-08-09 23:09 UTC, stewartie4 commented on tests/cli_tests/zboxcli_recent_refs_test.go
> +type SimilarField struct {
can we move these models out of the test file please?

2022-08-09 23:09 UTC, stewartie4 commented on internal/cli/util/utils.go
> +func GetSubPaths(p string) (paths []string, err error) {
handy

2022-08-09 23:09 UTC, stewartie4 commented on tests/cli_tests/zboxcli_recent_refs_test.go
> +		allocationID := setupAllocation(t, configPath, map[string]interface{}{
can these tests run in parallel?

2022-08-09 23:09 UTC, stewartie4 commented on tests/cli_tests/zboxcli_recent_refs_test.go
> +	t.Run("Invalid parameters should return error", func(t *testing.T) {
what about attempting to list someone else's allocation? or a ref that doesn't exist

2022-08-11 03:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/recent-refs  |
| gosdk  | feature/list-recent-files  |
| zboxcli  | feature/list-recent-files  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-08-12 22:33 UTC, stewartie4 commented on go.mod
> +	github.com/0chain/gosdk v1.8.5
was go mod tidy run necessary? I wonder how we didn't notice

2022-10-17 02:43 UTC, lpoli commented on tests/cli_tests/zboxcli_recent_refs_test.go
> +	t.Run("Invalid parameters should return error", func(t *testing.T) {
It is redundant to test for `refs that does not exist.`
We can add to test for some else's allocation recent file listing.

2022-10-21 10:48 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/recent-refs  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/limit-access-on-recent-refs  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-10-28 14:36 UTC, stewartie4 approved these changes

2022-10-29 09:18 UTC, merged