Improve blobber tests
0chain/system_test pull request #370
Opened 2022-08-09 21:01 UTC by Kishan-Dhakan

- Increase file size for large upload case to 1 GB
- Add rename root path coverage

2022-08-09 23:22 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_rename_test.go
> +	t.Run("rename file", func(t *testing.T) {
rename root path directory fail?

2022-08-09 23:23 UTC, stewartie4 requested changes
minor test rename needed if I'm right

2022-08-09 23:23 UTC, stewartie4 commented on tests/cli_tests/zboxcli_upload_test.go
> +		allocSize := int64(2 * GB)
does 2gb and 1gb give us anything that 500 and 100mb didn't?

2022-08-12 22:32 UTC, stewartie4 requested changes
Happy to make these changes @Kishan-Dhakan ?

2022-08-16 14:43 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_rename_test.go
> +	t.Run("rename file", func(t *testing.T) {
Missed that, Done

2022-08-16 14:46 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_upload_test.go
> +		allocSize := int64(2 * GB)
@lpoli suggested this would be a better benchmark. See: https://0chain.slack.com/archives/C03788G8N2D/p1660054501357799

2022-08-19 09:47 UTC, stewartie4 approved these changes

2022-08-22 19:46 UTC, merged