Pool info
0chain/system_test pull request #378
Opened 2022-08-22 20:14 UTC by Kishan-Dhakan

- Unskip and fix TestMinerSharderPoolInfo

Closes https://github.com/0chain/system_test/issues/361

2022-08-30 23:16 UTC, stewartie4 requested changes
Some minor questions

2022-08-30 23:16 UTC, stewartie4 commented on tests/cli_tests/main_test.go
> +	miner01ID   = "73ad5727612116c025bb4405bf3adb4a4a04867ae508c51cf885395bffc8a949"
why do we need to hardcode these ids? the tests should be able to run against any network and x number of miners/sharders

2022-08-30 23:16 UTC, stewartie4 commented
So so great to get these working!

2022-08-31 14:21 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_sharder_update_settings_test.go
> -		t.Parallel()
All these settings update tests use the same `delegate wallet`. If run in parallel, nonce will mismatch and cause flakiness. So I'm afraid these will have to be run sequentially.

2022-08-31 14:27 UTC, Kishan-Dhakan commented on tests/cli_tests/main_test.go
> +	miner01ID   = "73ad5727612116c025bb4405bf3adb4a4a04867ae508c51cf885395bffc8a949"
It's because we need to hardcode the delegate wallets. Earlier, the operational wallet (miner.ID == wallet.ClientID) was being used for this (because the operational wallet is the default delegate wallet), which meant we could get these dynamically from ls-miners. But the operational wallet is used for a lot of transactions (like payFees) in the background, so it causes nonce-mismatch, and also for security purposes we should not be keeping delegate and operational wallet to be the same. Since I have changed them, I need to hardcode these IDs against their respective wallets, there is no way to do this dynamically (which makes sense).

It might be worth noting that even earlier, we couldn't have run these against any network with X no. of M/S because we would still need to hardcode all their wallets as well.

2022-08-31 16:44 UTC, stewartie4 commented on tests/cli_tests/main_test.go
> +	miner01ID   = "73ad5727612116c025bb4405bf3adb4a4a04867ae508c51cf885395bffc8a949"
hmmmm ok, can we pass these ids through as run params rather than hardcoding? 
Then if they're not passed in, these tests can be skipped 
It's just as it is now these tests will run and fail against every network other than dev-x

2022-09-04 00:18 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | poolInfo  |
| gosdk  | fix/cornerCaseConsensus  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-04 01:13 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | poolInfo  |
| gosdk  | fix/cornerCaseConsensus  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-04 16:11 UTC, merged