Feat: Added concurrent download test.
0chain/system_test pull request #383
Opened 2022-08-26 01:58 UTC by nlok5923

2022-08-27 15:10 UTC, Kishan-Dhakan requested changes

2022-08-27 15:10 UTC, Kishan-Dhakan commented on tests/cli_tests/dir2/THvtnR0dTl_test.txt
> +)�";���C��E�Z�B�t�K���q?��-|����B$��������C#����}��)3?�;�o[:��t6lG�:}����s�Y�O�zLr��9�XI�}�W"�qz(�&o�dy������K79p^��oA%��s����-��xfg��6�O$��߆k�V�g�aE���>��:
Why is this file committed?

2022-08-27 15:10 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_test.go
> +		filesize := int64(256)
IIRC file size was supposed to be 1 MB for better chances of lock_exists to pop up? Please check with @lpoli again and update if this if that's the case

2022-08-27 15:10 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_test.go
> +		require.Nil(t, err)
Assert nil for errors on both removals instead of only the second one.

2022-08-27 15:10 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_test.go
> +		}()
Can use a for loop with 1 goroutine and waitgroups for cleaner code

2022-08-28 03:40 UTC, nlok5923 commented on tests/cli_tests/dir2/THvtnR0dTl_test.txt
> +)�";���C��E�Z�B�t�K���q?��-|����B$��������C#����}��)3?�;�o[:��t6lG�:}����s�Y�O�zLr��9�XI�}�W"�qz(�&o�dy������K79p^��oA%��s����-��xfg��6�O$��߆k�V�g�aE���>��:
fixed in the latest commit

2022-08-28 03:40 UTC, nlok5923 commented on tests/cli_tests/zboxcli_download_test.go
> +		filesize := int64(256)
Fixed it. In the issue it is mentioned to use 1 MB file so fixed the changes accordingly.

2022-08-28 03:40 UTC, nlok5923 commented on tests/cli_tests/zboxcli_download_test.go
> +		require.Nil(t, err)
Addressed in latest commit.

2022-08-28 03:41 UTC, nlok5923 commented on tests/cli_tests/zboxcli_download_test.go
> +		}()
implemented in latest commit.

2022-08-28 03:44 UTC, nlok5923 commented
@Kishan-Dhakan Sir i did the changes but stuck with this [error](https://gist.github.com/nlok5923/a8a1a20a4bc8c3ab6313675e9fdc893a) can you please take a look and let me know where i am going wrong.

2022-08-29 02:53 UTC, nlok5923 commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev.0chain.net/dns
@Kishan-Dhakan while i was testing the test this `block_worker` don't seems to work so for now i changed it with another `block_worker` url please do let me know if i need to revert it.

2022-08-29 09:36 UTC, stewartie4 requested changes

2022-08-29 09:36 UTC, stewartie4 commented on tests/cli_tests/dir2/THvtnR0dTl_test.txt
> +)�";���C��E�Z�B�t�K���q?��-|����B$��������C#����}��)3?�;�o[:��t6lG�:}����s�Y�O�zLr��9�XI�}�W"�qz(�&o�dy������K79p^��oA%��s����-��xfg��6�O$��߆k�V�g�aE���>��:
we don't normally commit binary files to the repo, we instead generate them dynamically as the test runs
see how other tests do it

2022-08-29 09:48 UTC, nlok5923 commented on tests/cli_tests/dir2/THvtnR0dTl_test.txt
> +)�";���C��E�Z�B�t�K���q?��-|����B$��������C#����}��)3?�;�o[:��t6lG�:}����s�Y�O�zLr��9�XI�}�W"�qz(�&o�dy������K79p^��oA%��s����-��xfg��6�O$��߆k�V�g�aE���>��:
@stewartie4 i agree i had removed the binary files in the latest commit.

2022-08-29 19:22 UTC, Kishan-Dhakan commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev.0chain.net/dns
Yes Keep it dev for now.

2022-08-29 19:22 UTC, Kishan-Dhakan approved these changes

2022-08-30 00:09 UTC, merged

2022-08-30 00:09 UTC, stewartie4 reviewed
LGTM