Cancellation charge changes
0chain/system_test pull request #384
Opened 2022-08-26 15:48 UTC by Sriep

2022-08-26 16:27 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | cancellation_charge  |
| gosdk  | allocation_min_lock  |
| zboxcli  | allocation_min_lock  |
| zwalletcli  | staging  |
| 0chain  | cancellation_charge  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-08-27 10:01 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | cancellation_charge  |
| gosdk  | allocation_min_lock  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | cancellation_charge  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-08-27 10:43 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | cancellation_charge  |
| gosdk  | allocation_min_lock  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | cancellation_charge  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-07 19:58 UTC, dabasov requested changes

2022-09-07 19:58 UTC, dabasov commented on tests/api_tests/endpoints_test.go
> +	httpResponse, httpError := zeroChain.GetFromSharders(t, "/v1/screst/"+STORAGE_SMART_CONTRACT_ADDRESS+"/alloc-blobbers?allocation_data="+allocationData, &blobbers)
I haven't seen endpoint name change in 0chain

2022-09-07 20:01 UTC, dabasov commented on tests/api_tests/endpoints_test.go
> +	httpResponse, httpError := zeroChain.GetFromSharders(t, "/v1/screst/"+STORAGE_SMART_CONTRACT_ADDRESS+"/alloc-blobbers?allocation_data="+allocationData, &blobbers)
do not suggest to change name, as there are a lot of clients who use it and coordination of change an be painful

2022-09-15 12:08 UTC, Sriep commented
not needed

2022-09-15 12:08 UTC, closed without merging