blockRewardsPayment
0chain/system_test pull request #390
Opened 2022-09-01 14:38 UTC by Kishan-Dhakan

- Fixes block rewards test for miners.

2022-09-01 15:18 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blockRewardsPayment  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | nodestat_add_round  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-04 13:57 UTC, YarikRevich requested changes

2022-09-04 13:57 UTC, YarikRevich commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://dev-4.devnet-0chain.net/dns
Change "block_worker" back to "https://dev.0chain.net/dns"

2022-09-04 13:57 UTC, YarikRevich commented on internal/cli/model/model.go
> +	Round      int64 `json:"round"`
Perhaps, it will be better to create another model exatly for round tracking, like NodeWithRound, because not in all cases we need such field as "Round"

2022-09-06 17:08 UTC, Sriep commented on internal/cli/model/model.go
> +	Round      int64 `json:"round"`
Why? We could create a different versions of each object tailored for each test, but why make that effort?

2022-09-13 11:06 UTC, Kishan-Dhakan commented on tests/cli_tests/block_rewards_test.go
> +		fmt.Println("finished")
Can remove this

2022-09-13 11:06 UTC, Kishan-Dhakan commented on tests/cli_tests/block_rewards_test.go
> +		fmt.Println("start round", startRound, "end round", endRound)
Can remove Print code

2022-09-13 17:11 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blockRewardsPayment  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | nodestat_add_round  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-16 09:31 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blockRewardsPayment  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-17 23:01 UTC, stewartie4 reviewed
LGTM pending green build

2022-09-20 12:40 UTC, merged