Feature/wallet concurrency tests
0chain/system_test pull request #395
Opened 2022-09-03 19:11 UTC by YarikRevich

PR refers to issue #64

Added concurrent tests for all file requests

2022-09-04 17:07 UTC, Kishan-Dhakan requested changes
Minor comment: Great work otherwise.

2022-09-04 17:07 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_rename_test.go
> +			}(i)
This seems to do delete and rename twice. Would be better to upload two files, then `go func(){ rename }` and `go func() { delete }`.

2022-09-04 18:50 UTC, YarikRevich commented on tests/cli_tests/zboxcli_file_rename_test.go
> +			}(i)
You know, that there won't be any guarantee, that file will be renamed, so it won't be possible to test it correctly

2022-09-04 19:12 UTC, YarikRevich commented on tests/cli_tests/zboxcli_file_rename_test.go
> +			}(i)
The only way is to use mutex, but don't know, if it will make any difference

2022-09-05 14:08 UTC, Kishan-Dhakan requested changes

2022-09-05 14:08 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_rename_test.go
> +		wg.Wait()
What we're trying to test is that concurrent delete and rename operations work on the same `allocation`, not file. Can you please update the flow to:
- Upload two files
- go func() { rename file 1 }
- go func() { delete file 2 }

So it does not need to be on the same file as long as the it's the same allocation.

2022-09-05 16:26 UTC, YarikRevich commented on tests/cli_tests/zboxcli_file_rename_test.go
> +		wg.Wait()
Got it, fixed

2022-09-05 16:45 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_rename_test.go
>  		var destFileNames [2]string
Minor: Do we need to two for each?

2022-09-05 18:58 UTC, YarikRevich commented on tests/cli_tests/zboxcli_file_rename_test.go
>  		var destFileNames [2]string
Yes, we need

2022-09-05 18:59 UTC, merged