WIP: Feature/add blobber tests
0chain/system_test pull request #401
Opened 2022-09-06 16:13 UTC by YarikRevich

Refers to issue #252

2022-09-12 23:18 UTC, stewartie4 reviewed
This PR is massive - do you mind summarising the changes other than the obvious (renaming the module)

2022-09-13 11:44 UTC, YarikRevich commented
Add such changes:
- Add blobber tests
- Remove blobber tests
- Replace blobber tests

2022-09-13 15:28 UTC, Kishan-Dhakan requested changes
Great work! Left a few minor comments and some queries, along with some tests needing changes in the flow. Keep up the good work!

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/add_blobber_test.go
> +		require.Greater(t, numberOfBlobbersAfter, numberOfBlobbersBefore)
Can be made stronger using `require.Equal(t, numberOfBlobbersAfter, numberOfBlobbersBefore + 1)` or something similar.

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/add_blobber_test.go
> +	//}
Remove dead code

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/config/api_tests_config.yaml
> +network_entrypoint: https://bolt.devnet-0chain.net/dns/network
Revert to dev

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/endpoints_test.go
> +	httpResponse, httpError := zeroChain.GetFromSharders(t, filepath.Join("/v1/transaction/get/confirmation?hash="+hash), consensusCategoriser, &confirmation)
Why use filepath.Join() here (and below elsewhere)? If the purpose is to trim or clean the path, there are other methods.

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/execute_faucet_test.go
> +	//require.Equal(t, 1, confirmation.Transaction.TransactionStatus, "Confirmation suggests original transaction was unsuccessful. Transaction output: [%s]", confirmation.Transaction.TransactionOutput)
Uncomment this?

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/get_scstate_test.go
> +	t.Run("Get SCState of faucet SC, shouldn't work", func(t *testing.T) {
Needs a better description. What should fail?

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/replace_blobber_test.go
> +	})
For this to be tested, we should upload a file, then replace a blobber, and check if wee can still download it. Compare the file's content hash before and after to see if it matches.

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/api_tests/replace_blobber_test.go
> +}
This does not seem to be doing anything, can be removed. This can be approached as part of blobber rewards tests ticket.

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://bolt.devnet-0chain.net/dns
revert to dev

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/cli_tests/flaky___broken_scenarios_test.go
> +	t.Skip()
Why?

2022-09-13 15:28 UTC, Kishan-Dhakan commented on tests/cli_tests/flaky___flaky_test.go
> +	t.Skip()
Why?

2022-09-13 15:30 UTC, YarikRevich commented on internal/api/model/model.go
> +func (w *Wallet) MustConvertDateCreatedToInt() int {
Must is a special prefix used for those functions, which should process errors inside, not pushing them outside. It's a special pattern posted in golang blog

2022-09-13 15:31 UTC, YarikRevich commented on internal/api/util/config/config.go
> +func MustGetHomeDir() string {
Must is a special prefix used for those functions, which should process errors inside, not pushing them outside. It's a special pattern posted in golang blog

2022-09-13 15:32 UTC, YarikRevich commented on tests/api_tests/endpoints_test.go
> +	httpResponse, httpError := zeroChain.GetFromSharders(t, filepath.Join("/v1/transaction/get/confirmation?hash="+hash), consensusCategoriser, &confirmation)
In general I want to create URL builder, but I'll do that in refactoring PR

2022-09-13 15:32 UTC, YarikRevich commented on tests/api_tests/execute_faucet_test.go
> +	//require.Equal(t, 1, confirmation.Transaction.TransactionStatus, "Confirmation suggests original transaction was unsuccessful. Transaction output: [%s]", confirmation.Transaction.TransactionOutput)
Nah, forgot to remove

2022-09-13 15:34 UTC, YarikRevich commented on tests/api_tests/replace_blobber_test.go
> +}
No, it's useful, I'll add some other assertions, they should make this test case better

2022-09-13 15:34 UTC, Kishan-Dhakan commented
Also the suite seems to be panicking https://github.com/0chain/system_test/actions/runs/3044548718/jobs/4905060669#step:7:1577, please check.

2022-09-13 15:48 UTC, YarikRevich commented on tests/api_tests/get_scstate_test.go
> +	t.Run("Get SCState of faucet SC, shouldn't work", func(t *testing.T) {
There is another PR for that #402

2022-09-13 16:05 UTC, YarikRevich commented on tests/cli_tests/flaky___flaky_test.go
> +	t.Skip()
Never mind, it was there before my commit

2022-09-13 16:52 UTC, YarikRevich commented on tests/api_tests/replace_blobber_test.go
> +	})
I know about it, let me do that after some refactoring, because it will make code not as clean as I want

2022-09-15 14:32 UTC, Kishan-Dhakan approved these changes

2022-09-16 14:48 UTC, Kishan-Dhakan commented
![image](https://user-images.githubusercontent.com/42718091/190666957-0f7e415f-ca0d-4091-b34c-40a6930bfcf2.png)
@YarikRevich please check the failing test. Seems you have changed the amount to 0.2?

2022-09-16 22:24 UTC, merged

2022-09-16 22:49 UTC, stewartie4 reviewed
.