Fix: Skipped TestShareFile tests
0chain/system_test pull request #404
Opened 2022-09-11 04:15 UTC by nlok5923

Fixing the skipped TestShareFile test.

2022-09-16 12:24 UTC, Kishan-Dhakan requested changes

2022-09-16 12:24 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +		require.Equal(t, 0.4*1e10, float64(initialReadPool.Balance))
The readPool you are checking before and after downloading is of the owner. But the download is being done by `receiverWallet` here: `output, err = downloadFileForWallet(t, receiverWallet, configPath, downloadParams, false)`.

2022-09-18 04:16 UTC, nlok5923 commented on tests/cli_tests/zboxcli_share_file_test.go
> +		require.Equal(t, 0.4*1e10, float64(initialReadPool.Balance))
Fixed this in latest commit.

2022-10-10 04:08 UTC, nlok5923 commented
@Kishan-Dhakan the test are passing on test run here https://github.com/0chain/system_test/actions/runs/3216728675/jobs/5258912965 on https://github.com/0chain/0chain/pull/1721 pr but failing due authorizer crashing 
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/56120084/194798062-6a473cb1-1ecc-4756-be80-8faa89dc53b2.png">

2022-10-10 20:35 UTC, stewartie4 requested changes
Few questions, why are these being skipped? Can you update the t.skip reason? 
Also why remove the logging?

2022-10-11 03:13 UTC, nlok5923 commented
> Few questions, why are these being skipped? Can you update the t.skip reason? Also why remove the logging?

Hi @stewartie4 
> why are these being skipped? 

Actually the test are being skipped because on sharing file and downloading file by receiver the read pool balance is not affected although it incurred some download cost due to downloading.

> Can you update the t.skip reason?

As now the test i fixed i think we won't be keeping the `t.Skip` statement. so shall i still update the reason.

> Also why remove the logging?

I had added those statement just for debugging purpose.

2022-10-11 14:34 UTC, Kishan-Dhakan commented
Failing due to unrelated authorizer crashes, merging this.

2022-10-11 14:37 UTC, merged