Feature/ add repair allocation tests
0chain/system_test pull request #411
Opened 2022-09-15 11:05 UTC by Naman-1234

This pull request covers the issue https://github.com/0chain/system_test/issues/117.

2022-09-16 12:13 UTC, Kishan-Dhakan requested changes

2022-09-16 12:13 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		require.Len(t, output, 2)
This repeated

2022-09-16 12:13 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		output, err = deleteFile(t, walletOwner, params, false)
Calling delete will delete it from both blobbers.

2022-09-16 12:13 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		// Since there were 2 blobbers before, Now they should be 2
This comment does not seem related to the following code

2022-09-16 12:13 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		err = os.MkdirAll("tmp_repair", os.ModePerm)
Use os.Temp() for consistency

2022-09-16 12:13 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		require.Equal(t, fmt.Sprintf("%s deleted", filepath.Base(filename)), output[1])
It should be output[0]

2022-09-16 18:40 UTC, Naman-1234 commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		require.Len(t, output, 2)
Removed.

2022-09-16 18:40 UTC, Naman-1234 commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		output, err = deleteFile(t, walletOwner, params, false)
looking into this

2022-09-16 18:41 UTC, Naman-1234 commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		// Since there were 2 blobbers before, Now they should be 2
Removed it.

2022-09-16 18:43 UTC, Naman-1234 commented on tests/cli_tests/zboxcli_repair_file_test.go
> +		err = os.MkdirAll("tmp_repair", os.ModePerm)
Replaced it.

2022-10-08 20:02 UTC, closed without merging

2022-10-08 20:02 UTC, Naman-1234 commented
Closing this pull request and raised a new one #440