Draft: feature:create tests for blobber stake unstake
0chain/system_test pull request #414
Opened 2022-09-19 19:14 UTC by killbotXD

this PR fixes #172

2022-09-21 07:09 UTC, YarikRevich requested changes

2022-09-21 07:09 UTC, YarikRevich commented on tests/cli_tests/zboxcli_blobber_sp_lock_unlock_test.go
> +		require.Regexp(t, regexp.MustCompile(`Balance: 1000.00\d mZCN \(\d*\.?\d+ USD\)$`), output[0])
"output" contains JSON value, and it's unmarshaled already, so you don't need this regexp. Just check if "stakePool" struct has correct value

2022-09-21 07:09 UTC, YarikRevich commented on tests/cli_tests/zboxcli_blobber_sp_lock_unlock_test.go
> +		allocationID := strings.Fields(output[0])[4]
There are only 3 elements, so change index "4" to "2"

2022-09-21 07:09 UTC, YarikRevich commented on tests/cli_tests/zboxcli_blobber_sp_lock_unlock_test.go
> +		require.Regexp(t, regexp.MustCompile(`Balance: 200.00\d mZCN \(\d*\.?\d+ USD\)$`), output[0])
Change balance "200" to "400", because you have more tokens

2022-09-21 07:09 UTC, YarikRevich commented on tests/cli_tests/zboxcli_blobber_sp_lock_unlock_test.go
> +		require.Len(t, output, 1)
Returned output has more elements than "1"

2022-09-21 07:09 UTC, YarikRevich commented on tests/cli_tests/zboxcli_blobber_sp_lock_unlock_test.go
> +		stakePoolSecondID := strings.Fields(output[0])[4]
"output" contains JSON value

2022-09-21 12:48 UTC, Kishan-Dhakan requested changes
Good first contribution. Please fix the errors in the review comments and keep different cases as different sub-tests running parallely

2022-09-21 12:48 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_blobber_sp_lock_unlock_test.go
> +		require.Equal(t, err, "Error unstaking tokens from stake pool", strings.Join(output, "\n"))
All subtests should be independent of each other, please separate this into two subtests and run them parallely.

2022-09-23 17:54 UTC, killbotXD commented on tests/cli_tests/zboxcli_blobber_sp_lock_unlock_test.go
> +		// require.Nil(t, err, "Error getting wallet", strings.Join(output, "\n"))
removed

2022-10-06 19:11 UTC, killbotXD commented
> @killbotXD these tests are still failing.

I see @Kishan-Dhakan still fixing

2022-12-01 17:46 UTC, closed without merging