Feat: Adding test for blobbers: v1/file/refs end point
0chain/system_test pull request #422
Opened 2022-09-23 05:03 UTC by nlok5923

Pr under work

2022-09-23 21:05 UTC, Kishan-Dhakan requested changes

2022-09-23 21:05 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> +		url := "http://dev.0chain.net/blobber01"
dev isn't always online and we shouldn't be using dev.
Also before requesting the ref wouldn't you need to do upload unless i'm missing something silly?

2022-09-23 21:06 UTC, stewartie4 commented on tests/api_tests/get_blobberFileRef_test.go
> +		url := "http://dev.0chain.net/blobber01"
yes, please use the framework retrieve the blobber for you

2022-09-24 02:07 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> +		url := "http://dev.0chain.net/blobber01"
> 

Yes you are right @Kishan-Dhakan we need to upload a file first before requesting ref and i had just used `dev` for testing purpose will replace it.

2022-09-28 15:26 UTC, Kishan-Dhakan requested changes
@nlok5923 good work, please resolve the comments on priority.

2022-09-28 15:26 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> +}
Can we import these if we already have them somewhere please?

2022-09-28 15:26 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> +}
Why are we duplicating code? Can you please export these functions from their packages and import them here?

2022-09-28 15:26 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
>  		url := "http://dev.0chain.net/blobber01"
Please don't hardcode dev here

2022-09-28 15:32 UTC, Kishan-Dhakan commented
@nlok5923 it's okay to use the CLI, but you'll have to provide the binary to the runner first. See how it's done here https://github.com/0chain/actions/blob/35dc116018384882581373f87cab510aed988adb/run-system-tests/action.yml#L146.

2022-10-01 13:20 UTC, nlok5923 commented on tests/api_tests/endpoints_test.go
> +func v1BlobberGetFileRefs(t *testing.T, blobberGetFileRefsRequest model.BlobberGetFileRefsRequest) (*model.BlobberGetFileRefsResponse, *resty.Response, error) { //nolint
Will add in latest commit.

2022-10-01 13:35 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
>  		url := "http://dev.0chain.net/blobber01"
Yeah actually just for testing purpose i did hardcoded dev will remove it once test completes.

2022-10-02 14:55 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> +}
Hi @Kishan-Dhakan actually most of the function which i was using in this test has been removed from master and i think @YarikRevich is working on bringing upload functionality via gosdk in this [pr](https://github.com/0chain/system_test/pull/430) so i think i should wait for this #430 to get merged and then i would be using gosdk functions to implement this tests.

2022-10-02 20:10 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> +}
Why would need for that to get merged? You can just pull from his branch into yours locally. Also I remember okaying upload via CLI for now. Please use that instead if you're blocked.

2022-10-02 20:10 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
>  		url := "http://dev.0chain.net/blobber01"
Can you update this please?

2022-10-03 06:33 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> +}
@Kishan-Dhakan i thought that as the gosdk pr haven't merged yet so it might land up in few issues as the full review haven't completed but still i will proceed further with it. Also there's a lot incompaitibility in using cli based functions with api based function due to which i was stucked and i discussed the same with @YarikRevich yesterday that using gosdk functions should be preferable.

2022-10-05 13:00 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
>  		url := "http://dev.0chain.net/blobber01"
addressed it in the latest commit

2022-10-05 13:01 UTC, nlok5923 commented
> @nlok5923 it's okay to use the CLI, but you'll have to provide the binary to the runner first. See how it's done here https://github.com/0chain/actions/blob/35dc116018384882581373f87cab510aed988adb/run-system-tests/action.yml#L146.

I think we don't need this change now as now i am using gosdk for uploading file instead of cli

2022-10-05 20:36 UTC, Kishan-Dhakan requested changes

2022-10-05 20:36 UTC, Kishan-Dhakan commented on internal/api/util/client/api.go
> +	healthyBlobbers, err := c.getHealthyBlobbers(networkDNSResponse.Blobbers)
NetworkDNSResponse has no blobbers object.

2022-10-05 20:36 UTC, Kishan-Dhakan commented on internal/api/util/client/api.go
> +	// var scRestGetAllocationResponse *model.SCRestGetAllocationResponse
Remove dead code

2022-10-05 20:36 UTC, Kishan-Dhakan commented on internal/api/util/client/api.go
> +	resp, err := c.executeForAllServiceProviders(
Getting the ref from one blobber should be enough for testing

2022-10-05 20:36 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> +		apiClient.UpdateAllocationBlobbers(t, wallet, newBlobberID, "", allocationID, client.TxSuccessfulStatus)
Why are we adding blobber for this test? Use getUsedStorageNodeID instead of not used, and request only that blobber for ref

2022-10-05 20:36 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> +}
This should be available in the crypto package. Let's not duplicate it

2022-10-06 06:54 UTC, nlok5923 commented on internal/api/util/client/api.go
> +	healthyBlobbers, err := c.getHealthyBlobbers(networkDNSResponse.Blobbers)
Actually i had added blobbers object in it's schema as well.

2022-10-06 08:09 UTC, nlok5923 commented on internal/api/util/client/api.go
> +	healthyBlobbers, err := c.getHealthyBlobbers(networkDNSResponse.Blobbers)
Removed it at the latest commit.

2022-10-06 08:10 UTC, nlok5923 commented on internal/api/util/client/api.go
> +	// var scRestGetAllocationResponse *model.SCRestGetAllocationResponse
Removed dead code in latest commit

2022-10-06 08:10 UTC, nlok5923 commented on internal/api/util/client/api.go
> +	resp, err := c.executeForAllServiceProviders(
Implemented in the latest commit.

2022-10-06 08:11 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> +		apiClient.UpdateAllocationBlobbers(t, wallet, newBlobberID, "", allocationID, client.TxSuccessfulStatus)
Avoided using getNotUsedStorageNodeId function usage.

2022-10-07 06:55 UTC, nlok5923 commented
@Kishan-Dhakan the tests which i wrote are passing locally and CI status is fail because the older test are not updated shall i push the updated the older test as well ?

2022-10-07 15:04 UTC, Kishan-Dhakan requested changes
LGTM, minor changes needed. Nearly there

2022-10-07 15:04 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> +	t.Logf("get blobber file request object...")
Use t.Log() if you're not formatting the string with placeholders like %s or %v

2022-10-09 12:25 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> +		// request with refType as updated
Most prolly it return the ref for updated files.

2022-10-09 12:26 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> +	t.Logf("get blobber file request object...")
Sure will remove it as it is not needed in latest commit

2022-10-09 12:52 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> +
Fixed in latest commit

2022-10-09 12:52 UTC, nlok5923 commented on internal/api/util/client/sdk.go
> +func (c *SDKClient) UploadSomeFile(t *testing.T, allocationID string) string {
Fixed in latest commit.

2022-10-10 12:01 UTC, Kishan-Dhakan approved these changes

2022-10-11 14:39 UTC, merged