Hashnode endpoint API tests
0chain/system_test pull request #429
Opened 2022-09-28 15:50 UTC by Kishan-Dhakan

2022-09-29 22:28 UTC, stewartie4 commented on internal/api/util/crypto/bls.go
> +
Why do we need to pull all this crypto stuff in?
We haven't needed to thus far for BLS signing etc.

2022-09-29 22:30 UTC, stewartie4 requested changes
few small queries

2022-09-29 22:30 UTC, stewartie4 commented on tests/api_tests/blobber_hashnode_test.go
> +		getBlobberResponse, restyResponse, err := apiClient.V1BlobberGetHashNodeRoot(t, *blobberRequest, client.HttpOkStatus)
any assertions on the response body?

2022-09-29 22:30 UTC, stewartie4 commented on tests/api_tests/blobber_hashnode_test.go
> +	t.Run("Get hashnode root from blobber should work", func(t *testing.T) {
are there any failure test cases? missing required params not sent etc.?

2022-09-30 19:11 UTC, YarikRevich requested changes

2022-09-30 19:11 UTC, YarikRevich commented on internal/api/util/crypto/signature_scheme.go
> +}
There is a KeyPair structure in "internal/api/model" which has the same signature. Please use it.

2022-10-03 15:01 UTC, Kishan-Dhakan commented on internal/api/util/crypto/signature_scheme.go
> +}
This causes more trouble than it handles. Check out this comment: https://github.com/0chain/system_test/pull/430#issuecomment-1264722713

2022-10-03 15:03 UTC, Kishan-Dhakan commented on internal/api/util/crypto/ed255190chain.go
> +	// return privateKeyBytes, nil
Resolved

2022-10-03 15:14 UTC, Kishan-Dhakan commented on tests/api_tests/blobber_hashnode_test.go
> +			URL:             getBlobberURL(usedBlobberID, allocation.Blobbers),
Resolved

2022-10-03 15:16 UTC, Kishan-Dhakan commented on internal/api/util/client/api.go
> +	url := blobberGetHashnodeRequest.URL + "/" + strings.Replace(GetHashNodeRoot, ":allocation", blobberGetHashnodeRequest.AllocationID, 1)
URLBuilder class is not very intuitive or readable. It needs refactoring. I will try to incorporate this

2022-10-03 15:18 UTC, Kishan-Dhakan commented on internal/api/util/client/api.go
> +	}
I am planning to rename networkDNSResponse to something like networkServiceProviders. This way everything will be inside one structure and still make sense.

2022-10-03 17:37 UTC, Kishan-Dhakan commented on internal/api/model/api.go
> +	ActualFileSize int64  `gorm:"column:actual_file_size" json:"actual_file_size,omitempty"`
Resolved

2022-10-03 17:38 UTC, Kishan-Dhakan commented on internal/api/util/crypto/bls.go
> +
I tried using the sign function we had in place, but I kept getting `bad signature` errors from blobber side.

2022-10-03 19:23 UTC, Kishan-Dhakan commented on internal/api/util/client/api.go
> +		formattedURL := ""
Why declare the variable in global scope here?

2022-10-04 16:10 UTC, Kishan-Dhakan commented on tests/api_tests/blobber_hashnode_test.go
> +		getBlobberResponse, restyResponse, err := apiClient.V1BlobberGetHashNodeRoot(t, *blobberRequest, client.HttpOkStatus)
Added. Although this from an empty allocation so not much to assert on. Once we get upload API working I'll add another case, left a todo for now.

2022-10-04 16:10 UTC, Kishan-Dhakan commented on tests/api_tests/blobber_hashnode_test.go
> +	t.Run("Get hashnode root from blobber should work", func(t *testing.T) {
Added

2022-10-04 21:48 UTC, YarikRevich requested changes

2022-10-04 21:48 UTC, YarikRevich commented on internal/api/util/crypto/bls.go
> +
Yeah, I also tried to use such stuff from gosdk it seems, but it didn't work. It's too coupled and needs to be refactored to be reused

2022-10-04 21:48 UTC, YarikRevich commented on internal/api/util/client/api.go
> +	url := blobberGetHashnodeRequest.URL + "/" + strings.Replace(GetHashNodeRoot, ":allocation", blobberGetHashnodeRequest.AllocationID, 1)
It's created with a usage of "Fluent Interface" pattern, which is pretty useful, when we try to implement "builders", but I will try to make it better

2022-10-04 21:48 UTC, YarikRevich commented on internal/api/util/client/api.go
> +		formattedURL := ""
I don't mean global scope. Declaration of variables with "var" keyword is just more clean

2022-10-06 17:33 UTC, YarikRevich approved these changes

2022-10-06 18:25 UTC, Kishan-Dhakan commented
@stewartie4 the crypto package is required because transactions and hashes are signed differently, transactions are signed using the privatekey (which is what the SignTransaction is doing), but hashes are signed using the bls0chain scheme. So we need those packages.

2022-10-07 07:53 UTC, stewartie4 approved these changes
LGTM

2022-10-07 14:57 UTC, merged