Feature/get new blobber rewards tests
0chain/system_test pull request #430
Opened 2022-09-29 15:38 UTC by YarikRevich

Refers to issue #406

2022-09-29 15:40 UTC, YarikRevich commented
@Kishan-Dhakan I know, that you suggested to use "cli" file uploading logic, but take a look at my implementation of the test. It seems to me that until utils for upload API tests are ready, gosdk can be used. It works fine.

2022-10-02 20:04 UTC, Kishan-Dhakan requested changes

2022-10-02 20:04 UTC, Kishan-Dhakan commented on internal/api/util/client/api.go
> +////Uploads a new file to blobber
Please remove the dead code

2022-10-02 20:04 UTC, Kishan-Dhakan commented on internal/api/util/client/sdk.go
> +	err = sdkAllocation.CommitMetaTransaction(filepath.Join("/", filepath.Base(tmpFile.Name())), "Upload", "", "", nil, new(model.StubStatusBar))
Commit meta txn has been removed now. Update your go.mod to use latest staging commit and refactor please.

2022-10-02 20:04 UTC, Kishan-Dhakan commented on tests/api_tests/get_new_blobber_rewards_test.go
> +	t.Run("Check if a new added blobber as additional parity shard to allocation can receive rewards, should work", func(t *testing.T) {
Please also add a case for existing blobber to receive rewards. And any other cases you might think of.

2022-10-02 20:04 UTC, Kishan-Dhakan commented on tests/api_tests/get_new_blobber_rewards_test.go
> +		require.Greater(t, rewards, int64(0))
We need stronger assertion that > 0. Can you check with @Sriep what is the calculation here and try to incorporate the token accounting?

2022-10-02 20:07 UTC, Kishan-Dhakan commented
@Yaroslav Svitlytskyi please resolve conflicts on https://github.com/0chain/system_test/pull/436. Check out https://github.com/0chain/system_test/pull/433 before resolving, and keep these changes, otherwise the crypto libs keep panicking. I'm okay with GoSDK usage for now, but much simpler to be honest to just call the existing upload from cli_tests package instead.

2022-10-03 10:48 UTC, YarikRevich commented on tests/api_tests/get_new_blobber_rewards_test.go
> +		require.Greater(t, rewards, int64(0))
It cannot be stronger, because there is no determined time for rewards receiving. It may take 2 minutes to receive the whole amount of rewards, but also can take up to 1 house, so it seems to me, that my current solution is probably the most accurate

2022-10-03 10:48 UTC, YarikRevich commented on tests/api_tests/get_new_blobber_rewards_test.go
> +	t.Run("Check if a new added blobber as additional parity shard to allocation can receive rewards, should work", func(t *testing.T) {
Added

2022-10-04 20:24 UTC, Kishan-Dhakan requested changes

2022-10-04 20:27 UTC, Kishan-Dhakan commented on tests/api_tests/get_new_blobber_rewards_test.go
> +		require.Greater(t, rewards, int64(0))
There must be something to equate the amount to. Check the stakePool of the blobber, it has a rewards field, after collecting rewards, wallet balance should increase by that.

If more nuanced token accounting cannot be done here, then ok, we need a different approach to test that.

2022-10-04 21:09 UTC, YarikRevich commented on tests/api_tests/get_new_blobber_rewards_test.go
> +		require.Greater(t, rewards, int64(0))
Yeah, added  the logic to check wallet balance after rewards collection. Sorry, missed it

2022-10-05 20:21 UTC, Kishan-Dhakan approved these changes

2022-10-07 13:08 UTC, merged

2022-10-09 22:39 UTC, stewartie4 commented on internal/api/util/crypto/crypto.go
> +func handlePanic() {
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:39 UTC, stewartie4 commented on tests/api_tests/add_blobber_test.go
> +		wallet := apiClient.RegisterWallet(t, "", "", nil, true, client.HttpOkStatus)
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:39 UTC, stewartie4 commented on internal/api/model/api.go
> +type ClientPutRequest struct {
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:39 UTC, stewartie4 commented on internal/api/util/client/api.go
> +	if clientPutRequest.GenerateInput {
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:39 UTC, stewartie4 commented on internal/api/util/client/api.go
> -		t,
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:39 UTC, stewartie4 commented on internal/api/util/client/api.go
> -			ClientKey:           wallet.PublicKey,
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:39 UTC, stewartie4 commented on internal/api/util/crypto/crypto.go
> -	t.Logf("Generated mnemonic [%s]", mnemonic)
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:39 UTC, stewartie4 commented on tests/api_tests/flaky___broken_scenarios_test.go
>  	t.Run("Register wallet API call should be successful, ignoring invalid creation date", func(t *testing.T) {
@YarikRevich Thanks for the contribution, but this PR has reverted many of the improvements I made as part of 
https://github.com/0chain/system_test/pull/433 
I am now going to have to re-apply these changes again, which is very time consuming and takes me away from other tasks.
Can we please be careful in future merges?
CC @Kishan-Dhakan

2022-10-09 22:47 UTC, stewartie4 commented on internal/api/util/client/api.go
> -	HttpBadRequestStatus = 400
same here

2022-10-10 22:49 UTC, YarikRevich commented
Sorry, it seems to me that @Kishan-Dhakan should have awared me about it

2022-10-11 13:28 UTC, Kishan-Dhakan commented
@YarikRevich I did mention keeping the changes of #433 in this [comment](https://github.com/0chain/system_test/pull/430#issuecomment-1264722713) already.