Feature/atlus total endpoints
0chain/system_test pull request #439
Opened 2022-10-08 08:45 UTC by YarikRevich

Refers to issue #417

2022-11-03 18:49 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/atlus_total_endpoints  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | feature/snapshots  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-16 09:44 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/atlus_total_endpoints  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | feature/snapshot-batch-update  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-31 12:18 UTC, devyetii commented on tests/api_tests/atlus_chimney_test.go
> +	t.RunWithTimeout("Check if a graph of total locked increases after write pool creation, should work", time.Minute*6, func(w *test.SystemTest) {
Duplicate of the one before

2023-02-11 22:40 UTC, stewartie4 reviewed
@YarikRevich what is the status of this PR
What's blocking it?

2023-02-12 15:04 UTC, Kishan-Dhakan commented
@stewartie4, now @devyetii is working on this PR.

2023-03-22 19:55 UTC, stewartie4 requested changes
closing in place of https://github.com/0chain/system_test/pull/593

2023-03-22 19:55 UTC, closed without merging