Fix API tests flakiness
0chain/system_test pull request #454
Opened 2022-10-14 16:19 UTC by Kishan-Dhakan

2022-10-14 17:03 UTC, nlok5923 commented on tests/api_tests/get_blobberFileRef_test.go
> -	t.Parallel()
Can't we still make this test run parallely along with making gosdk using one wallet at a time.

2022-10-14 17:05 UTC, YarikRevich requested changes

2022-10-14 17:05 UTC, YarikRevich commented on tests/api_tests/main_test.go
> +
I think this decesion to register a wallet only once for sdk client is a good way to go, but also it's better to make this "initialization" in a separate function. It's a minor change

2022-10-14 17:05 UTC, YarikRevich commented on tests/api_tests/get_blobber_rewards_test.go
> -	t.Parallel()
You can start using parallel execution of the tests, because you synchronized all actions in sdkClient.

2022-10-15 12:31 UTC, Kishan-Dhakan commented on internal/api/util/client/sdk.go
> +		_ = os.RemoveAll(name)
This wasn't being checked at all till now. It was just an empty if block. This is more of a lint fix than logic change.

2022-10-15 12:32 UTC, Kishan-Dhakan commented on tests/api_tests/main_test.go
> +
Okay, agreed. Will refactor

2022-10-15 15:32 UTC, YarikRevich commented on tests/api_tests/get_blobberFileRef_test.go
> -	t.Parallel()
I already left a comment on this. Yes, we can, cause @Kishan-Dhakan has fixed synchronization of actions for sdk client.

2022-10-15 15:33 UTC, YarikRevich approved these changes

2022-10-15 15:52 UTC, nlok5923 approved these changes

2022-10-16 14:12 UTC, stewartie4 requested changes
Look into multiple instantiation of the gosdk - if we can't do this then it is a serious deficiency in the gosdk itself - how do we ever expect anyone other than a hobbyist to use it?

2022-10-16 14:12 UTC, stewartie4 commented on internal/api/util/client/sdk.go
> +	defer c.Mutex.Unlock()
I hit these same issues and was investigating before I left.
Everything is 'static' (from a traditional language point of view) and global - we can use locks to kind of but not fully avoid the issues, but the underlying problem is still there.
Why can we not have multiple instances of this sdk client? 

For example even with locks, setWallet can still be called in one thread and upload can called in another, so you end up uploading using the incorrect wallet
Both calls will successfully establish a lock, but we still have state bleed between tests

2022-10-16 21:36 UTC, stewartie4 commented on tests/api_tests/main_test.go
> +
every test should have it's own independent setup eg. wallet and allocation, else this will cause issues with token accounting tests

2022-10-20 19:02 UTC, Kishan-Dhakan commented on tests/api_tests/get_blobberFileRef_test.go
> -	t.Parallel()
It causes nonce related errors in running them in parallel. So I'm keeping them sequential for now. Since we plan on removing gosdk dependency soon anyhow.

2022-11-08 19:57 UTC, Kishan-Dhakan commented
> Look into multiple instantiation of the gosdk - if we can't do this then it is a serious deficiency in the gosdk itself - how do we ever expect anyone other than a hobbyist to use it?
@stewartie4 Created an issue for it here: https://github.com/0chain/gosdk/issues/642, since we can only test code as it is for now, we should get these tests in before mainnet.

2022-11-09 15:52 UTC, stewartie4 commented
Agreed

2022-11-09 15:52 UTC, stewartie4 approved these changes

2022-11-09 16:53 UTC, merged