Fix: Fixing skipped test TestFileDownloadTokenMovement
0chain/system_test pull request #455
Opened 2022-10-16 04:23 UTC by nlok5923

PR under work

2022-10-18 06:06 UTC, nlok5923 commented
TestFileDownloadTokenMovement test are passing in CI
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/56120084/196348515-8d22eb5f-c8a4-47f5-be51-3f197bfbeeae.png">
But overall CI failing due to file test
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/56120084/196348669-11a2600a-d091-44a6-8bc5-3542f46ec521.png">

2022-10-19 13:29 UTC, Kishan-Dhakan requested changes
Minor, LGTM

2022-10-19 13:29 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_token_test.go
>  	t.Run("Each blobber's read pool balance should reduce by download cost", func(t *testing.T) {
Change the description to say "Downloader's readpool balance should reduce by download cost", current description applies to an older logic which is no longer applicable

2022-10-19 13:37 UTC, nlok5923 commented on tests/cli_tests/zboxcli_download_token_test.go
>  	t.Run("Each blobber's read pool balance should reduce by download cost", func(t *testing.T) {
Fixed at latest commit.

2022-10-19 14:00 UTC, Kishan-Dhakan approved these changes
LGTM

2022-10-19 14:47 UTC, nlok5923 commented
Download file token movement test are passing 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/56120084/196724557-5c2280f3-ccde-4098-baea-16fd089fcf4f.png">
But overall CI failing due to these tests which are unrelated to this pr 
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/56120084/196724748-6466daf1-aea5-4a70-940e-c421244eca08.png">

2022-10-19 16:48 UTC, merged