443 broken tests on staging
0chain/system_test pull request #462
Opened 2022-10-27 13:31 UTC by SinanEkm

All test cases are passing in my local so far. I also edited "Staking tokens against sharder should return intrests to wallet" case but, to be honest, I am not sure if it is the correct way of doing it or not so, I left the t.Skip() for now.

2022-11-01 13:27 UTC, Kishan-Dhakan requested changes

2022-11-01 13:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_sharder_stake_test.go
> +
Why is there a need to stake tokens on a blobber for this test? The test name says sharder stake

2022-11-01 13:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_mn_pool_info_test.go
> +	miners := getMinersListForWallet(t, miner01NodeDelegateWalletName)
Can you try using miner03NodeDelegateWalletName here instead of 01 and 02, seems they hit the max limit (20) in other tests

2022-11-01 20:20 UTC, stewartie4 reviewed
LGTM pending Kishan's comments

2022-11-02 00:47 UTC, stewartie4 approved these changes

2022-11-02 20:08 UTC, SinanEkm commented on tests/cli_tests/zwalletcli_sharder_stake_test.go
> +
Tbh, I have no idea. I just looked at similar test cases and tried something. But, as it turns out I was wrong. Deleted the lines I added and now it is passing the test.

2022-11-02 20:13 UTC, SinanEkm commented on tests/cli_tests/zwalletcli_mn_pool_info_test.go
> +	miners := getMinersListForWallet(t, miner01NodeDelegateWalletName)
Ok, I changed it to `miner03NodeDelegateWalletName`. But still, it is not passing all the tests every time. It sometimes passes and sometimes not passing.

2022-11-03 19:47 UTC, Kishan-Dhakan approved these changes
LGTM

2022-11-03 19:47 UTC, merged