Enhancement/verify download
0chain/system_test pull request #468
Opened 2022-11-10 15:48 UTC by lpoli

This PR contains the changes as per the changes in gosdk enhancement/verify-download branch

2022-11-12 02:41 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/verify-download  |
| gosdk  | enhancement/verify-download  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-14 03:51 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/verify-download  |
| gosdk  | enhancement/verify-download  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-14 05:05 UTC, peterlimg approved these changes

2022-11-14 05:06 UTC, peterlimg commented
@lpoli please fix the lint errors

2022-11-14 13:25 UTC, Kishan-Dhakan requested changes

2022-11-14 13:25 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +				finalReadPool.Balance >= int64(expectedRPBalance))
This seems like a regression. The cost shown by getDownloadCost should be as accurate as possible, which is, accounting for all blobbers instead of minimum. It should not assume some of the blobbers will be down. For UX purposes, the output can show something like "the actual cost might be lesser than the output, if your data is uploaded to lesser blobbers than expected." @stewartie4 thoughts?

2022-11-14 14:25 UTC, lpoli commented on tests/cli_tests/zboxcli_share_file_test.go
> +				finalReadPool.Balance >= int64(expectedRPBalance))
@Kishan-Dhakan Yes the cost is going to be in between values compared above.
`getDownloadCost` will calculate cost of downloading from 4 blobbers. The `enhancement/verify-download` gosdk PR uses as minimum blobber as possible. In our case, data is 2 and parity is 2. It is enough to download from 3 blobbers. The cost of 3 blobbers will be in between initial balance and expected final balance.

2022-11-14 14:27 UTC, Kishan-Dhakan approved these changes

2022-11-14 14:30 UTC, stewartie4 requested changes

2022-11-14 14:30 UTC, stewartie4 commented on tests/cli_tests/zboxcli_collaborator_system_test.go
> +		require.Contains(t, output[1], StatusCompletedCB)
In general, contains is a step down from regex - we are no longer verifying that the filename and type is correct
Any reason why?

2022-11-14 14:40 UTC, lpoli commented on tests/cli_tests/zboxcli_collaborator_system_test.go
> +		require.Contains(t, output[1], StatusCompletedCB)
@stewartie4 I think `Type` is flaky to compare. It is upto the client and server to agree on `content-type`.
For a successful download, we can simply check `Status completed` string. Filename is checked in line 693.

2022-11-14 18:54 UTC, stewartie4 commented on tests/cli_tests/zboxcli_collaborator_system_test.go
> +		require.Contains(t, output[1], StatusCompletedCB)
going to have to merge this as the code has been merged - not ideal

2022-11-14 18:54 UTC, stewartie4 approved these changes

2022-11-15 09:40 UTC, merged