Fix/zcn bridge burn tests
0chain/system_test pull request #481
Opened 2022-11-24 00:46 UTC by YarikRevich

2022-11-27 22:38 UTC, Kishan-Dhakan requested changes

2022-11-27 22:38 UTC, Kishan-Dhakan commented on tests/cli_tests/config/zbox_config.yaml
> +bridge_address: 0x0c2aa005C6FF9F4B46Ae566D9bc61E33B482D8E6
Please clean this

2022-11-27 22:38 UTC, Kishan-Dhakan commented on tests/cli_tests/logs/logs-2022-11-26T12-39-24.159.log
> +2022-11-26T12:38:37.894+0100	INFO	zcnbridge/authorizers_query.go:115	Got authorizers	{"amount": 3}
Please add *.log to .gitignore and update PR

2022-11-27 22:38 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> +		ethTxHash := allHashes[len(allHashes)-1]
Abstract this into some function so it is reusable. ExtractHashFromOutput or something

2022-11-27 22:38 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> -		require.Contains(t, output[len(output)-1], "Verification successful")
Assert on output too?

2022-11-30 19:48 UTC, YarikRevich commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> +		ethTxHash := allHashes[len(allHashes)-1]
It's not a correct way, because "bridge-get-zcn-burn" need hash without "0x" prefix, but "bridge-get-wzcn-burn" with it

2022-11-30 19:48 UTC, YarikRevich commented on tests/cli_tests/logs/logs-2022-11-26T12-39-24.159.log
> +2022-11-26T12:38:37.894+0100	INFO	zcnbridge/authorizers_query.go:115	Got authorizers	{"amount": 3}
Fixed

2022-11-30 19:48 UTC, YarikRevich commented on tests/cli_tests/config/zbox_config.yaml
> +bridge_address: 0x0c2aa005C6FF9F4B46Ae566D9bc61E33B482D8E6
Fixed

2022-12-01 22:33 UTC, stewartie4 commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
>  	t.Parallel()
Use test.SystemTest instead of testing.T

2022-12-01 22:36 UTC, stewartie4 requested changes
as comment

2022-12-08 20:40 UTC, stewartie4 approved these changes

2022-12-09 11:27 UTC, Kishan-Dhakan requested changes
Please make the above changes asap

2022-12-09 11:27 UTC, Kishan-Dhakan commented on tests/cli_tests/config/config.yaml
> +store_unlock_duration_sec: 2
Why a new file? Can this be merged with zbox_config.yaml or the other way round?

2022-12-09 11:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> +		ethTxHash := allHashes[len(allHashes)-1]
1. Why is that so? Is it well documented for end user? Could this be handled by the CLI?
2. If the above is not possible, pass the regex into the abstraction as a param.

2022-12-09 11:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> -		require.Contains(t, output[len(output)-1], "Verification successful")
Assert on output too

2022-12-09 11:27 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> +//nolint
These are now being used so remove //nolint (here+below)

2022-12-10 23:32 UTC, stewartie4 reviewed
Happy to approve again once @Kishan-Dhakan's comments are resolved 
When can we aim to merge this @YarikRevich ?

2022-12-13 18:29 UTC, YarikRevich commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> +		require.Contains(t, output[len(output)-1], "Transaction completed successfully:")
Added assertion

2022-12-13 20:15 UTC, Kishan-Dhakan approved these changes
LGTM

2022-12-13 20:19 UTC, merged