initial commit
0chain/system_test pull request #486
Opened 2022-11-29 19:57 UTC by SinanEkm

3 test cases are added.

2022-11-29 21:30 UTC, Kishan-Dhakan commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	fmt.Println(hash)
Remove log line

2022-11-29 21:42 UTC, Kishan-Dhakan commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	resp, err := http.Get("https://test.0chain.net/sharder01/v1/block/get/latest_finalized_magic_block")
Please replace this static URL and get it from Network service providers object

2022-11-29 21:56 UTC, SinanEkm commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	resp, err := http.Get("https://test.0chain.net/sharder01/v1/block/get/latest_finalized_magic_block")
Yes, I left this just temporarily for the PR.

2022-11-30 00:15 UTC, stewartie4 requested changes

2022-11-30 00:15 UTC, stewartie4 commented on internal/api/model/api.go
> +	LFMB *block.Block
This uses a model from gosdk - we should not do this as if gosdk changes the tests will still pass

2022-11-30 00:15 UTC, stewartie4 commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	hash, err := getCurrentHash(t)
These lines should be part of test setup

2022-11-30 00:15 UTC, stewartie4 commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	t.Run("Not modified, set node lfmb", func(t *testing.T) {
Can this test case description be clearer?
Given x, when y, then z
for example

2022-11-30 00:15 UTC, stewartie4 commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +		require.Equal(t, resp.RawResponse.StatusCode, http.StatusNotModified)
Add the actual output as an extra param to these assertions so if the assertion fails we also get useful output

2022-11-30 00:15 UTC, stewartie4 commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	t.Run("Not modified, no node lfmb", func(t *testing.T) {
These tests should use the new system tests framework, see https://0chain.slack.com/archives/C02AV6MKT36/p1669414630904799

2022-11-30 00:15 UTC, stewartie4 commented on internal/api/util/client/api.go
> +		urlBuilder = urlBuilder.AddParams("node-lfmb-hash", string(LFMB.LFMB.Hash))
No need for a complex LFMB object if all you require from it is the hash.
I would change this to a string, which makes for easier readability too

2022-11-30 23:18 UTC, stewartie4 commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	hash, err := getCurrentHash(t)
@SinanEkm not sure this is resolved?

2022-11-30 23:21 UTC, SinanEkm commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	hash, err := getCurrentHash(t)
@stewartie4 I couldn't exactly understand how it should be done. Is there any example that I can look at?

2022-11-30 23:35 UTC, SinanEkm commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +	hash, err := getCurrentHash(t)
@stewartie4 I guess they should be inside each test case right? Now, I changed it like this.

2022-12-01 11:47 UTC, Kishan-Dhakan requested changes

2022-12-01 11:47 UTC, Kishan-Dhakan commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +		t.Parallel()
When you pass in t *test.SystemTest, it automatically runs test cases in parallel. If you want any test to run in sequence, you need to call t.RunSequentially. Moreover, default case timeout is now 40 seconds. Look these methods for future reference:
![image](https://user-images.githubusercontent.com/42718091/205044838-15f45bad-6625-479c-b6ff-3583bd4a8c41.png)

For now, please remove all t.Parallel() calls, not needed here anymore

2022-12-01 11:47 UTC, Kishan-Dhakan commented on tests/api_tests/get_latest_finalized_magic_block_test.go
> +		t.Parallel()
Except the top level t.Parallel():

```
t := test.NewSystemTest(testSetup)
t.Parallel()
```
Keep this as it is

2022-12-01 17:43 UTC, Kishan-Dhakan approved these changes

2022-12-01 17:45 UTC, merged