WIP: Flaky test investigation
0chain/system_test pull request #493
Opened 2022-12-11 23:44 UTC by stewartie4

2022-12-12 18:33 UTC, Kishan-Dhakan requested changes

2022-12-12 18:33 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_copy_test.go
> +		require.True(t, actualCost == 0 || intToZCN(actualCost) == actualExpectedUploadCostInZCN)
This won't always pass since uploadcost calculation is erroneous on zbox/gosdk. I am working on that,

2022-12-12 18:33 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +	t.RunWithTimeout("transfer allocation accounting test", 6*time.Minute, func(t *test.SystemTest) {
This looks flaky in the runs through commits of this PR, are we able to find out why?

2022-12-13 01:10 UTC, stewartie4 commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +	t.RunWithTimeout("transfer allocation accounting test", 6*time.Minute, func(t *test.SystemTest) {
That's what i'm investigating at the minute, I think i've ruled out anything on the test side but watch this space

2022-12-13 01:11 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_copy_test.go
> +		require.True(t, actualCost == 0 || intToZCN(actualCost) == actualExpectedUploadCostInZCN)
Aaaah that makes sense as I was almost sure our test expectation was correct! is there an issue to track this?

2022-12-13 12:37 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_transfer_allocation_test.go
> +	t.RunWithTimeout("transfer allocation accounting test", 6*time.Minute, func(t *test.SystemTest) {
@stewartie4 https://github.com/0chain/blobber/issues/728 do check this out, seems related.

2022-12-13 12:44 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_copy_test.go
> +		require.True(t, actualCost == 0 || intToZCN(actualCost) == actualExpectedUploadCostInZCN)
I created a ticket for it here: https://github.com/0chain/zboxcli/issues/334

2022-12-21 00:02 UTC, merged