0box API tests base
0chain/system_test pull request #506
Opened 2023-01-06 00:03 UTC by stewartie4

2023-01-06 14:32 UTC, Kishan-Dhakan requested changes
Amazing work, happy to merge post lint fixes

2023-01-06 14:32 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +		}, //FIXME: List endpoint does not require signature!
Same as for above TODO

2023-01-06 14:32 UTC, Kishan-Dhakan commented on internal/api/util/test/system_test_framework.go
> +		s.Errorf("Test case exited due to panic - [%v]", err, string(debug.Stack()))
Needs to one more placeholder

2023-01-06 14:32 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +	//wallets, _, _ := zboxClient.ListWallets(t, idToken, csrfToken, phoneNumber) //FIXME: list wallets endpoint returns the client id in place of the wallet id, and does not return the wallet id at all
Can remove this

2023-01-08 13:34 UTC, stewartie4 commented on internal/api/model/zbox.go
> +type ZboxWalletAlt struct { //TODO THIS IS INCONSISTENT AND SHOULD BE FIXED
https://github.com/0chain/0box/issues/375

2023-01-08 13:38 UTC, stewartie4 commented on internal/api/util/client/zbox_client.go
> +		}, //FIXME: List endpoint does not require signature!
https://github.com/0chain/0box/issues/376

2023-01-08 16:55 UTC, Kishan-Dhakan approved these changes

2023-01-09 00:06 UTC, merged