clean up collaborator feature
0chain/system_test pull request #510
Opened 2023-01-15 15:33 UTC by boddumanohar

2023-01-15 23:58 UTC, stewartie4 requested changes

2023-01-15 23:58 UTC, stewartie4 commented on tests/cli_tests/zboxcli_collaborator_test.go
> -func TestCollaborator(testSetup *testing.T) {
let's delete this file if the collaborator feature no longer exists

2023-01-21 18:40 UTC, boddumanohar commented on tests/cli_tests/zboxcli_collaborator_test.go
> -func TestCollaborator(testSetup *testing.T) {
cleaned up the file

2023-01-21 18:46 UTC, boddumanohar commented on tests/cli_tests/zboxcli_rp_lock_unlock_test.go
> +func getReadPoolInfo(t *test.SystemTest) climodel.ReadPoolInfo {
this function was actually present in `zboxcli_collaborator_test.go`. Since that file is now deleted, I moved that function here as this function has more usage in this function.

2023-01-21 18:46 UTC, boddumanohar commented on tests/cli_tests/zboxcli_file_delete_test.go
> +func deleteFile(t *test.SystemTest, walletName, params string, retry bool) ([]string, error) {
this function was actually present in `zboxcli_collaborator_test.go`. Since that file is now deleted, I moved that function here as this function has more usage in this function.

2023-01-21 18:51 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | cleanup-collab  |
| gosdk  | clean-collab  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-21 20:10 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | cleanup-collab  |
| gosdk  | clean-collab  |
| zboxcli  | clean-collab  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-22 16:09 UTC, Kishan-Dhakan approved these changes
LGTM

2023-02-05 14:49 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | cleanup-collab  |
| gosdk  | clean-collab  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-05 16:07 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | cleanup-collab  |
| gosdk  | clean-collab  |
| zboxcli  | clean-collab  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-10 13:24 UTC, Kishan-Dhakan commented
@boddumanohar is this ready to merge?

2023-02-10 13:26 UTC, boddumanohar commented
these changes are ready and the build is also passing earlier. No new changes were added after that.

2023-02-11 22:43 UTC, stewartie4 approved these changes
@boddumanohar is the code ready for these tests? 
if not what's the blocker?

2023-02-15 03:24 UTC, peterlimg commented
Manual system tests was green, I'll merge all related PRs.

2023-02-15 03:24 UTC, merged