fix(zcncore): used zcncore.MakeSCRestAPICall instead of zboxutil.MakeSCRestAPICall
0chain/system_test pull request #514
Opened 2023-01-17 09:39 UTC by cnlangzi

### Changes
-

### Fixes
- speed up get info from sharders

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- https://github.com/0chain/gosdk/pull/718
- https://github.com/0chain/zboxcli/pull/342
- https://github.com/0chain/zwalletcli/pull/207

2023-01-17 10:00 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | fix/speed_up_txn_confirm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-17 11:15 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | fix/speed_up_txn_confirm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-17 17:32 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | fix/speed_up_txn_confirm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-26 08:38 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-26 10:02 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-31 13:42 UTC, Kishan-Dhakan requested changes

2023-01-31 13:42 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			"Error fetching the allocation.zcn: object not found"
It is better to have the ID in the error, this message change seems like a regression.

2023-01-31 14:05 UTC, cnlangzi commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			"Error fetching the allocation.zcn: object not found"
@Kishan-Dhakan  it is not regression bug. the message is changed by [gosdk PR](https://github.com/0chain/gosdk/pull/718). it will be thrown as generic message if any info is not consensus by sharders

2023-02-01 18:04 UTC, Kishan-Dhakan approved these changes

2023-02-01 23:21 UTC, merged