0box nft state/info system test
0chain/system_test pull request #518
Opened 2023-01-20 09:23 UTC by Manali-Jain-squareops

2023-01-20 09:24 UTC, Manali-Jain-squareops commented
NFT State (PUT Request)
![image](https://user-images.githubusercontent.com/86873900/213660602-3ac1248d-a8dc-41ce-a412-40f06a2097db.png)

2023-01-21 15:13 UTC, Kishan-Dhakan requested changes
This only has one case, valid PUT NFT State case. Please check the issue https://github.com/0chain/system_test/issues/513. and add more coverage listed there, for example, "put nft state with invalid allocation id should fail", and other endpoints/methods like NFT Info, GET NFT State/Info, so on

2023-01-21 15:13 UTC, Kishan-Dhakan commented on tests/api_tests/0box_nft_state_test.go
> +	t.RunSequentially("Create a wallet with valid phone number should work", func(t *test.SystemTest) {
Please change the description from to `Create a wallet with valid phone number should work` to something more relevant like "Posting NFT state with valid formdata should work"

2023-01-21 15:13 UTC, Kishan-Dhakan commented on tests/api_tests/0box_nft_state_test.go
> +
Please remove the white spaces to solve lint issue.

2023-01-21 15:13 UTC, Kishan-Dhakan commented on tests/api_tests/0box_nft_state_test.go
> +		require.NotNil(t, NftState)
Please make some stronger assertions here, other than notNil. For example, allocation id should be correct, collection id, so on.

2023-01-22 00:01 UTC, stewartie4 requested changes
Some missing coverage, please see the ticket description 
The list there also isn't exhaustive so feel free to think of other test cases by playing around with the APIs

2023-01-23 08:55 UTC, Manali-Jain-squareops commented
> This only has one case, valid PUT NFT State case. Please check the issue #513. and add more coverage listed there, for example, "put nft state with invalid allocation id should fail", and other endpoints/methods like NFT Info, GET NFT State/Info, so on

still in-progress

2023-01-23 08:56 UTC, Manali-Jain-squareops commented on internal/api/util/client/zbox_client.go
> +	}, HttpPUTMethod)
yes

2023-01-31 11:53 UTC, Manali-Jain-squareops commented
NFT INFO POST and PUT Method
![image](https://user-images.githubusercontent.com/86873900/215752481-de045863-b6c6-404b-ab05-0ff37501be61.png)

NFT INFO POST Method
<img width="759" alt="nft-info-POST" src="https://user-images.githubusercontent.com/86873900/215752777-3ec4a862-3ae1-489a-a344-9901cc621dd6.PNG">

<img width="502" alt="nftPostPASS" src="https://user-images.githubusercontent.com/86873900/215752801-2c79acc8-9227-4065-aea6-140cac86c907.PNG">

2023-03-02 19:17 UTC, closed without merging