System test 508
0chain/system_test pull request #519
Opened 2023-01-20 23:56 UTC by shalinikum

2023-01-21 14:27 UTC, Kishan-Dhakan requested changes
Good work Shalini, minor changes requested

2023-01-21 14:27 UTC, Kishan-Dhakan commented on internal/api/model/zbox.go
> +type Allocationobj struct { // FIXME THIS IS INCONSISTENT AND SHOULD BE FIXED SEE https://github.com/0chain/0box/issues/375
This comment should not be here, please remove

2023-01-21 14:27 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Posting wallet using 0box...")
Change log line

2023-01-21 14:27 UTC, Kishan-Dhakan commented on tests/api_tests/0box_allocation_test.go
> +	// })
Please remove commented code or uncomment it

2023-01-21 14:27 UTC, Kishan-Dhakan commented on tests/api_tests/0box_allocation_test.go
> +		require.NotNil(t, allocationObjCreatedResponse)
Can you change this from a notNil assertion to to a stronger check, for example require.Equal() to what it should equal

2023-01-21 14:27 UTC, Kishan-Dhakan commented on tests/api_tests/0box_allocation_test.go
> +		require.Equal(t, 1, len(allocationList), "Response status code does not match expected. Output: [%v]", response.String())
Use require.Len() instead of require.Equal for asserting on lengths

2023-01-21 14:27 UTC, Kishan-Dhakan commented on tests/api_tests/0box_allocation_test.go
> +		require.Equal(t, 1, len(allocationList), "Response status code does not match expected. Output: [%v]", response.String())
Again, instead of asserting allocation list is notNil please assert something stronger, for example, allocationList[0] oontains the desired allocation ID

2023-01-21 14:27 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +		) // github.com/0chain/system_test.git
Please remove this comment

2023-01-21 14:36 UTC, Kishan-Dhakan requested changes
There is only one case for `POST allocation`, the valid request. Please go through the ticket https://github.com/0chain/system_test/issues/508 to add the remaining cases as well. For example, POST allocation with invalid phone number should fail and similar. ALso, GET ALLOCATION valid+invalid, GET ALLOCATION LIST valid+invalid, UPDATE ALLOCATION valid+invalid requests

2023-01-21 14:36 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +		) // github.com/0chain/system_test.git
Done

2023-01-21 14:41 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +		require.Equal(t, 1, len(allocationList), "Response status code does not match expected. Output: [%v]", response.String())
Done

2023-01-21 14:45 UTC, shalinikum commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Posting wallet using 0box...")
Done.

2023-01-21 14:46 UTC, shalinikum commented on internal/api/model/zbox.go
> +type Allocationobj struct { // FIXME THIS IS INCONSISTENT AND SHOULD BE FIXED SEE https://github.com/0chain/0box/issues/375
Done

2023-01-21 14:47 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	// })
There is no call for delete allocation. How to remove allocations?

2023-01-21 17:28 UTC, Kishan-Dhakan requested changes

2023-01-21 17:28 UTC, Kishan-Dhakan commented on tests/api_tests/0box_allocation_test.go
> +	t.Parallel()
REmove t.Parallel(), since all tests are using same wallet and phone number

2023-01-21 22:50 UTC, stewartie4 requested changes
Some comments and missing coverage

2023-01-21 22:50 UTC, stewartie4 commented on internal/api/model/zbox.go
> +type Allocationobj struct { // FIXME THIS IS INCONSISTENT AND SHOULD BE FIXED SEE https://github.com/0chain/0box/issues/375
is the "obj" suffix necessary? why not just call it 'ZboxAllocation' as is the convention for the other models?

2023-01-21 22:50 UTC, stewartie4 commented on tests/api_tests/0box_allocation_test.go
> +	// })
Check with the 0box team, we may need to extend this in some cases
https://github.com/0chain/0box/issues/407
In general though, you can't delete an  allocation anymore, it just needs to expire on it's own

2023-01-21 22:50 UTC, stewartie4 commented on tests/api_tests/0box_allocation_test.go
> +		require.NotNil(t, allocationObjCreatedResponse)
Agreed, we can keep the nill check but we need to add other assertions, otherwise we don't know if the response is valid or not

2023-01-21 22:50 UTC, stewartie4 commented on tests/api_tests/0box_allocation_test.go
> +	t.Parallel()
Maybe we should keep all 0box tests in a single file for now? 
Until we figure out better how to have a clean test environment per test?

2023-01-21 22:50 UTC, stewartie4 commented on tests/api_tests/0box_allocation_test.go
> +	t.RunSequentially("Create an allocation with valid phone number should work", func(t *test.SystemTest) {
I only see a single test case here.
There were a lot of examples mentioned on the ticket that need to be covered:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/18306778/213890090-5c94484b-7a8d-477d-8e41-ea3fcb4cbe71.png">
And those aren't exhaustive

2023-01-22 09:14 UTC, Kishan-Dhakan commented on tests/api_tests/0box_allocation_test.go
> +	// })
I don't understand how that is related to my comment

2023-01-22 11:51 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	// })
Okay got it. For time being I am just tearing down wallet for each and every case which would automatically delete all allocation. Also removed the comment and made it work.

2023-01-22 11:52 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +		require.NotNil(t, allocationObjCreatedResponse)
Done.

2023-01-22 11:53 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	t.Parallel()
done.

2023-01-22 11:54 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	t.RunSequentially("Create an allocation with valid phone number should work", func(t *test.SystemTest) {
Working on it. Will complete it by today.

2023-01-22 13:42 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	t.RunSequentially("Create an allocation with valid phone number should work", func(t *test.SystemTest) {
Again there is no put mehod for updating allocation in postman.

2023-01-22 14:13 UTC, shalinikum commented on internal/api/model/zbox.go
> +type Allocationobj struct { // FIXME THIS IS INCONSISTENT AND SHOULD BE FIXED SEE https://github.com/0chain/0box/issues/375
Done.

2023-01-22 17:57 UTC, Kishan-Dhakan requested changes
Minor changes.

2023-01-22 17:57 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +		time.Sleep(1 * time.Second)
Remove the wait everywhere

2023-01-22 17:57 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +	t.RunSequentially("Post allocation with invalid phonenumber should not  work", func(t *test.SystemTest) {
Minor: two spaces between `should not` and `work`

2023-01-22 17:57 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +		require.Len(t, allocationList, 1, "Response status code does not match expected. Output: [%v]", response.String())
Keep `require.Len(t, allocationList, 1, "Response status code does not match expected. Output: [%v]", response.String())` above `require.Equal(t, zboxClient.DefaultAllocationId, allocationList[0].Allocs[0].Id)`. That way, if Len is 0, test will fail and execution will stop. If Len check is below and len is 0, `require.Equal(t, zboxClient.DefaultAllocationId, allocationList[0].Allocs[0].Id)` will cause a panic and halt the entire suite

2023-01-22 17:57 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +		_, _, err = zboxClient.ListAllocation(t, firebaseToken.IdToken, csrfToken, "1234567890")
Response status should be 4xx

2023-01-22 17:57 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +		)
Do not ignore asserting on these

2023-01-23 20:45 UTC, stewartie4 commented on tests/api_tests/0box_allocation_test.go
> +	t.RunSequentially("Create an allocation with valid phone number should work", func(t *test.SystemTest) {
There is a PUT endpoint 
PUT {{url}}/v2/allocation

2023-01-30 16:11 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +	t.RunSequentially("Post allocation with invalid phonenumber should not  work", func(t *test.SystemTest) {
Done.

2023-01-30 16:13 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +		time.Sleep(1 * time.Second)
Done.

2023-01-30 18:45 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	t.RunSequentially("Create an allocation with valid phone number should work", func(t *test.SystemTest) {
There is no method for update allocation in 0box. I have checked postman and 0box repo. We need to create one.

2023-01-30 18:46 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	t.RunSequentially("Create an allocation with valid phone number should work", func(t *test.SystemTest) {
> There is no method for update allocation in 0box. I have checked postman and 0box repo. We need to create one.

// FIXME

2023-01-30 18:49 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +		require.Len(t, allocationList, 1, "Response status code does not match expected. Output: [%v]", response.String())
Done.

2023-01-31 20:04 UTC, shalinikum commented on tests/api_tests/0box_allocation_test.go
> +	t.RunSequentially("Create an allocation with valid phone number should work", func(t *test.SystemTest) {
Done.

2023-01-31 20:11 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +		)
Done

2023-02-01 23:57 UTC, stewartie4 approved these changes
Looking great!

2023-02-02 10:22 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +		_, _, err = zboxClient.ListAllocation(t, firebaseToken.IdToken, csrfToken, "1234567890")
let's merge it first. then we will check.

2023-02-02 23:58 UTC, stewartie4 commented on tests/api_tests/config/api_tests_config.yaml
> +default_test_case_timeout: 400s
revert this

2023-02-03 18:09 UTC, Kishan-Dhakan commented on tests/api_tests/config/api_tests_config.yaml
> +default_test_case_timeout: 400s
Good catch, reverted

2023-02-04 14:32 UTC, merged