Modify/fmt leaf hash calculation
0chain/system_test pull request #531
Opened 2023-02-02 09:22 UTC by lpoli

gosdk: https://github.com/0chain/gosdk/pull/719
blobber: https://github.com/0chain/blobber/pull/912
zboxcli: https://github.com/0chain/zboxcli/pull/343

2023-02-09 19:26 UTC, Kishan-Dhakan requested changes

2023-02-09 19:26 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_download_test.go
> +		startBlock := 1
This makes the test useless, it says `Download File With startblock 0` but test uses startblock=1, what's the point exactly?

2023-02-11 17:15 UTC, lpoli commented on tests/cli_tests/zboxcli_file_download_test.go
> +		startBlock := 1
This test actually was useless because it was expecting error.
The use of startblock 1 is due to zboxcli setting. It subtracts startBlock to startBlock -1

2023-02-11 18:27 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/fmt-leaf-hash-calculation  |
| gosdk  | modify/fmt-leaf-hash-calculation  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/fmt-leaf-hash-calculation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-15 07:33 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/fmt-leaf-hash-calculation  |
| gosdk  | modify/fmt-leaf-hash-calculation  |
| zboxcli  | modify/fmt-leaf-hash-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/fmt-leaf-hash-calculation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-25 08:42 UTC, Kishan-Dhakan requested changes

2023-02-25 08:42 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_download_test.go
> +		startBlock := 1
Negative test cases are not useless, they notify if something that wasn't supposed to be happening starts happening. Please revert this change to the way it was and assert on whatever the error is. After your modification this cases becomes a duplicate of the one below it.

2023-02-25 08:42 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_download_test.go
> +		startBlock := 1
Also I believe this should be changed on zboxcli (allow 0 start block) or documented somewhere that it will only work from 1, and this test serves as a documentation till it is changed.

2023-03-03 09:33 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/fmt-leaf-hash-calculation  |
| gosdk  | modify/fmt-leaf-hash-calculation  |
| zboxcli  | modify/fmt-leaf-hash-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/fmt-leaf-hash-calculation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-04 02:07 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/fmt-leaf-hash-calculation  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | modify/fmt-leaf-hash-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/fmt-leaf-hash-calculation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-10 12:40 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | modify/fmt-leaf-hash-calculation  |
| gosdk  | modify/fmt-leaf-hash-calculation  |
| zboxcli  | modify/fmt-leaf-hash-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/fmt-leaf-hash-calculation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-12 17:19 UTC, Kishan-Dhakan approved these changes

2023-03-12 20:07 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | modify/fmt-leaf-hash-calculation  |
| gosdk  | modify/fmt-leaf-hash-calculation  |
| zboxcli  | modify/fmt-leaf-hash-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/fmt-leaf-hash-calculation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-12 21:19 UTC, merged