fix userinfo tests
0chain/system_test pull request #532
Opened 2023-02-02 18:21 UTC by Sanchit011

2023-02-02 18:37 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/userinfo  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/username-exists  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-02 23:57 UTC, stewartie4 commented on internal/api/util/client/zbox_client.go
> -			"X-App-Client-ID":    "31f740fb12cf72464419a7e860591058a248b01e34b13cbf71d5a107b7bdc1e9",
is this not required?

2023-02-02 23:57 UTC, stewartie4 commented on tests/api_tests/0box_test.go
> +		t.Skip("Skip till fixed")
why is this being skipped?

2023-02-03 09:35 UTC, Sanchit011 commented on internal/api/util/client/zbox_client.go
> -			"X-App-Client-ID":    "31f740fb12cf72464419a7e860591058a248b01e34b13cbf71d5a107b7bdc1e9",
its not required as this is an non auth route

2023-02-05 17:40 UTC, Sanchit011 commented on tests/api_tests/0box_test.go
> +		t.Skip("Skip till fixed")
not sure
i think as there is no delete just imitated the above function but get from username rather than phone number

2023-02-06 11:52 UTC, Kishan-Dhakan requested changes

2023-02-06 11:52 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +		t.Skip("Skip till fixed")
I believe this is due to copy and paste without context, I'll test this out

2023-02-06 12:13 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/userinfo  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | fix/username-exists  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-06 12:49 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/userinfo  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | fix/username-exists  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-07 15:21 UTC, merged