523 0box wallet system tests
0chain/system_test pull request #537
Opened 2023-02-08 18:54 UTC by Jayashsatolia403

Added all 4 system tests of API endpoints for wallets.

2023-02-08 22:38 UTC, stewartie4 requested changes

2023-02-08 22:38 UTC, stewartie4 commented on tests/api_tests/0box_test.go
> +
general: lint issues need resolved

2023-02-08 22:38 UTC, stewartie4 commented on tests/api_tests/0box_test.go
>  		}
Why do we need to add these jpgs to the repo?
the other tests generate a file, this also avoids file permission issues

2023-02-08 22:38 UTC, stewartie4 commented on tests/api_tests/0box_test.go
> +	t.RunSequentially("Contact Wallet should work with for multiple users", func(t *test.SystemTest) {
negative scenarios could be added eg.
field validation (invalid, missing field, length check etc.)
404 not found 
etc.

2023-02-08 22:39 UTC, stewartie4 reviewed
Great set of tests, just some minor changes

2023-02-09 06:33 UTC, Jayashsatolia403 commented
Sure, I will fix the lint issues and add some negative scenarios. Thanks for the comment.

2023-02-10 16:46 UTC, Jayashsatolia403 commented
Fixed and Updated the branch.

2023-02-10 16:47 UTC, closed without merging