Changed ReadPoolInfo struct
0chain/system_test pull request #538
Opened 2023-02-08 20:01 UTC by SinanEkm

Made a small change to model.go file for ReadPoolInfo struct. It is related to https://github.com/0chain/zboxcli/pull/350

2023-02-12 15:06 UTC, Kishan-Dhakan commented
@SinanEkm what's the status of this PR?

2023-02-16 23:12 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | model.go-ReadPoolInfo-change  |
| gosdk  | staging  |
| zboxcli  | 340-rp-info-value-returned-requires-consistent-zcn-currency-format  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-18 16:13 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | model.go-ReadPoolInfo-change  |
| gosdk  | staging  |
| zboxcli  | 340-rp-info-value-returned-requires-consistent-zcn-currency-format  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-19 19:29 UTC, Kishan-Dhakan requested changes
The feature change is simply a formatting fix, please change only things related to `output` of rp-info. Revert everything else

2023-02-19 19:29 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_download_token_test.go
> +			finalReadPool.Balance <= initialReadPool.Balance &&
Your change on zboxcli is simply a formatting fix, it should not change test logic. Please revert this

2023-02-19 19:29 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +			finalReadPool.Balance <= initialReadPool.Balance &&
Please revert

2023-02-19 19:29 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.RunWithTimeout("Share unencrypted file using auth ticket - download accounting test", 60*time.Second, func(t *test.SystemTest) {
Why is timeout being reduced?

2023-02-19 19:29 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +			finalReadPool.Balance <= initialReadPool.Balance &&
Please revert

2023-02-19 19:29 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.RunWithTimeout("Share encrypted file using auth ticket - download accounting test - proxy re-encryption ", 60*time.Second, func(t *test.SystemTest) {
Why is timeout being reduced?

2023-02-19 19:35 UTC, SinanEkm commented on tests/cli_tests/zboxcli_download_token_test.go
> +			finalReadPool.Balance <= initialReadPool.Balance &&
It weirdly passed the test with this change. So, I wanted to leave it like this for your opinion. I am reverting it if it shouldn't be like this.

2023-02-19 19:38 UTC, SinanEkm commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.RunWithTimeout("Share unencrypted file using auth ticket - download accounting test", 60*time.Second, func(t *test.SystemTest) {
I tested failed cases in my local and changed timeouts to see if they are working correctly if they aren't timeout. So, I probably forget during local tests. Changing it right now.

2023-02-20 14:36 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | model.go-ReadPoolInfo-change  |
| gosdk  | staging  |
| zboxcli  | 340-rp-info-value-returned-requires-consistent-zcn-currency-format  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-21 14:14 UTC, Kishan-Dhakan requested changes

2023-02-21 14:14 UTC, Kishan-Dhakan commented on internal/cli/model/model.go
> +	Usd     float64 `json:"usd"`
Add test case to ensure the feature works:
- with json flag
- Without json flag

2023-02-22 17:04 UTC, SinanEkm commented on internal/cli/model/model.go
> +	Usd     float64 `json:"usd"`
I added the requested test(s). You can check it @Kishan-Dhakan.

2023-02-23 21:11 UTC, Kishan-Dhakan approved these changes

2023-02-23 21:11 UTC, Kishan-Dhakan commented on tests/cli_tests/zwallet_vesting_test.go
> +	t.Skip("turn on post mainnet")
vesting sc will be turned off for mainnet release so these do not need to run.

2023-02-23 21:13 UTC, merged