Task/zs3 test
0chain/system_test pull request #539
Opened 2023-02-09 16:50 UTC by ahmedzidan

2023-02-11 14:13 UTC, Kishan-Dhakan requested changes

2023-02-11 14:13 UTC, Kishan-Dhakan commented on tests/api_tests/zs3_sever_test.go
> +		require.Equal(t, resp.StatusCode(), client.HttpOkStatus)
Expected value should come first, and actual later. So `require.Equal(t, resp.StatusCode(), client.HttpOkStatus)` should be `require.Equal(t, client.HttpOkStatus, resp.StatusCode())`. Also, for some reason resp.StatusCode() is 0, please investigate
![image](https://user-images.githubusercontent.com/42718091/218262628-67b7e3c3-978c-4677-a75d-94670ea10ebe.png)

2023-02-11 22:26 UTC, stewartie4 requested changes
Minor fixes needed

2023-02-11 22:26 UTC, stewartie4 commented on internal/api/util/client/zs3_client.go
> +	}
we should also use t.log instead of println / the log package

2023-02-11 22:26 UTC, stewartie4 commented on internal/api/util/client/zs3_client.go
> +	fmt.Print(resp.String())
same here, remove this

2023-02-11 22:26 UTC, stewartie4 commented on internal/api/util/client/zs3_client.go
> +		fmt.Println(err)
^^

2023-02-11 22:26 UTC, stewartie4 commented on internal/api/util/client/zs3_client.go
> +		fmt.Println(err)
^^

2023-02-11 22:26 UTC, stewartie4 commented on internal/api/util/client/zs3_client.go
> +		fmt.Println(err)
^^

2023-02-11 22:26 UTC, stewartie4 commented on internal/api/util/client/zs3_client.go
> +		fmt.Println(err)
^^

2023-02-11 22:26 UTC, stewartie4 commented on internal/api/util/client/zs3_client.go
> +		fmt.Println(err)
^^

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/config/api_tests_config.yaml
> +block_worker: https://dev.devnet-0chain.net/dns
revert

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/config/api_tests_config.yaml
> +zs3_server_url: https://dev.devnet-0chain.net/zs3server/
this should probably be dev.0chain.net

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/zs3_sever_test.go
> +		require.Equal(t, resp.StatusCode(), client.HttpOkStatus)
Additionally, I would add the full response in the event that the test fails - resp.Body() as the 4th param

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/zs3_sever_test.go
> +	t.Run("run createbucket test", func(t *test.SystemTest) {
Please rename this test to match existing naming conventions
eg. given, when, then
or x should y when z

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/zs3_sever_test.go
> +	t.Run("run ListBuckets test", func(t *test.SystemTest) {
rename test

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/zs3_sever_test.go
> +	t.Run("run ListBuckets test", func(t *test.SystemTest) {
this looks copied, can be renamed

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/zs3_sever_test.go
> +func TestPutObject(testSetup *testing.T) {
PutBucket ?

2023-02-11 22:26 UTC, stewartie4 commented on tests/api_tests/zs3_sever_test.go
> +func TestCreateBucket(testSetup *testing.T) {
general comment:
Can we also add error scenarios?
example:
What happens when required field are not supplied?
But also think of others

Right now I only see success scenarios

2023-02-12 15:06 UTC, Kishan-Dhakan commented
Closing, duplicated in #544

2023-02-12 15:06 UTC, closed without merging