Feature: add support of Tenderly forks for bridge tests
0chain/system_test pull request #557
Opened 2023-02-15 17:21 UTC by YarikRevich

2023-02-19 13:59 UTC, dabasov requested changes

2023-02-19 13:59 UTC, dabasov commented on tests/cli_tests/config/zbox_config.yaml
> +block_worker: https://test.zus.network/dns
rollback to 
```
block_worker: http://192.168.1.100:9091
```

2023-02-21 14:11 UTC, Kishan-Dhakan requested changes
LGTM except this minor change

2023-02-21 14:11 UTC, Kishan-Dhakan commented on .github/workflows/ci.yml
> +        description: 'Ethereum node URL used for 0Box CLI internal logic and Authorizers registration'
Github actions only allows 10 params, so this won't show up on dialog box. Suggest refactoring `miner_Image` and `sharder_image` into one `0chain image` param, same for blobber/validator image params. It will reduce two params and make space for this new one.

2023-02-22 14:05 UTC, Kishan-Dhakan approved these changes

2023-02-22 19:10 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/tenderly_support  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | feature/reconciliation_problem  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-23 10:09 UTC, dabasov approved these changes
lgtm

2023-02-23 15:25 UTC, Kishan-Dhakan commented
@YarikRevich some of the bridge tests are failing, please check

2023-02-25 21:09 UTC, Kishan-Dhakan approved these changes
LGTM

2023-02-26 10:40 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/tenderly_support  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | feature/system_tests_workflow  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-26 19:38 UTC, merged