0Box: Utility endpoints system tests
0chain/system_test pull request #563
Opened 2023-02-19 22:37 UTC by iamrz1

https://github.com/0chain/system_test/issues/547

2023-03-06 19:13 UTC, Kishan-Dhakan requested changes
Happy to merge after negative cases are added

2023-03-06 19:13 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +	})
Can you add negative test cases as well?

2023-03-09 17:50 UTC, Kishan-Dhakan approved these changes
LGTM

2023-03-09 22:01 UTC, stewartie4 approved these changes
LGTM

2023-03-09 22:12 UTC, merged