added Zs3image input
0chain/system_test pull request #574
Opened 2023-03-01 18:21 UTC by shahnawaz-creator

2023-03-01 18:46 UTC, Kishan-Dhakan requested changes

2023-03-01 18:46 UTC, Kishan-Dhakan commented on tests/api_tests/list_buckets_test.go
> +		// t.Skip("skip till zs3server issues are resolved")
Please remove the code instead of commenting it.

2023-03-01 19:15 UTC, Kishan-Dhakan requested changes
Also unskip create bucket tests

2023-03-01 19:27 UTC, shahnawaz-creator commented on tests/api_tests/list_buckets_test.go
> +		// t.Skip("skip till zs3server issues are resolved")
Removed

2023-03-01 19:31 UTC, shahnawaz-creator commented
> Also unskip create bucket tests

Removed the skipping on create bucket tests

2023-03-02 19:52 UTC, ahmedzidan approved these changes
LGTM

2023-03-03 19:01 UTC, Kishan-Dhakan approved these changes
LGTM

2023-03-03 20:39 UTC, merged