[Draft - Do not merge]System test 513- nft collection test
0chain/system_test pull request #575
Opened 2023-03-01 18:22 UTC by shalinikum

2023-03-06 19:22 UTC, Kishan-Dhakan requested changes

2023-03-06 19:22 UTC, Kishan-Dhakan commented on 0chain-0box.postman_collection .json
> +{
Remove this file

2023-03-06 19:22 UTC, Kishan-Dhakan commented on 0chain-0box.postman_collection.json
> +{
Remove this file

2023-03-06 19:22 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +		DefaultAuthTicket:     "eyJjbGllbnRfaWQiOiIiLCJvd25lcl9pZCI6ImEzMzQ1NGRhMTEwZGY0OTU2ZDc1YzgyMDA2N2M1ZThmZTJlZjIyZjZkNWQxODVhNWRjYTRmODYwMDczNTM1ZDEiLCJhbGxvY2F0aW9uX2lkIjoiZTBjMmNkMmQ1ZmFhYWQxM2ZjN
Add //nolint:revive here or try using raw string

2023-03-06 19:22 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +func (c *ZboxClient) CreateNftCollectionId(t *test.SystemTest, idToken, csrfToken, phoneNumber, createdBy, collectionName, collectionId, totalNfts, collectionType, allocationId, baseUrl, symbol strin
Rename CurrMints to currMints

2023-03-06 19:22 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +func Test0BoxNFT(testSetup *testing.T) {
Please cleanup this file once you're done with local testing

2023-03-06 19:22 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +
remove unnecessary whitespaces

2023-03-06 19:22 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> -func Test0BoxWallet(testSetup *testing.T) {
This should not be removed, might be branching issue, please re-add this

2023-03-06 19:22 UTC, Kishan-Dhakan commented on tests/api_tests/config/api_tests_config.yaml
> +<<<<<<< HEAD
Remove the conflict lines please. Also, remove the 2 png files added in the PR if unnecessary

2023-03-09 18:17 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | system_test_513  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-10 13:01 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | system_test_513  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-12 05:22 UTC, Kishan-Dhakan approved these changes

2023-03-12 05:22 UTC, merged