removed curator from system_tests
0chain/system_test pull request #578
Opened 2023-03-04 20:07 UTC by Hitenjain14

Removed curator functionality . 
Related PR's - 
0chain - https://github.com/0chain/0chain/pull/2184
gosdk - https://github.com/0chain/gosdk/pull/819
zboxcli - https://github.com/0chain/zboxcli/pull/372

2023-03-06 18:51 UTC, Kishan-Dhakan requested changes

2023-03-06 18:51 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
>  package cli_tests
This file can be deleted, please remove it completely

2023-03-07 11:21 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | rm_curator  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | rm_curator  |
| zwalletcli  | staging  |
| 0chain  | rm-curator  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-10 19:36 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | rm_curator  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | rm_curator  |
| zwalletcli  | staging  |
| 0chain  | rm-curator  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-11 09:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | rm_curator  |
| gosdk  | rm_curator  |
| zboxcli  | rm_curator  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-11 11:06 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | rm_curator  |
| gosdk  | rm_curator  |
| zboxcli  | rm_curator  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-11 11:34 UTC, merged