fix responses
0chain/system_test pull request #587
Opened 2023-03-15 19:30 UTC by Sanchit011

2023-03-15 19:54 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | fix/update-delete  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | feat/delete-routes  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-16 20:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-delete  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | feat/delete-routes  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-20 22:31 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-delete  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | feat/delete-routes  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-20 23:31 UTC, stewartie4 requested changes
Some API changes seem incorrect

2023-03-20 23:31 UTC, stewartie4 commented on tests/api_tests/0box_test.go
> +		require.Equal(t, 200, response.StatusCode(), "Response status code does not match expected. Output: [%v]", response.String())
HTTP status code 201 means "created"
This is inappropriate for PUT/PATCH calls which updates an already existing resource

2023-03-20 23:31 UTC, stewartie4 commented on tests/api_tests/0box_test.go
> +		require.Equal(t, 200, response.StatusCode(), "Response status code does not match expected. Output: [%v]", response.String())
HTTP status code 201 means "created"
This is inappropriate for PUT/PATCH calls which updates an already existing resource

2023-03-20 23:45 UTC, Sanchit011 commented on tests/api_tests/0box_test.go
> +		require.Equal(t, 200, response.StatusCode(), "Response status code does not match expected. Output: [%v]", response.String())
we should use 200 right?
that is what the new status code is

2023-03-22 22:27 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-delete  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | feat/delete-routes  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-22 22:29 UTC, Kishan-Dhakan approved these changes
LGTM

2023-03-23 13:27 UTC, merged