System test 534
0chain/system_test pull request #588
Opened 2023-03-16 16:42 UTC by shalinikum

2023-03-16 20:02 UTC, Kishan-Dhakan requested changes
One query, LGTM otherwise

2023-03-16 20:02 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +		require.Equal(t, "creating allocation successful", allocationObjCreatedResponse.Message)
Why is this message saying `successful` if status is not 2XX?

2023-03-16 20:04 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +		require.Equal(t, "creating allocation successful", allocationObjCreatedResponse.Message)
Just waiting for system test output. I will change accordingly. missed it.

2023-03-20 19:18 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | system-test-534  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-20 19:40 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | system-test-534  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-01 07:57 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | system-test-534  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | system-test-534  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-01 19:39 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | system-test-534  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | system-test-534  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-04 17:48 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | system-test-534  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | system-test-534  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-06 17:46 UTC, closed without merging

2023-04-06 17:47 UTC, shalinikum commented
Created a different PR