minor fix after zboxcli change(s)
0chain/system_test pull request #592
Opened 2023-03-20 19:40 UTC by SinanEkm

Changed the `TestShareFile/Shared_encrypted_file_to_public_using_auth_ticket_should_fail_to_download` case to `TestShareFile/Shared_encrypted_file_to_public_using_auth_ticket_should_fail`. 

Related Zboxcli PR: https://github.com/0chain/zboxcli/pull/385

2023-03-20 23:33 UTC, stewartie4 requested changes

2023-03-20 23:33 UTC, stewartie4 commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.RunWithTimeout("Shared encrypted file to public using auth ticket should fail", 60*time.Second, func(t *test.SystemTest) {
Maybe state why the failure is happening in the test case name?
"should fail due to..."

2023-03-21 13:16 UTC, SinanEkm commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.RunWithTimeout("Shared encrypted file to public using auth ticket should fail", 60*time.Second, func(t *test.SystemTest) {
Ok, got it!

2023-03-21 22:11 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/TestShareFile  |
| gosdk  | staging  |
| zboxcli  | 357-for-encrypted-share-clientid-and-encryptionpublickey-should-be-mandatory  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-22 17:45 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | fix/TestShareFile  |
| gosdk  | staging  |
| zboxcli  | 357-for-encrypted-share-clientid-and-encryptionpublickey-should-be-mandatory  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-22 17:47 UTC, Kishan-Dhakan approved these changes

2023-03-22 17:47 UTC, merged