172 stake pool unlock and unstaked tokens
0chain/system_test pull request #620
Opened 2023-04-04 17:04 UTC by Jayashsatolia403

2023-04-04 18:57 UTC, Kishan-Dhakan requested changes
Good work, nearly there, some changes requested. Please also fix the lint issue raised by Github's beta feature in `internal/api/util/client/zs3_client.go`

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +
Remove unnecessary spacing please

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +	}
Replace with require.Nil(t, err)

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +	fmt.Println(wallet)
Remove fmt printing please, use t.Log() where necessary

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +	t.RunSequentiallyWithTimeout("should allow stake pool to be created", 60*time.Minute, func(t *test.SystemTest) {
60 minute timeout is okay for local debugging but does not serve any practical purpose on CI. Please replace it with appropriate timeout, the idea is the if some refactor slows down any process in the test case too much, we should know about it, but if timeout is 60 minute, we will never catch any performance regression

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +	t.RunSequentiallyWithTimeout("should allow stake pool to be created", 60*time.Minute, func(t *test.SystemTest) {
The description is not apt. It should be something like "total stake in a blobber can never be lesser than it's used capacity". Then, you can add some comments at the top explaining the flow, see how Piers's miner_rewards_test file explains it for reference

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +			}
Replace all such instances with require.Nil(t, err) please

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +			"size":   32212254716,
Instead of hardcoding the size here, please create a variable and initialize it using the logic you have behind this size

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +		fmt.Println(allocationId)
remove fmt log lines (here + below)

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +		require.Equal(t, totalOffersNew, totalOffers+9999999999, "Total Offers should Increase")
where is this `9999999999` coming from? Please show it using a variable

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +		require.Greater(t, totalOffersNew, totalOffers, "total offers should be greater")
Line 115 is unnecessary after 113, `totalOffersNew = totalOffers+9999999999` implies `totalOffersNew > totalOffers` anyway

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +
remove unnecessary spacing

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +		//require.Equal(t, expectedWallet1Balance, wallet1Balance, "wallet 1 balance is not as expected")
remove commented code

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +type BlobberInfo struct {
this should be in models.go, not here. Please check where the other structs are stored for cli tests

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_stake_unstake_token_test.go
> +func stakeTokensForWallet(t *test.SystemTest, cliConfigFilename, wallet, params string, retry bool) ([]string, error) {
Please refactor as follows to avoid duplicated code:

DoSomething(params...) {
    return DoSomethingForWallet(params..., escapedTestName(t))
}

DoSomethingForWallet(params..., wallet) {
    // Do something
}

2023-04-04 18:57 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_stake_unstake_token_test.go
> +func unstakeTokensForWallet(t *test.SystemTest, cliConfigFilename, wallet, params string) ([]string, error) {
Same refactor as above

2023-04-04 19:17 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +		require.Equal(t, totalOffersNew, totalOffers+9999999999, "Total Offers should Increase")
It is just tokens calculated from staked capacity. Should I change it with the variable too?

2023-04-04 19:18 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +			"size":   32212254716,
Sure.

2023-04-04 19:35 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +	t.RunSequentiallyWithTimeout("should allow stake pool to be created", 60*time.Minute, func(t *test.SystemTest) {
Makes sense. Setting it to 5 minutes. This time should be enough.

2023-04-05 20:14 UTC, Kishan-Dhakan commented
@Jayashsatolia403 the case you've added is failing, please check

2023-04-07 15:43 UTC, Kishan-Dhakan requested changes

2023-04-07 15:43 UTC, Kishan-Dhakan commented on internal/api/util/client/zs3_client.go
> -
Why is this being removed?

2023-04-07 15:43 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +func TestStakePool(testSetup *testing.T) {
Please fix lint issues

2023-04-07 15:43 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +		allocSize := 32212254716 // 30 GB (We are using 30 GB of allocation to match it with the staked capacity [ staked capacity = 10GB for each blobber (3 data 3 parity)])
You need to calculate this on the fly. Get total stake of the blobber, and calculate staked capacity from there at this point of time

2023-04-07 15:43 UTC, Kishan-Dhakan commented on tests/cli_tests/stake_pool_test.go
> +			output, err = unstakeTokens(t, configPath, createParams(map[string]interface{}{"blobber_id": blobber.Id}))
there should be a require.Nil(t, err) on errors inside this loop

2023-04-07 15:45 UTC, Jayashsatolia403 commented on internal/api/util/client/zs3_client.go
> -
This was not used anywhere and was giving lint errors. You told me to fix the lint errors in this file specifically so removed it.

Should I add it again?

2023-04-10 12:07 UTC, Kishan-Dhakan commented on internal/api/util/client/zs3_client.go
> -
No

2023-04-18 16:14 UTC, Kishan-Dhakan requested changes
Happy to merge post changes, lint fixes and green run

2023-04-18 16:14 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_stake_unstake_token_test.go
> +	output, err := unstakeTokensForWallet(t, cliConfigFilename, escapedTestName(t), params)
Simply do `return unstakeTokensForWallet(t, cliConfigFilename, escapedTestName(t), params)`

2023-04-18 16:14 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_stake_unstake_token_test.go
> +	output, err := stakeTokensForWallet(t, cliConfigFilename, escapedTestName(t), params, retry)
Simply do `return stakeTokensForWallet(t, cliConfigFilename, escapedTestName(t), params, retry)`

2023-04-20 11:32 UTC, Sriep requested changes

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		lenDelegates := len(delegates)
Why not replace this with something like 
```go
initalDelegateLength = len(stakePool.Delegates)
```
so its clear what you are doing later on line 106. Same goes for totalOffers above.

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		// create an allocation of capacity
Not a helpful comment. How about explaining why want this particular allocation size.

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		newStakeWallet := "new_stake_wallet"
Can you make this a constant?

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		require.Equal(t, lenDelegatesNew, lenDelegates+1, "delegates should be greater")
Greater than what? Maybe you mean the number of delegates should have increased?

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		require.Nil(t, err, "error should not be there")
`error should not be there` that is implicit try saying where you got the error. For example:
```go
require.NoErrorf(t, err, "error unstaking tokens from blobber %s", blobber.Id)
```

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		require.Equal(t, lenDelegatesNew+1, lenDelegates, "delegates should be greater")
As mentioned above, its the number of delegates that should increase, not the delegates themselves.

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		require.Nil(t, err, "error should not be there")
As above, its implicit that there should be no error; explain from where the error is coming.

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		require.Equal(t, lenDelegatesNew, lenDelegates, "delegates should be equal")
All delegates in a stake pool should be distinct, its the number of delegates that should be equal here.

2023-04-20 11:32 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		require.Equal(t, lenDelegatesNew+1, lenDelegates, "delegates should be greater")
As mentioned above its the length of the delegates that should have increased not the delegates themselves.

2023-04-20 12:46 UTC, Jayashsatolia403 commented on internal/cli/model/model.go
> +type BlobberInfoDetailed struct {
This was already created. Both BlobberInfo and BlobberDetails does not have the data I need.

2023-04-20 12:47 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +package cli_tests
Sure, I will change the file name. Wasn't aware of this.

2023-04-20 12:48 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +		maxStakedCapacity := uint64(18446744073709551615)
Let me change this. Was't aware of this.

2023-04-20 12:49 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +			err = json.Unmarshal([]byte(output[len(output)-1]), &blInfo)
Yes, It can.

2023-04-21 09:24 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +			if stakedCapacity < maxStakedCapacity {
I think this is alright. We can set it to the stakedCapacity of the first blobber but I don't think it makes much sense to change this. Am I getting it wrong?

2023-04-21 09:26 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +		// create an allocation of capacity
To match it with minStakedCapacity.

2023-04-21 09:26 UTC, Jayashsatolia403 commented on tests/cli_tests/stake_pool_test.go
> +		newStakeWallet := "new_stake_wallet"
It is secondary wallet so yes, we can.

2023-04-21 10:20 UTC, Sriep commented on internal/cli/model/model.go
> +type BlobberInfoDetailed struct {
I think you should modify one of the existing blobber objects instead of adding a new one. You could alternately merge together all the blobber objects into one.  You can always use composition if you want to restrict the fields.

2023-04-21 10:38 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +			if stakedCapacity < maxStakedCapacity {
It works fine; I was thinking of your audience. IMHO, you want to write your code so it's as easy for other developers to follow, even if that means adding an extra line or two of code. 

You could for instance add a `firstTime = true` boolean which has the advantage of making it explicit what you are doing and does not have the reader confused as to what `math.MaxUint64` has to do with anything.

2023-04-21 10:47 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		// create an allocation of capacity
` create an allocation of capacity` does not make sense. If you add a comment, you want it to be useful for the reader. I suggest either removing this comment or change it to explain why we are setting the allocation size to this particular value.

2023-04-21 10:50 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		newStakeWallet := "new_stake_wallet"
When a variable is designed to never be changed, it's best to make it a constant. This is mainly as a guide to the reader and just good coding, rather than to save a fraction of a nanosecond.

2023-04-21 11:02 UTC, Sriep commented on tests/cli_tests/stake_pool_test.go
> +		require.Equal(t, lenDelegatesNew, lenDelegates, "delegates should be equal")
We are comparing the length of the delegates' slices, not the delegates themselves.

2023-04-21 11:58 UTC, Jayashsatolia403 commented on internal/cli/model/model.go
> +type BlobberInfoDetailed struct {
Is there any specific reason for this?

2023-04-22 17:27 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_stake_pool_test.go
> +
This is the max limit so we are staking multiple times in the clubs of 9.

2023-04-23 08:25 UTC, Sriep commented on internal/cli/model/model.go
> +type BlobberInfoDetailed struct {
It is good coding practice to avoid copying and pasting and have one declaration of each object type. It makes the code easier to understand and reduces maintenance overheads. 

It confuses anyone reading the code who will expect there to be a good reason for multiple blobber objects, confused developers make mistakes. The next time someone needs to modify the blobber object, the developer might not expect three copies of the blobber and only update one of them.

2023-04-23 08:30 UTC, Sriep commented on tests/cli_tests/zboxcli_stake_pool_test.go
> +
What does `Clubs of 9` mean? Anyway, don't tell me; tell anyone reading the code. The reader is very lily to get lost at this point.

2023-05-03 19:39 UTC, Kishan-Dhakan commented
Closing this as commit history is too polluted. Will be done in https://github.com/0chain/system_test/pull/659.

2023-05-03 19:39 UTC, closed without merging