system-test-534
0chain/system_test pull request #622
Opened 2023-04-06 16:56 UTC by shalinikum

2023-04-06 19:37 UTC, Kishan-Dhakan commented
Where are the new tests in this PR? This only seems to be removing a lot of tests

2023-04-11 22:33 UTC, stewartie4 requested changes

2023-04-11 22:33 UTC, stewartie4 commented on tests/api_tests/0box_test.go
> +	// todo: These tests are sequential and start with teardown as they all share a common phone number
Why move these tests to a single file, is it not tidier as separate files?

2023-04-12 23:59 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +	// todo: These tests are sequential and start with teardown as they all share a common phone number
Hi Ryan,
we don't know in which order the test file would run, and there are lots of other testcase which are using allocation endpoint. Keeping that in mind we should move allocation at top.

2023-04-19 14:28 UTC, Kishan-Dhakan approved these changes
LGTM

2023-04-19 14:29 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +	// todo: These tests are sequential and start with teardown as they all share a common phone number
@shalinikum it was added to a new file for the exact reason you mentioned, we know `0box_allocation_test.go` will run before `0box_tests.go`, since it is lexicographically smaller name. I'v reverted the separation to as it was.

2023-04-19 16:29 UTC, shalinikum commented on tests/api_tests/0box_test.go
> +	// todo: These tests are sequential and start with teardown as they all share a common phone number
okay.Kishan Thank you so much. I didn't new that.

2023-04-19 23:12 UTC, stewartie4 approved these changes
LGTM - good increased coverage

2023-04-21 13:28 UTC, Kishan-Dhakan approved these changes
LGTM

2023-04-21 13:28 UTC, merged