New test for gosdk#869
0chain/system_test pull request #628
Opened 2023-04-10 20:03 UTC by SinanEkm

An additional test after changes made in [gosdk#869](https://github.com/0chain/gosdk/issues/869).

2023-04-18 15:53 UTC, Kishan-Dhakan requested changes
Happy to merge post a manual green run

2023-04-18 15:53 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.RunWithTimeout("deneme", 2*time.Minute, func(t *test.SystemTest) {
Provide a good description instead of "deneme"

2023-04-18 15:53 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> +		//Share unencrypted file privately should fail
Fix lint issues

2023-04-23 19:06 UTC, SinanEkm commented on tests/cli_tests/zboxcli_share_file_test.go
> +	t.RunWithTimeout("deneme", 2*time.Minute, func(t *test.SystemTest) {
Oh sorry, it was from local testing :d

2023-05-23 20:12 UTC, merged