System test for kill_miner and kill_sharder
0chain/system_test pull request #631
Opened 2023-04-12 14:45 UTC by Sriep

Requires

0chain: https://github.com/0chain/0chain/pull/2285
goSDK: https://github.com/0chain/gosdk/pull/891
zwallet: https://github.com/0chain/zwalletcli/pull/154

2023-04-13 11:57 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | kill_miner  |
| gosdk  | minersc_kill  |
| zboxcli  | staging  |
| zwalletcli  | kill_miners  |
| 0chain  | pr-2285-0e9c3888  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-14 11:46 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | kill_miner  |
| gosdk  | minersc_kill  |
| zboxcli  | staging  |
| zwalletcli  | kill_miners  |
| 0chain  | kill_minersc  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-18 16:05 UTC, Kishan-Dhakan requested changes

2023-04-18 16:05 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_kill_sharder_test.go
> +	t.RunSequentiallyWithTimeout("Killed sharder does not receive rewards", 1000*time.Second, func(t *test.SystemTest) {
Why the substantially longer timeout here, 1000 is 5x of shutdown miner

2023-04-19 09:00 UTC, Sriep commented on tests/cli_tests/zwalletcli_kill_sharder_test.go
> +	t.RunSequentiallyWithTimeout("Killed sharder does not receive rewards", 1000*time.Second, func(t *test.SystemTest) {
The longer timeout here is that there are often no sharders available to kill, so we must wait for one to be added to the MPT. For some reason, there is usually a miner we can kill registered, so the wait is not so important.

2023-04-19 11:59 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | kill_miner  |
| gosdk  | minersc_kill  |
| zboxcli  | kill_miners  |
| zwalletcli  | staging  |
| 0chain  | kill_minersc  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-03 23:01 UTC, stewartie4 reviewed
is it possible that these tests will affect other tests? eg. by killing a miner/validator?

2023-05-04 14:06 UTC, Kishan-Dhakan commented
> is it possible that these tests will affect other tests? eg. by killing a miner/validator?
Yep, the nodes being killed can't be used again. I'll make the necessary CI changes today to close this.

2023-05-12 06:42 UTC, peterlimg commented
@Kishan-Dhakan what's the plan on CI to fix this issue, maybe we should run the kill and shutdown tests in the end of the tests so that it would not affect other cases.

2023-05-15 09:31 UTC, Sriep commented
I added a check that there are at least a minimum number of miners/sharders in the 0chian. The tests are skipped if there are not enough miners/sharders. 

The theory is that if we have zero or one miner/sharder in the 0chain then the 0chain is not suitable for this test; as the system tests should be able to run against any valid 0chian the solution would seem to be skipping the test in this situation. If there is still a problem with other tests we can increase the number of miners/sharders until there is not.

Adding a framework to allow partial ordering of tests would be a nice addition.

2023-05-23 14:09 UTC, merged