Zs3server test
0chain/system_test pull request #634
Opened 2023-04-13 17:17 UTC by shalinikum

2023-04-18 15:58 UTC, Kishan-Dhakan requested changes
remove empty test-file from repo please

2023-04-18 15:58 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +	// t.Run("GetObjects should return 200 all the parameter are correct", func(t *test.SystemTest) {
Fix lint issues

2023-04-18 15:58 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +	// t.Run("GetObjects should return 200 all the parameter are correct", func(t *test.SystemTest) {
Why is GetObjects commented out?

2023-04-20 16:53 UTC, shalinikum commented on tests/api_tests/zs3server_opertions_test.go
> +	// t.Run("GetObjects should return 200 all the parameter are correct", func(t *test.SystemTest) {
Will remove it.

2023-04-28 14:48 UTC, Kishan-Dhakan reviewed
Happy to merge after passing run

2023-04-28 14:48 UTC, Kishan-Dhakan commented on tests/api_tests/test-file
Remove this please

2023-05-16 15:08 UTC, Kishan-Dhakan requested changes
Good work, happy to merge post lint fixes and some cleanup

2023-05-16 15:08 UTC, Kishan-Dhakan commented on tests/api_tests/test-file
Please remove this file

2023-05-16 15:08 UTC, Kishan-Dhakan commented on tests/api_tests/graph_test.go
Please remove this file

2023-05-16 15:11 UTC, shalinikum commented on tests/api_tests/test-file
This is importanat file to run the test. As we need to upload a file.

2023-05-16 15:11 UTC, shalinikum commented on tests/api_tests/graph_test.go
I will remove it.

2023-05-25 15:24 UTC, Kishan-Dhakan requested changes
Minor changes requested

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +// adding comment to run ppipeline again
You can simply re-run the previous action, please remove it

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +		// t.Skip("wait for the issue to get resolved : https://github.com/0chain/zs3server/issues/21")
Please remove commented code

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
Filename and test name should have operations, not opertions

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +		require.Equal(t, 200, resp.StatusCode())
This test already exists in create_bucket_test.go, please remove it if it's exactly same

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +		require.Equal(t, 200, resp.StatusCode())
If it's an error this should be 4XX or 5XX, please add a TODO comment here and create an issue on zs3server

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +		require.Equal(t, 200, resp.StatusCode())
Also take over the content of that file into this one and remove that file

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +	t.RunSequentially("ListBucket should return 200 all the parameter are correct", func(t *test.SystemTest) {
Already exists in list_buckets_test.go. Please move content from that file to this and remove that file

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +	t.RunSequentially("ListObjects should return 200 all the parameter are correct", func(t *test.SystemTest) {
Already exists in list_objects_test.go, same as above

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +		// t.Skip("wait for the issue to get resolved : https://github.com/0chain/zs3server/issues/21")
Remove comment

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +	t.RunSequentially("PutObjects should return error when buckcet name doesnot exist", func(t *test.SystemTest) {
Space between does and not

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +	t.RunSequentially("GetObjects should return 200 all the parameter are correct", func(t *test.SystemTest) {
Please keep a newline between test cases

2023-05-25 15:24 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +		// t.Skip("wait for the issue to get resolved : https://github.com/0chain/zs3server/issues/22")
Remove comment

2023-05-25 15:44 UTC, shalinikum commented on tests/api_tests/zs3server_opertions_test.go
> +	t.RunSequentially("ListBucket should return 200 all the parameter are correct", func(t *test.SystemTest) {
these two are different

2023-05-25 17:28 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +	t.RunSequentially("ListObjects should return 200 all the parameter are correct", func(t *test.SystemTest) {
Check this on master https://github.com/0chain/system_test/blob/216311121a1d246a836e907c6f27e327724bd95b/tests/api_tests/list_objects_test.go#L12, it already exists.

2023-05-25 17:29 UTC, Kishan-Dhakan commented on tests/api_tests/zs3server_opertions_test.go
> +		require.Equal(t, 200, resp.StatusCode())
This is not resolved

2023-05-25 18:31 UTC, Kishan-Dhakan approved these changes
LGTM

2023-05-25 18:36 UTC, merged