Added tokenomics code to new workflow
0chain/system_test pull request #639
Opened 2023-04-17 17:17 UTC by Jayashsatolia403

2023-04-17 17:53 UTC, Kishan-Dhakan requested changes
Partial review: we don't want to turn off other tests in the main runs, we want to keep tokenomics suite disabled in the main run, and run only tokenomics suite when we need (via a manual trigger or cron job)

2023-04-17 17:53 UTC, Kishan-Dhakan commented on .github/workflows/ci.yml
> +          run_cli_system_tests: false
This ci.yml is the workflow file for manual runs and automated runs on every commit, we don't want to set them to false here. What you want to do is, create a separate workflow file, that runs manually, and only runs tokenomics suite. You can read on github workflows or check out or workflow files to see how they work.

2023-04-17 17:59 UTC, Jayashsatolia403 commented on .github/workflows/ci.yml
> +          run_cli_system_tests: false
Yeah, I just turned them off to get check if my changes are working faster.

2023-04-27 16:20 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | tokenomics_suite  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | tokenomics_suite_cicd_test  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-24 18:39 UTC, closed without merging