Add s3 migration base system test
0chain/system_test pull request #647
Opened 2023-04-20 21:30 UTC by stewartie4

2023-04-21 17:19 UTC, Kishan-Dhakan requested changes
That's a great cornerstone PR for these stories! Happy to merge post green run but would like to discuss how we go about running these cases on slack.

2023-04-21 17:19 UTC, Kishan-Dhakan commented on tests/cli_tests/s3mgrt_migrate_test.go
> +	t.RunSequentiallyWithTimeout("Should migrate existing bucket successfully", 15*time.Minute, func(t *test.SystemTest) {
15 minutes is a long time👀. What options do we want to run this? Starting a thread on slack

2023-05-11 21:57 UTC, stewartie4 commented on tests/cli_tests/s3mgrt_migrate_test.go
> +	t.RunSequentiallyWithTimeout("Should migrate existing bucket successfully", 15*time.Minute, func(t *test.SystemTest) {
created a smaller bucket and now the test runs in ~20s

2023-05-11 23:06 UTC, stewartie4 commented
system tests passing, minus known authorizor crash

2023-05-11 23:06 UTC, merged