added web streaming system test
0chain/system_test pull request #648
Opened 2023-04-21 13:41 UTC by Manish-210

2023-04-21 13:58 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add_transcode_test  |
| gosdk  | feature/transcode-on-upload  |
| zboxcli  | feature/web-streaming  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-21 14:23 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add_transcode_test  |
| gosdk  | feature/transcode-on-upload  |
| zboxcli  | feature/web-streaming  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-26 08:18 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add_transcode_test  |
| gosdk  | feature/transcode-on-upload  |
| zboxcli  | feature/web-streaming  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-26 13:09 UTC, Kishan-Dhakan requested changes
Minor change but LGTM otherwise

2023-04-26 13:09 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			require.Nil(t, err, "Failed to download test video file: ", strings.Join(output, "\n"))
Can you abstract this into method?

2023-05-03 21:04 UTC, Kishan-Dhakan approved these changes

2023-05-03 21:04 UTC, merged