Add staked capacity test
0chain/system_test pull request #659
Opened 2023-05-03 19:39 UTC by Kishan-Dhakan

2023-05-05 13:03 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | test/staked-capacity  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/stakepool_test  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-13 14:40 UTC, stewartie4 commented on tests/cli_tests/blobber_staked_capacity_test.go
> +	_, err := createWallet(t, configPath)
this test setup should now be wrapped in a t.TestSetup block like the other tests

2023-05-13 14:42 UTC, stewartie4 requested changes

2023-05-13 14:42 UTC, stewartie4 commented on tests/cli_tests/blobber_staked_capacity_test.go
> +		_, err := createWallet(t, configPath)
Looks like really good/complex work, there is a lot going on in this test and it is 200 lines long, can some logic be broken out into functions to make it more readable? 
eg. anywhere there is a comment could probably be a function call

2023-05-13 14:55 UTC, stewartie4 commented on tests/cli_tests/zboxcli_stake_unstake_token_test.go
> +	return cliutils.RunCommand(t, fmt.Sprintf("./zbox sp-unlock %s --silent --wallet %s_wallet.json --configDir ./config --config %s", params, wallet, cliConfigFilename), 3, time.Second*2)
re-add the log line
t.Log("Unlocking tokens from stake pool...")
here

2023-05-13 14:55 UTC, stewartie4 requested changes

2023-05-13 14:55 UTC, stewartie4 commented on tests/cli_tests/zboxcli_stake_unstake_token_test.go
> +	cmd := fmt.Sprintf("./zbox sp-lock %s --silent --wallet %s_wallet.json --configDir ./config --config %s", params, wallet, cliConfigFilename)
re-add the log line
t.Log("Staking tokens...")
here

2023-05-13 23:57 UTC, stewartie4 commented on tests/cli_tests/blobber_staked_capacity_test.go
> +		_, err := createWallet(t, configPath)
there is still a lot of logic that could be broken into functions here
eg.

fetchStakePoolInfo
stakeBlobbers
assertStakeGreaterThanUsedCapacity
createAllocationOfMaxSizeBlobbersCanHonour
...
....
.....
unstakeTokens

2023-05-13 23:59 UTC, stewartie4 commented on tests/cli_tests/blobber_staked_capacity_test.go
> +	t.TestSetup("stake_pool_test", func() {
This label should be something like "register wallet and get blobbers"

2023-05-14 00:00 UTC, stewartie4 commented on tests/cli_tests/blobber_staked_capacity_test.go
> +package cli_tests
If these tests are sequential then they should probably run at the beginning of the suite, so a "0_" should be appended to the file name

2023-05-14 00:00 UTC, stewartie4 requested changes
few final comments

2023-05-14 09:51 UTC, stewartie4 approved these changes

2023-05-14 09:51 UTC, stewartie4 approved these changes
Thanks @Jayashsatolia403 looks good

2023-05-14 13:19 UTC, merged