Referral tests
0chain/system_test pull request #677
Opened 2023-05-17 20:19 UTC by SrLeet03

2023-05-17 22:13 UTC, stewartie4 requested changes
some lint issues

2023-05-23 16:39 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | referral-tests  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | nft-cache  |
| 0dns  | staging  |

2023-05-24 21:20 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | referral-tests  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-25 14:01 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | referral-tests  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | nft-cache  |
| 0dns  | staging  |

2023-05-27 22:38 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | referral-tests  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | nft-cache  |
| 0dns  | staging  |

2023-05-29 20:27 UTC, Kishan-Dhakan commented
Passing run: https://github.com/0chain/0box/actions/runs/5113448332

2023-05-29 20:55 UTC, Kishan-Dhakan requested changes

2023-05-29 20:55 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Checking if wallet exists for [%v] using 0box...", phoneNumber)
Fix logging

2023-05-29 20:55 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Checking if wallet exists for [%v] using 0box...", phoneNumber)
Fix logging

2023-05-29 20:55 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Checking if wallet exists for [%v] using 0box...", phoneNumber)
Fix logging

2023-05-29 20:55 UTC, Kishan-Dhakan commented on tests/api_tests/0box_referral_test.go
> +	})
Does not need to be done twice 🤔

2023-05-29 20:59 UTC, Kishan-Dhakan approved these changes
LGTM

2023-05-29 21:11 UTC, Kishan-Dhakan commented on tests/api_tests/0box_referral_test.go
> +	})
resolved

2023-05-29 21:12 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Checking if wallet exists for [%v] using 0box...", phoneNumber)
resolved

2023-05-29 21:12 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Checking if wallet exists for [%v] using 0box...", phoneNumber)
resolved

2023-05-29 21:12 UTC, Kishan-Dhakan commented on internal/api/util/client/zbox_client.go
> +	t.Logf("Checking if wallet exists for [%v] using 0box...", phoneNumber)
resolved

2023-05-29 21:44 UTC, merged