Fix: unskip authorizer tests
0chain/system_test pull request #680
Opened 2023-05-19 13:10 UTC by YarikRevich

2023-05-19 23:24 UTC, Kishan-Dhakan requested changes
Please fix TestBridgeBurn/Get_WZCN_burn_ticket,_should_work, happy to merge after it is passing

2023-05-23 01:16 UTC, YarikRevich commented
This PR is blocked by the lack of graph-node deployment for system tests

2023-06-03 17:59 UTC, Kishan-Dhakan requested changes

2023-06-03 17:59 UTC, Kishan-Dhakan commented on .github/workflows/ci.yml
> +          go-version: '1.18'
Please revert, lint issues are fixed.

2023-06-17 23:03 UTC, stewartie4 reviewed
@YarikRevich what is the status of this PR?

2023-06-21 13:18 UTC, Kishan-Dhakan commented
@YarikRevich it's https://github.com/0chain/system_test/issues/717 this one, are you working on it?

2023-06-21 16:03 UTC, YarikRevich commented
@Kishan-Dhakan Yes, I'm working on IPFS deployment issue

2023-07-02 10:40 UTC, Kishan-Dhakan requested changes

2023-07-02 10:40 UTC, Kishan-Dhakan commented on tests/cli_tests/zwalletcli_zcnbridge_burn_test.go
> -	t.Skip("skip till authorizers are re-enabled")
Please skip all the other zcnbirdge tests as well

2023-07-30 08:23 UTC, Kishan-Dhakan approved these changes
LGTM, happy to merge pending passing tests

2023-08-03 18:55 UTC, Kishan-Dhakan commented
Passing run: https://github.com/0chain/system_test/actions/runs/5754104281/job/15599526710

![image](https://github.com/0chain/system_test/assets/42718091/47d8af41-5b70-464e-8d5f-b05ab36d7b98)

2023-08-03 19:22 UTC, merged