Tokenomics suite
0chain/system_test pull request #691
Opened 2023-05-23 14:27 UTC by Jayashsatolia403

2023-06-08 17:56 UTC, Kishan-Dhakan requested changes
Minor refactor needed, awesome PR

2023-06-08 17:56 UTC, Kishan-Dhakan commented on .github/workflows/ci.yml
> +          echo "TOKENOMICS_ALLOCATION_TESTS=$(echo $(([ -z 'TestAllocation' ] && echo '') || echo 'TestAllocation'))" >> $GITHUB_ENV
Please migrate this workflow to a different file and revert this ci.yaml, idea being that we want a tokenomics suite to be trigerred manually or through crons only, not on every commit.

2023-06-17 23:03 UTC, stewartie4 commented
Reviewing this shortly

2023-06-19 13:28 UTC, Kishan-Dhakan requested changes
Partial review

2023-06-19 13:28 UTC, Kishan-Dhakan commented on .github/workflows/tokenomics_ci.yml
> +name: "0Chain System Tests"
Please rename this to `Zus Tokenomics System Tests`

2023-06-19 21:07 UTC, stewartie4 reviewed
First scan looks great, if you need anything to help get this across the line let me know 
Amazing coverage

2023-06-19 21:07 UTC, stewartie4 commented on test-output.json
> +{"Time":"2023-05-13T00:54:38.445376049+05:30","Action":"output","Package":"github.com/0chain/system_test/internal/api/model","Output":"?   \tgithub.com/0chain/system_test/internal/api/model\t[no test
this can be removed

2023-06-19 21:07 UTC, stewartie4 commented on tests/tokenomics_tests/test-output.json
> +{"Time":"2023-05-13T00:55:50.355133007+05:30","Action":"start","Package":"github.com/0chain/system_test/tests/tokenomics_tests/utils"}
this can be removed

2023-06-19 21:07 UTC, stewartie4 commented on .github/workflows/tokenomics_ci.yml
> +name: "Zus Tokenomics System Tests"
should this run on cron on a nightly basis if not against the CI

2023-06-19 21:07 UTC, stewartie4 commented on tests/tokenomics_tests/config/wallets/UTC--2022-11-13T22-51-36.015115000Z--d8c9156e782c68ee671c09b6b92de76c97948432
> +{"address":"d8c9156e782c68ee671c09b6b92de76c97948432","crypto":{"cipher":"aes-128-ctr","ciphertext":"e4a7f436e5aaf5e70c4d599710d73e87555ca52f8e980609f318cb1b139a5731","cipherparams":{"iv":"e9ab45b3c3
can these be renamed to something more meaningful at a glance?

2023-06-19 21:07 UTC, stewartie4 commented on tests/tokenomics_tests/SUBSET_TEST_RUNNER_COMMAND.sh
> +[ -z "$1" ] && TESTS_TO_RUN="-run ^\QTestAllocation\E$ ./..." || TESTS_TO_RUN=$1
this should live in the actions repo

2023-06-20 04:13 UTC, Jayashsatolia403 commented on tests/tokenomics_tests/config/wallets/UTC--2022-11-13T22-51-36.015115000Z--d8c9156e782c68ee671c09b6b92de76c97948432
> +{"address":"d8c9156e782c68ee671c09b6b92de76c97948432","crypto":{"cipher":"aes-128-ctr","ciphertext":"e4a7f436e5aaf5e70c4d599710d73e87555ca52f8e980609f318cb1b139a5731","cipherparams":{"iv":"e9ab45b3c3
These are from cli tests only, I didn't add them.

2023-06-20 04:14 UTC, Jayashsatolia403 commented on tests/tokenomics_tests/SUBSET_TEST_RUNNER_COMMAND.sh
> +[ -z "$1" ] && TESTS_TO_RUN="-run ^\QTestAllocation\E$ ./..." || TESTS_TO_RUN=$1
We had a good discussion to keep it here only. @Kishan-Dhakan can clarify.

2023-07-18 14:24 UTC, closed without merging