Free stroage test
0chain/system_test pull request #698
Opened 2023-05-27 20:34 UTC by shalinikum

https://github.com/0chain/system_test/issues/657

2023-05-27 23:00 UTC, stewartie4 commented on tests/api_tests/config/api_tests_config.yaml
> +0box_url: https://0box.demo.zus.network
revert

2023-05-29 15:04 UTC, Kishan-Dhakan requested changes
Happy with the changes so far, needs some extension to fully cover the flow

2023-05-29 15:04 UTC, Kishan-Dhakan commented on tests/api_tests/0box_free_storage_test.go
> +		require.Positive(t, marker.FreeTokens)
There should also be a task_id being returned here, which needs to be used to poll the status of the funding task. In the polling, once response contains `funded` as `true`, you need to redeem the marker for allocation to be created. Also, confirm allocation is created from sharders.

2023-06-01 19:47 UTC, shalinikum commented on tests/api_tests/0box_free_storage_test.go
> +		require.Positive(t, marker.FreeTokens)
Done.

2023-06-01 19:51 UTC, shalinikum commented on tests/api_tests/config/api_tests_config.yaml
> +0box_url: https://0box.demo.zus.network
Done.

2023-06-03 15:23 UTC, Kishan-Dhakan approved these changes
LGTM

2023-06-03 15:49 UTC, merged