Fix allocation update method in blobber
0chain/system_test pull request #704
Opened 2023-06-01 11:26 UTC by Jayashsatolia403

Related PRs:

https://github.com/0chain/blobber/pull/1100
https://github.com/0chain/gosdk/pull/987
https://github.com/0chain/zboxcli/pull/442
https://github.com/0chain/0box/pull/669

2023-06-01 20:21 UTC, Kishan-Dhakan commented
Please mention related PRs

2023-06-13 17:44 UTC, Kishan-Dhakan requested changes

2023-06-13 17:44 UTC, Kishan-Dhakan commented on .github/workflows/ci.yml
> +          zs3_minio: pr-40-fb06fd07
Use staging in all

2023-06-13 17:44 UTC, Kishan-Dhakan commented on .github/workflows/ci.yml
> +          s3_migration_cli_branch: fix/allocation
use staging

2023-06-13 17:44 UTC, Kishan-Dhakan commented on go.mod
> +	github.com/0chain/gosdk v1.8.17-0.20230612181834-a31d2d7190fe
Update to staging since everything is merged

2023-06-13 17:44 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +	t.Skip()
Revert and remove unnecessary whitespace inserted above

2023-06-13 17:44 UTC, Kishan-Dhakan commented on tests/api_tests/blobber_hashnode_test.go
> -		require.Equal(t, "bad request: Invalid Allocation id. Allocation not found in blockchain.\n", string(restyResponse.Body()))
Don't remove this please, assert against an error. If there's no error or a not-so-meaningful error, it's a regression

2023-06-13 17:44 UTC, Kishan-Dhakan commented on tests/api_tests/config/api_tests_config.yaml
>  blobber_owner_wallet_mnemonics: "economy day fan flower between rebuild valid bid catch bargain vivid hybrid room permit check manage mean twelve damage summer close churn boat either"
Revert this file completely

2023-06-13 17:46 UTC, Kishan-Dhakan requested changes

2023-06-13 17:46 UTC, Kishan-Dhakan commented on tests/api_tests/0box_test.go
> +
Remove both these whitespaces please

2023-06-13 17:51 UTC, Kishan-Dhakan approved these changes

2023-06-13 19:51 UTC, Kishan-Dhakan approved these changes

2023-06-13 22:18 UTC, stewartie4 approved these changes

2023-06-13 22:18 UTC, merged