WIP : Unskip CLI tests
0chain/system_test pull request #745
Opened 2023-07-01 12:13 UTC by Jayashsatolia403

2023-07-05 20:53 UTC, Kishan-Dhakan requested changes
Minor comments + lint fixes please

2023-07-05 20:53 UTC, Kishan-Dhakan commented on tests/cli_tests/0_zboxcli_file_copy_test.go
> -			"localpath":  file,
Why is this being removed?

2023-07-05 20:53 UTC, Kishan-Dhakan commented on tests/cli_tests/0_zboxcli_file_copy_test.go
> +	t.TestSetup("register wallet and get blobbers", func() {
change description

2023-07-05 20:53 UTC, Kishan-Dhakan commented on tests/cli_tests/0_zboxcli_file_upload_test.go
> +	t.TestSetup("register wallet and get blobbers", func() {
update description, it's not registering or getting blobbers

2023-07-05 20:55 UTC, Kishan-Dhakan requested changes

2023-07-05 20:55 UTC, Kishan-Dhakan commented on tests/cli_tests/0_zboxcli_file_copy_test.go
> +	"math"
This file shouldn't need to be ran sequentially.

2023-07-05 20:55 UTC, Kishan-Dhakan commented on tests/cli_tests/0_zboxcli_file_upload_test.go
> +	"regexp"
This file shouldn't need to be ran sequentially

2023-07-05 21:00 UTC, Jayashsatolia403 commented on tests/cli_tests/0_zboxcli_file_copy_test.go
> +	"math"
It was to debug the runner issue only. Will revert it.

2023-07-23 14:37 UTC, Kishan-Dhakan requested changes

2023-07-23 14:37 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_copy_test.go
> +		t.Skip("Skipping until the issue that running it in workflow is fixed")
It's still skipped

2023-07-23 14:37 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		t.Skip("Skipping until the issue that running it in workflow is fixed")
It's still skipped.

2023-07-23 14:37 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_share_file_test.go
> -	})
Why is this removed? It's a passing test covering a negative flow.

2023-07-23 14:37 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_sync_test.go
> +	t.Run("BROKEN Sync path to non-empty allocation - locally updated files (in sub folder) must be updated in allocation but is not see zboxcli/issues/250", func(t *test.SystemTest) {
In fixed tests, please remove all `BROKEN` references

2023-07-23 17:25 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_share_file_test.go
> -	})
You can't share unencrypted file in private. We had this discussion earlier. 

I have another test that covered encrypted file share.

2023-07-23 17:25 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_sync_test.go
> +	t.Run("BROKEN Sync path to non-empty allocation - locally updated files (in sub folder) must be updated in allocation but is not see zboxcli/issues/250", func(t *test.SystemTest) {
Makes sense. Let me make the changes.

2023-07-27 19:01 UTC, Kishan-Dhakan reviewed
LGTM, but do not merge till full run

2023-08-08 10:52 UTC, Jayashsatolia403 commented
Full green run here against sprint branch

2023-08-08 14:09 UTC, Kishan-Dhakan approved these changes
lgtm

2023-08-08 14:15 UTC, merged