Fix blobber size tests
0chain/system_test pull request #753
Opened 2023-07-04 20:58 UTC by Jayashsatolia403

2023-07-04 21:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | sprint-july-1  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | sprint-july-1  |
| 0chain  | max_charge  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-05 13:51 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | fix/blobber_size  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/cache_allocation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-05 14:03 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | fix/download-filecallback  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | sprint-july-1  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-05 14:51 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | sprint-july-1  |
| zboxcli  | updategosdk  |
| zwalletcli  | updategosdk  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-05 17:50 UTC, Kishan-Dhakan requested changes

2023-07-05 17:50 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		require.Nil(t, err, strings.Join(output, "\n"))
I'm assuming the functionality has now changed to `can upload file == 100% size of the allocation`? 

Looks weird, if I create allocation of size 1 GB, 2 data 2 parity, then practically I'm storing 4 GB right?

2023-07-05 18:05 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		require.Nil(t, err, strings.Join(output, "\n"))
No you are practically storing 2gb and paying for 2 gb.

2023-07-05 18:06 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		require.Nil(t, err, strings.Join(output, "\n"))
Per blobber size is size of allocation divided by number of data shards.

2023-07-05 18:37 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		require.Nil(t, err, strings.Join(output, "\n"))
In that case, please change these 2 cases ("Upload File too large - parity shards take up allocation space - more than half Size of the Allocation Should not Fail when 1 parity shard" and "Upload File too large - parity shards take up allocation space - more than quarter Size of the Allocation Should not Fail when 3 parity shards") to this:
- Upload file 100% of allocation size should pass
- Upload file more than alloc size should fail

Testing for 50% and 75% doesn't make sense now.

2023-07-05 18:40 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		require.Nil(t, err, strings.Join(output, "\n"))
`Upload file more than alloc size should fail`

This is already covered. 

`Upload file 100% of allocation size should pass`

I am adding case for this. Thanks!!

2023-07-06 21:47 UTC, stewartie4 approved these changes

2023-07-08 19:48 UTC, Kishan-Dhakan commented
Passing run: https://github.com/0chain/system_test/actions/runs/5495805823/jobs/10015712756

2023-07-08 19:48 UTC, Kishan-Dhakan approved these changes

2023-07-08 19:48 UTC, merged