Fix err messages
0chain/system_test pull request #824
Opened 2023-08-14 22:55 UTC by din-mukhammed

https://github.com/0chain/zboxcli/pull/506 - main PR
https://github.com/0chain/gosdk/pull/1172
https://github.com/0chain/blobber/pull/1214

2023-08-15 19:03 UTC, Kishan-Dhakan commented
@din-mukhammed can you link the relevant PRs in the description? Would like to help with a full run as this looks like it has lot of breaking changes/error code changes

2023-08-19 22:37 UTC, stewartie4 requested changes
some queries

2023-08-19 22:37 UTC, stewartie4 commented on .github/workflows/nightly-current-sprint.yaml
> -    timeout-minutes: 120
we need some sort of timeout, is 2 hrs not enough?

2023-08-19 22:37 UTC, stewartie4 commented on tests/cli_tests/zboxcli_create_allocation_test.go
> +		require.Contains(t, strings.Join(output, ""), "consensus_not_met")
The previous error message was more user friendly

2023-08-19 22:37 UTC, stewartie4 commented on tests/cli_tests/zboxcli_create_dir_test.go
> +		require.Contains(t, aggregatedOutput, "consensus_not_met")
same here

2023-08-19 22:37 UTC, stewartie4 commented on tests/cli_tests/zboxcli_create_dir_test.go
> +		require.Equal(t, "CreateDir failed:  invalid_path: Path is not absolute", output[0])
again, the old message made more sense to the end user

2023-08-19 22:37 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_copy_test.go
> +		require.Contains(t, output[0], "Error performing CopyObject")
This is leaking internal info to the end user

2023-08-22 14:35 UTC, Kishan-Dhakan requested changes

2023-08-22 14:35 UTC, Kishan-Dhakan commented on .github/workflows/nightly-current-sprint.yaml
> +    timeout-minutes: 120
remove this

2023-08-29 09:16 UTC, Kishan-Dhakan approved these changes

2023-08-29 09:16 UTC, merged