Add tests for authorizers
0chain/system_test pull request #846
Opened 2023-08-29 14:58 UTC by peterlimg

- Add tests to register and delete authorizer from DEX SC 
- Add tests to register and delete authorizer from zcnsc

2023-10-10 00:03 UTC, YarikRevich requested changes

2023-10-10 00:03 UTC, YarikRevich commented on tests/cli_tests/zwalletcli_zcnbridge_add_and_rm_authorizer_test.go
I guess we can associate these test cases into one file regarding authorizer tests

2023-10-26 06:31 UTC, peterlimg commented on tests/cli_tests/zwalletcli_zcnbridge_auth_replace_burn_mint_test.go
> +	// but that's trivial and we have done the manual test to confirm the correct authorizers are used.
yes, the manual tests should be enough.

2023-10-27 18:20 UTC, Kishan-Dhakan approved these changes

2023-10-28 14:03 UTC, Kishan-Dhakan commented
Passing run https://github.com/0chain/system_test/actions/runs/6677271899/job/18147117920

2023-10-28 14:04 UTC, merged