Update allocation on forbid new allocation should work
0chain/system_test pull request #868
Opened 2023-09-27 13:48 UTC by Jayashsatolia403

2023-09-27 19:32 UTC, Kishan-Dhakan requested changes
MInor changes

2023-09-27 19:32 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +	t.Run("Update allocation on forbid new allocation should work", func(t *test.SystemTest) {
Since this is tampering with a blobber's availability, it can hamper other tests. Therfore it needs to be run either at the beginning of the suite or the end.

2023-09-27 19:32 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +		require.GreaterOrEqual(t, len(blobbers), 1)
Make it 2 (minimum for a allocation is 1 data 1 parity)

2023-09-27 19:32 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +		require.Greater(t, len(allocationID), 0)
What does this assertion accomplish? You can assert on regex pattern or simply leave out asserting on allocationID, it's tested elsewhere

2023-09-27 19:35 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +		require.GreaterOrEqual(t, len(blobbers), 1)
We need to make sure allocation creation fails.

2023-09-27 19:36 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +	t.Run("Update allocation on forbid new allocation should work", func(t *test.SystemTest) {
Let me add this in complete new file and the run it sequentially.

2023-09-27 20:00 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +		require.Greater(t, len(allocationID), 0)
Fixed

2023-09-28 12:40 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +		require.GreaterOrEqual(t, len(blobbers), 1)
Yes still need two blobbers otherwise allocation creation will fail but for different reason

2023-09-28 12:44 UTC, Kishan-Dhakan reviewed
This seems no longer related to the title `Update allocation on forbid new allocation should work`. The title suggests update allocation should work on an allocation that has used it's forbid options. But the test is trying to ascertain allocation can be extended even if 1 blobber is down. 

Please change the title or test and link relevant closing issue in the PR description for proper context

2023-09-28 12:46 UTC, Kishan-Dhakan approved these changes
Update the PR description and issue, lgtm now

2023-09-28 12:47 UTC, merged