Fix write pool unlock after alloc cancel
0chain/system_test pull request #877
Opened 2023-10-09 00:09 UTC by peterlimg

Fix write pool unlock failure after canceling allocation. The pool will be unlocked automatically when it's canceled

2023-10-10 12:24 UTC, Kishan-Dhakan requested changes

2023-10-10 12:24 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_wp_lock_unlock_test.go
And add testing for `cancel allocation will do unlock automatically`

2023-10-11 00:36 UTC, peterlimg commented on tests/cli_tests/zboxcli_wp_lock_unlock_test.go
This `cancel allocation will do unlock automatically` is tested here I think. Anyway, we can add explicit test case to do it.

2023-10-25 13:24 UTC, closed without merging

2023-10-25 13:25 UTC, Kishan-Dhakan commented
Closing as these commits are cleanly merged elsewhere
![image](https://github.com/0chain/system_test/assets/42718091/15421ac5-ec7e-46cf-8108-48ca175cb1d9)