Resume upload chunkNumber
0chain/system_test pull request #893
Opened 2023-10-12 19:17 UTC by Hitenjain14

2023-10-15 12:01 UTC, Kishan-Dhakan requested changes

2023-10-15 12:01 UTC, Kishan-Dhakan commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			"chunknumber": 500, // 64KB * 1024 = 64M
please update the comment

2023-10-15 13:48 UTC, Hitenjain14 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			"chunknumber": 500, // 64KB * 1024 = 64M
Updated the comment

2023-10-16 14:25 UTC, Kishan-Dhakan approved these changes

2023-10-16 14:25 UTC, merged