Fix/chimney blobber rewards
0chain/system_test pull request #898
Opened 2023-10-13 17:56 UTC by Jayashsatolia403

2023-10-26 10:42 UTC, stewartie4 commented on .github/workflows/chimney-and-blobber-tests.yaml
> +          system_tests_branch: fix/chimney-blobber-rewards
revert

2023-10-27 18:40 UTC, Kishan-Dhakan requested changes

2023-10-27 18:40 UTC, Kishan-Dhakan commented on tests/api_tests/chimney_blobber_rewards_test.go
> +			//}
remove dead code or uncomment

2023-10-28 19:10 UTC, stewartie4 approved these changes
LGTM thanks!

2023-10-28 20:07 UTC, merged