Updated chimney blobber rewards to work with 0 service charge
0chain/system_test pull request #930
Opened 2023-11-05 18:22 UTC by Jayashsatolia403

2023-11-07 20:12 UTC, stewartie4 requested changes

2023-11-07 20:12 UTC, stewartie4 commented on tests/api_tests/chimney_blobber_rewards_test.go
> +			t.Log("Expected Challenge Reward: ", expectedCancellationChargeForBlobber)
Remove all of the t.log in this file as the assertion will print out the expected and actual if it fails

2023-11-07 20:12 UTC, stewartie4 commented
small tweak needed, otherwise looks good

2023-11-07 21:25 UTC, Jayashsatolia403 commented on tests/api_tests/chimney_blobber_rewards_test.go
> +			t.Log("Expected Challenge Reward: ", expectedCancellationChargeForBlobber)
It does not in case of inepsilon.

2023-11-09 10:39 UTC, stewartie4 approved these changes

2023-11-09 17:59 UTC, merged