Feature/multi format file upload
0chain/system_test pull request #933
Opened 2023-11-07 01:40 UTC by Jayashsatolia403

2023-11-07 20:14 UTC, stewartie4 requested changes

2023-11-07 20:14 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			t.Log("Staking tokens for blobber: ", blobberId)
can be removed

2023-11-07 20:14 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		var fileExtensions = []string{".txt", ".docx", ".pdf", ".jpg", ".png", ".mp3", ".mp4", ".xlsx", ".html", ".json", ".csv", ".xml", ".zip", ".rar", ".gz", ".tar", ".avi", ".mov", ".wav", ".ogg", ".bm
do we need all of these? it's never going to be an extensive list, so why not make it shorter so the test takes less time to run>

2023-11-07 20:14 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			require.Equal(t, expected, output[1], "Failed to upload file with extension: "+ext)
The actual output should be returned in the message if the assertion fails

2023-11-07 20:53 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			t.Log("Staking tokens for blobber: ", blobberId)
Why do we want to remove staking?

2023-11-07 20:53 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +		var fileExtensions = []string{".txt", ".docx", ".pdf", ".jpg", ".png", ".mp3", ".mp4", ".xlsx", ".html", ".json", ".csv", ".xml", ".zip", ".rar", ".gz", ".tar", ".avi", ".mov", ".wav", ".ogg", ".bm
Yes, we do.

2023-11-07 20:55 UTC, Jayashsatolia403 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			require.Equal(t, expected, output[1], "Failed to upload file with extension: "+ext)
Fixing. Thanks!!

2023-11-08 08:45 UTC, stewartie4 commented on tests/cli_tests/zboxcli_file_upload_test.go
> +			t.Log("Staking tokens for blobber: ", blobberId)
We don't want to remove staking, we want to remove the superfluous log line

2023-11-08 20:03 UTC, merged