Modify test, cancel allocation is independant of challenges
0chain/system_test pull request #95
Opened 2021-11-03 13:41 UTC by Sriep

To work with 0chain PR https://github.com/0chain/0chain/pull/637. 
`cancelAllocation` no longer gives an error if not enough challenges have passed.

Passed test https://github.com/0chain/system_test/runs/4092818034?check_suite_focus=true

2021-11-03 21:00 UTC, stewartie4 commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +		require.NoError(t, err, "cancel allocation failed but should succeed")
assign _ on line 187 to variable called output
add Strings.join(output, "\n") as another String param to require.NoError
that will give good info if there is an error

2021-11-04 13:32 UTC, Sriep commented
Passed system test with 0chianPR https://github.com/0chain/0chain/pull/637  https://github.com/0chain/system_test/runs/4105276072?check_suite_focus=true

2021-11-04 14:49 UTC, stewartie4 commented
thanks, we can merge this once your change merges to staging

2021-11-04 16:40 UTC, Sriep commented
https://github.com/0chain/0chain/pull/637 has been merged

2021-11-04 22:30 UTC, stewartie4 commented on tests/cli_tests/zboxcli_update_allocation_test.go
> +	t.Run("Cancel_allocation_immediately_should_succeed", func(t *testing.T) {
There are already a tests for this in 
unhealthy_blobber_test.go ->
"cancel Allocation Should Work when blobber fails challenges"
"cancel Other's Allocation Should Fail"
You could just move these in here now that they no longer require a bad blobber

2021-11-05 19:21 UTC, stewartie4 requested changes
move existing test - see above

2021-11-12 14:09 UTC, stewartie4 commented
@Sriep thanks, happy to merge once staging has the code fix

2021-11-24 21:51 UTC, merged