Added negative TCs for resume upload feature of zbox cli
0chain/system_test pull request #979
Opened 2023-12-28 15:36 UTC by Zorro30

2023-12-30 14:11 UTC, Jayashsatolia403 requested changes
Please check comments

2023-12-30 15:15 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		fileSize := int64(500 * MB)
done

2023-12-30 15:17 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		defer func() {
These delete doesn't affect the flow right I am anyways creating a new file to upload in the second run right.

2023-12-30 15:20 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +
I have done the same I guess!

2023-12-30 15:21 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +	t.RunSequentiallyWithTimeout("Resume upload with diff allocationID", 10*time.Minute, func(t *test.SystemTest) {
okay

2023-12-30 15:33 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		err = createFileWithSize(filename, fileSize2)
We already have a positive case where we have same size scenario, hence only added a case for different szie.

2023-12-30 15:33 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +			"remotepath":  "/demo/",
I tried that, but even that was successful.

2023-12-30 15:35 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +			"remotepath":  "/demo/",
I added the 
```
remotepath : "/"
"localpath":   filename, #this has a different file size
```
still the testcase succeeded.

2023-12-30 16:49 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		require.NotNil(t, err, strings.Join(output, "\n"))
updated!

2023-12-31 01:13 UTC, Jayashsatolia403 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		err = createFileWithSize(filename, fileSize2)
Both are negative cases. same size different file and different size different file.

2023-12-31 01:15 UTC, Jayashsatolia403 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +			"remotepath":  "/demo/",
If resume on same path is successful, that is a bug in system. Please report issues on channel if you notice something like this.

Please revert back to resume on same path code and share a successful run.

2023-12-31 05:52 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		require.Nil(t, err, strings.Join(output, "\n"))
done

2023-12-31 05:53 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +			"remotepath":  "/demo/",
I have already reverted back to same path code & the system tests have passed for the PR.

2023-12-31 07:50 UTC, Jayashsatolia403 requested changes

2023-12-31 07:51 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		defer func() {
connected & resolved!

2023-12-31 10:38 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +
okay, added the a dummy path in remote path variable.

2023-12-31 10:39 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		err = createFileWithSize(filename, fileSize2)
okay added a separate case for diff filename having diff file size

2024-01-05 15:21 UTC, Jayashsatolia403 requested changes

2024-01-05 15:21 UTC, Jayashsatolia403 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		filename2 := generateRandomTestFileName(t)
Rename same file

2024-01-05 15:21 UTC, Jayashsatolia403 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		require.Contains(t, output[0],"no such file or directory")
Assert statement doesn't look correct.

2024-01-05 15:21 UTC, Jayashsatolia403 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +	t.RunSequentiallyWithTimeout("Resume upload with diff filesize and diff filename (Negative)", 10*time.Minute, func(t *test.SystemTest) {
It should be different file of same size.

2024-01-05 15:21 UTC, Jayashsatolia403 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +	t.RunSequentiallyWithTimeout("Resume upload with diff filesize having same filename (Negative)", 10*time.Minute, func(t *test.SystemTest) {
It should be different file of different size.

2024-01-06 11:54 UTC, zorro-30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		require.Contains(t, output[0],"no such file or directory")
the file path coming in local & dev network is not the same, cannot generalise the assertions, hence asserting it with the constant thing what also comes in error.

2024-01-06 11:54 UTC, zorro-30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +		filename2 := generateRandomTestFileName(t)
done

2024-01-17 04:36 UTC, Zorro30 commented on tests/cli_tests/0_zboxcli_file_resume_upload_test.go
> +	t.RunSequentiallyWithTimeout("Resume upload with diff filesize having same filename (Negative)", 10*time.Minute, func(t *test.SystemTest) {
Resolved

2024-02-21 22:21 UTC, merged