Add or Remove Curator system tests
0chain/system_test pull request #99
Opened 2021-11-03 21:52 UTC by mohsenno1

2021-11-04 21:07 UTC, stewartie4 approved these changes

2021-11-04 21:08 UTC, stewartie4 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +	t.Run("Add Curator _ Curator must be able to transfer the allocation ownership", func(t *testing.T) {
very minor: but I'd move the add tests before remove

2021-11-06 10:53 UTC, stewartie4 requested changes
some queries

2021-11-06 10:53 UTC, stewartie4 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +	t.Run("Add Curator _ must fail when the user is not the owner ", func(t *testing.T) {
This seems wrong to me
There is no such requirement that the curator must be the owner in the official docs.
Also if the only valid curator is the owner, why is there a "list" of curators (plural) 
The owner being the only valid curator defeats the purpose of the feature

2021-11-06 10:53 UTC, stewartie4 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +	t.Run("Add Curator _ Owner added as curator must be able to transfer the ownership", func(t *testing.T) {
This test is the same as above, worth keeping if we change the test above to not be the owner

2021-11-06 10:53 UTC, stewartie4 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +		output, err := registerWallet(t, configPath)
We don't use this for anything in this test

2021-11-06 10:53 UTC, stewartie4 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +	t.Run("Add Curator _ must fail when the user is not the owner ", func(t *testing.T) {
"Add Curator _ Curator must be able to transfer the allocation ownership" contradicts this test as a non-owner is added as a curator there

2021-11-06 20:10 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +	t.Run("Add Curator _ must fail when the user is not the owner ", func(t *testing.T) {
No, this seems to be like bad naming. Here by "user" I mean the operator which is adding the curator.
So if you are not the owner of an allocation then you cannot add someone else as the curator to that allocation.

2021-11-06 20:20 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +	t.Run("Add Curator _ must fail when the user is not the owner ", func(t *testing.T) {
I changed the test name to:

> Add Curator _ attempt to add curator by anyone except allocation owner must fail

2021-11-06 20:26 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +	t.Run("Add Curator _ Owner added as curator must be able to transfer the ownership", func(t *testing.T) {
The test are different. As I mentioned on the other comment, that is about testing if any one except allocation owner can add curator.
this is testing if after owner adds itself as curator is able to transfer the allocation.

2021-11-06 20:32 UTC, mohsenno1 commented on tests/cli_tests/zboxcli_add_remove_curator_test.go
> +		output, err := registerWallet(t, configPath)
you mean the wallet?
In this test we register a wallet and we create allocation by that. so this wallet is the owner. Then as the owner we add curatorWallet as curator. Then we test if curatorWallet is able to transfer allocation to a third party which is the targetWallet here.

2021-11-06 23:55 UTC, merged